// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var Approvals = Table[
	approvalColumns,
	approvalIndexes,
	approvalForeignKeys,
	approvalUniques,
	approvalChecks,
]{
	Schema: "",
	Name:   "approvals",
	Columns: approvalColumns{
		ID: column{
			Name:      "id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RunID: column{
			Name:      "run_id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RequestedBy: column{
			Name:      "requested_by",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ApprovedBy: column{
			Name:      "approved_by",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ApprovedAt: column{
			Name:      "approved_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: approvalIndexes{
		ApprovalsPkey: index{
			Type: "btree",
			Name: "approvals_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		ApprovalsRunIDKey: index{
			Type: "btree",
			Name: "approvals_run_id_key",
			Columns: []indexColumn{
				{
					Name:         "run_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxApprovalsStatus: index{
			Type: "btree",
			Name: "idx_approvals_status",
			Columns: []indexColumn{
				{
					Name:         "status",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "approvals_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: approvalForeignKeys{
		ApprovalsApprovalsApprovedByFkey: foreignKey{
			constraint: constraint{
				Name:    "approvals.approvals_approved_by_fkey",
				Columns: []string{"approved_by"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
		ApprovalsApprovalsRequestedByFkey: foreignKey{
			constraint: constraint{
				Name:    "approvals.approvals_requested_by_fkey",
				Columns: []string{"requested_by"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
		ApprovalsApprovalsRunIDFkey: foreignKey{
			constraint: constraint{
				Name:    "approvals.approvals_run_id_fkey",
				Columns: []string{"run_id"},
				Comment: "",
			},
			ForeignTable:   "task_runs",
			ForeignColumns: []string{"id"},
		},
	},
	Uniques: approvalUniques{
		ApprovalsRunIDKey: constraint{
			Name:    "approvals_run_id_key",
			Columns: []string{"run_id"},
			Comment: "",
		},
	},
	Checks: approvalChecks{
		ApprovalsStatusCheck: check{
			constraint: constraint{
				Name:    "approvals_status_check",
				Columns: []string{"status"},
				Comment: "",
			},
			Expression: "(status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text]))",
		},
	},
	Comment: "",
}

type approvalColumns struct {
	ID          column
	RunID       column
	Status      column
	RequestedBy column
	ApprovedBy  column
	CreatedAt   column
	ApprovedAt  column
}

func (c approvalColumns) AsSlice() []column {
	return []column{
		c.ID, c.RunID, c.Status, c.RequestedBy, c.ApprovedBy, c.CreatedAt, c.ApprovedAt,
	}
}

type approvalIndexes struct {
	ApprovalsPkey      index
	ApprovalsRunIDKey  index
	IdxApprovalsStatus index
}

func (i approvalIndexes) AsSlice() []index {
	return []index{
		i.ApprovalsPkey, i.ApprovalsRunIDKey, i.IdxApprovalsStatus,
	}
}

type approvalForeignKeys struct {
	ApprovalsApprovalsApprovedByFkey  foreignKey
	ApprovalsApprovalsRequestedByFkey foreignKey
	ApprovalsApprovalsRunIDFkey       foreignKey
}

func (f approvalForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.ApprovalsApprovalsApprovedByFkey, f.ApprovalsApprovalsRequestedByFkey, f.ApprovalsApprovalsRunIDFkey,
	}
}

type approvalUniques struct {
	ApprovalsRunIDKey constraint
}

func (u approvalUniques) AsSlice() []constraint {
	return []constraint{
		u.ApprovalsRunIDKey,
	}
}

type approvalChecks struct {
	ApprovalsStatusCheck check
}

func (c approvalChecks) AsSlice() []check {
	return []check{
		c.ApprovalsStatusCheck,
	}
}
