// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbinfo

import "github.com/aarondl/opt/null"

var TaskRuns = Table[
	taskRunColumns,
	taskRunIndexes,
	taskRunForeignKeys,
	taskRunUniques,
	taskRunChecks,
]{
	Schema: "",
	Name:   "task_runs",
	Columns: taskRunColumns{
		ID: column{
			Name:      "id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		ProjectID: column{
			Name:      "project_id",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		TemplateID: column{
			Name:      "template_id",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		Status: column{
			Name:      "status",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RequestedBy: column{
			Name:      "requested_by",
			DBType:    "text",
			Default:   "",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		StartedAt: column{
			Name:      "started_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		FinishedAt: column{
			Name:      "finished_at",
			DBType:    "timestamp with time zone",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
		CreatedAt: column{
			Name:      "created_at",
			DBType:    "timestamp with time zone",
			Default:   "now()",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RunSpec: column{
			Name:      "run_spec",
			DBType:    "jsonb",
			Default:   "'{}'::jsonb",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		Workflow: column{
			Name:      "workflow",
			DBType:    "jsonb",
			Default:   "'{\"steps\": []}'::jsonb",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		WorkflowState: column{
			Name:      "workflow_state",
			DBType:    "jsonb",
			Default:   "'{\"steps\": []}'::jsonb",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RunnerTags: column{
			Name:      "runner_tags",
			DBType:    "text[]",
			Default:   "'{}'::text[]",
			Comment:   "",
			Nullable:  false,
			Generated: false,
			AutoIncr:  false,
		},
		RunnerID: column{
			Name:      "runner_id",
			DBType:    "text",
			Default:   "NULL",
			Comment:   "",
			Nullable:  true,
			Generated: false,
			AutoIncr:  false,
		},
	},
	Indexes: taskRunIndexes{
		TaskRunsPkey: index{
			Type: "btree",
			Name: "task_runs_pkey",
			Columns: []indexColumn{
				{
					Name:         "id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        true,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxTaskRunsProjectID: index{
			Type: "btree",
			Name: "idx_task_runs_project_id",
			Columns: []indexColumn{
				{
					Name:         "project_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxTaskRunsRunnerID: index{
			Type: "btree",
			Name: "idx_task_runs_runner_id",
			Columns: []indexColumn{
				{
					Name:         "runner_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxTaskRunsStatus: index{
			Type: "btree",
			Name: "idx_task_runs_status",
			Columns: []indexColumn{
				{
					Name:         "status",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
		IdxTaskRunsTemplateID: index{
			Type: "btree",
			Name: "idx_task_runs_template_id",
			Columns: []indexColumn{
				{
					Name:         "template_id",
					Desc:         null.FromCond(false, true),
					IsExpression: false,
				},
			},
			Unique:        false,
			Comment:       "",
			NullsFirst:    []bool{false},
			NullsDistinct: false,
			Where:         "",
			Include:       []string{},
		},
	},
	PrimaryKey: &constraint{
		Name:    "task_runs_pkey",
		Columns: []string{"id"},
		Comment: "",
	},
	ForeignKeys: taskRunForeignKeys{
		TaskRunsTaskRunsProjectIDFkey: foreignKey{
			constraint: constraint{
				Name:    "task_runs.task_runs_project_id_fkey",
				Columns: []string{"project_id"},
				Comment: "",
			},
			ForeignTable:   "projects",
			ForeignColumns: []string{"id"},
		},
		TaskRunsTaskRunsRequestedByFkey: foreignKey{
			constraint: constraint{
				Name:    "task_runs.task_runs_requested_by_fkey",
				Columns: []string{"requested_by"},
				Comment: "",
			},
			ForeignTable:   "users",
			ForeignColumns: []string{"id"},
		},
		TaskRunsTaskRunsTemplateIDFkey: foreignKey{
			constraint: constraint{
				Name:    "task_runs.task_runs_template_id_fkey",
				Columns: []string{"template_id"},
				Comment: "",
			},
			ForeignTable:   "task_templates",
			ForeignColumns: []string{"id"},
		},
	},

	Checks: taskRunChecks{
		TaskRunsStatusCheck: check{
			constraint: constraint{
				Name:    "task_runs_status_check",
				Columns: []string{"status"},
				Comment: "",
			},
			Expression: "(status = ANY (ARRAY['queued'::text, 'waiting_approval'::text, 'running'::text, 'succeeded'::text, 'failed'::text, 'canceled'::text]))",
		},
	},
	Comment: "",
}

type taskRunColumns struct {
	ID            column
	ProjectID     column
	TemplateID    column
	Status        column
	RequestedBy   column
	StartedAt     column
	FinishedAt    column
	CreatedAt     column
	RunSpec       column
	Workflow      column
	WorkflowState column
	RunnerTags    column
	RunnerID      column
}

func (c taskRunColumns) AsSlice() []column {
	return []column{
		c.ID, c.ProjectID, c.TemplateID, c.Status, c.RequestedBy, c.StartedAt, c.FinishedAt, c.CreatedAt, c.RunSpec, c.Workflow, c.WorkflowState, c.RunnerTags, c.RunnerID,
	}
}

type taskRunIndexes struct {
	TaskRunsPkey          index
	IdxTaskRunsProjectID  index
	IdxTaskRunsRunnerID   index
	IdxTaskRunsStatus     index
	IdxTaskRunsTemplateID index
}

func (i taskRunIndexes) AsSlice() []index {
	return []index{
		i.TaskRunsPkey, i.IdxTaskRunsProjectID, i.IdxTaskRunsRunnerID, i.IdxTaskRunsStatus, i.IdxTaskRunsTemplateID,
	}
}

type taskRunForeignKeys struct {
	TaskRunsTaskRunsProjectIDFkey   foreignKey
	TaskRunsTaskRunsRequestedByFkey foreignKey
	TaskRunsTaskRunsTemplateIDFkey  foreignKey
}

func (f taskRunForeignKeys) AsSlice() []foreignKey {
	return []foreignKey{
		f.TaskRunsTaskRunsProjectIDFkey, f.TaskRunsTaskRunsRequestedByFkey, f.TaskRunsTaskRunsTemplateIDFkey,
	}
}

type taskRunUniques struct{}

func (u taskRunUniques) AsSlice() []constraint {
	return []constraint{}
}

type taskRunChecks struct {
	TaskRunsStatusCheck check
}

func (c taskRunChecks) AsSlice() []check {
	return []check{
		c.TaskRunsStatusCheck,
	}
}
