// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/google/go-cmp/cmp"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	testutils "github.com/stephenafamo/bob/test/utils"
)

var beforeTestingInsertRunLogWithSequence = func(context.Context, bob.Tx) ([]InsertRunLogWithSequence_Group80, error) {
	return []struct {
		ID        string
		RunID     string
		RunID2    string
		Sequence  int32
		Arg5      sql.Null[int32]
		Stream    string
		Message   string
		CreatedAt time.Time
	}{{
		ID:        random_string(nil),
		RunID:     random_string(nil),
		RunID2:    random_string(nil),
		Sequence:  random_int32(nil),
		Arg5:      sql.Null[int32]{V: random_int32(nil), Valid: true},
		Stream:    random_string(nil),
		Message:   random_string(nil),
		CreatedAt: random_time_Time(nil),
	}}, nil
}

func TestInsertRunLogWithSequence(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := InsertRunLogWithSequence([]struct {
			ID        string
			RunID     string
			RunID2    string
			Sequence  int32
			Arg5      sql.Null[int32]
			Stream    string
			Message   string
			CreatedAt time.Time
		}{{
			ID:        random_string(nil),
			RunID:     random_string(nil),
			RunID2:    random_string(nil),
			Sequence:  random_int32(nil),
			Arg5:      sql.Null[int32]{V: random_int32(nil), Valid: true},
			Stream:    random_string(nil),
			Message:   random_string(nil),
			CreatedAt: random_time_Time(nil),
		}})

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(insertRunLogWithSequenceSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := InsertRunLogWithSequence([]struct {
			ID        string
			RunID     string
			RunID2    string
			Sequence  int32
			Arg5      sql.Null[int32]
			Stream    string
			Message   string
			CreatedAt time.Time
		}{{
			ID:        random_string(nil),
			RunID:     random_string(nil),
			RunID2:    random_string(nil),
			Sequence:  random_int32(nil),
			Arg5:      sql.Null[int32]{V: random_int32(nil), Valid: true},
			Stream:    random_string(nil),
			Message:   random_string(nil),
			CreatedAt: random_time_Time(nil),
		}})

		if _, err := psql.Insert(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(insertRunLogWithSequenceSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		arg0, beforeHookErr := beforeTestingInsertRunLogWithSequence(ctxTx, tx)
		if beforeHookErr != nil {
			t.Fatalf("Error in beforeTesting: %v", beforeHookErr)
		}

		query, args, err := bob.Build(ctxTx, psql.Insert(InsertRunLogWithSequence(arg0)))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := rows.Close(); err != nil {
				t.Fatalf("Error closing rows: %v", err)
			}
		}()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 6 {
			t.Fatalf("expected %d columns, got %d", 6, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "run_id" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "run_id", columns[1])
		}

		if columns[2] != "sequence" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "sequence", columns[2])
		}

		if columns[3] != "stream" {
			t.Fatalf("expected column %d to be %s, got %s", 3, "stream", columns[3])
		}

		if columns[4] != "message" {
			t.Fatalf("expected column %d to be %s, got %s", 4, "message", columns[4])
		}

		if columns[5] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 5, "created_at", columns[5])
		}
	})
}

var beforeTestingExpireLeasesAndRequeueRuns = func(context.Context, bob.Tx) (time.Time, error) {
	return random_time_Time(nil), nil
}

func TestExpireLeasesAndRequeueRuns(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := ExpireLeasesAndRequeueRuns(random_time_Time(nil))

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(expireLeasesAndRequeueRunsSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := ExpireLeasesAndRequeueRuns(random_time_Time(nil))

		if _, err := psql.Update(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(expireLeasesAndRequeueRunsSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		arg0, beforeHookErr := beforeTestingExpireLeasesAndRequeueRuns(ctxTx, tx)
		if beforeHookErr != nil {
			t.Fatalf("Error in beforeTesting: %v", beforeHookErr)
		}

		query, args, err := bob.Build(ctxTx, psql.Update(ExpireLeasesAndRequeueRuns(arg0)))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := rows.Close(); err != nil {
				t.Fatalf("Error closing rows: %v", err)
			}
		}()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 1 {
			t.Fatalf("expected %d columns, got %d", 1, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}
	})
}

var beforeTestingMarkStaleRunners = func(context.Context, bob.Tx) (time.Time, error) {
	return random_time_Time(nil), nil
}

func TestMarkStaleRunners(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := MarkStaleRunners(random_time_Time(nil))

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(markStaleRunnersSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := MarkStaleRunners(random_time_Time(nil))

		if _, err := psql.Update(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(markStaleRunnersSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		arg0, beforeHookErr := beforeTestingMarkStaleRunners(ctxTx, tx)
		if beforeHookErr != nil {
			t.Fatalf("Error in beforeTesting: %v", beforeHookErr)
		}

		query, args, err := bob.Build(ctxTx, psql.Update(MarkStaleRunners(arg0)))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := rows.Close(); err != nil {
				t.Fatalf("Error closing rows: %v", err)
			}
		}()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 1 {
			t.Fatalf("expected %d columns, got %d", 1, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}
	})
}
