// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"context"
	_ "embed"
	"io"
	"iter"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

//go:embed identity.bob.sql
var formattedQueries_identity string

var principalBySessionTokenHashSQL = formattedQueries_identity[159:481]

type PrincipalBySessionTokenHashQuery = orm.ModQuery[*dialect.SelectQuery, principalBySessionTokenHash, PrincipalBySessionTokenHashRow, []PrincipalBySessionTokenHashRow, principalBySessionTokenHashTransformer]

func PrincipalBySessionTokenHash(TokenHash string, ExpiresAt time.Time) *PrincipalBySessionTokenHashQuery {
	var expressionTypArgs principalBySessionTokenHash

	expressionTypArgs.TokenHash = psql.Arg(TokenHash)
	expressionTypArgs.ExpiresAt = psql.Arg(ExpiresAt)

	return &PrincipalBySessionTokenHashQuery{
		Query: orm.Query[principalBySessionTokenHash, PrincipalBySessionTokenHashRow, []PrincipalBySessionTokenHashRow, principalBySessionTokenHashTransformer]{
			ExecQuery: orm.ExecQuery[principalBySessionTokenHash]{
				BaseQuery: bob.BaseQuery[principalBySessionTokenHash]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (PrincipalBySessionTokenHashRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t PrincipalBySessionTokenHashRow
						row.ScheduleScanByIndex(0, &t.ID)
						row.ScheduleScanByIndex(1, &t.Email)
						row.ScheduleScanByIndex(2, &t.Name)
						row.ScheduleScanByIndex(3, &t.Status)
						row.ScheduleScanByIndex(4, &t.GlobalRole)
						row.ScheduleScanByIndex(5, &t.PasswordHash)
						row.ScheduleScanByIndex(6, &t.CreatedAt)
						return &t, nil
					}, func(v any) (PrincipalBySessionTokenHashRow, error) {
						return *(v.(*PrincipalBySessionTokenHashRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(11, 140))
			q.SetTable(expressionTypArgs.subExpr(146, 196))
			q.AppendWhere(expressionTypArgs.subExpr(203, 322))
		}),
	}
}

type PrincipalBySessionTokenHashRow = struct {
	ID           string    `db:"id"`
	Email        string    `db:"email"`
	Name         string    `db:"name"`
	Status       string    `db:"status"`
	GlobalRole   string    `db:"global_role"`
	PasswordHash string    `db:"password_hash"`
	CreatedAt    time.Time `db:"created_at"`
}

type principalBySessionTokenHashTransformer = bob.SliceTransformer[PrincipalBySessionTokenHashRow, []PrincipalBySessionTokenHashRow]

type principalBySessionTokenHash struct {
	TokenHash bob.Expression
	ExpiresAt bob.Expression
}

func (o principalBySessionTokenHash) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "tokenHash",
			Start:      225,
			Stop:       227,
			Expression: o.TokenHash,
		}) {
			return
		}

		if !yield(orm.ArgWithPosition{
			Name:       "expiresAt",
			Start:      256,
			Stop:       258,
			Expression: o.ExpiresAt,
		}) {
			return
		}
	}
}

func (o principalBySessionTokenHash) raw(from, to int) string {
	return principalBySessionTokenHashSQL[from:to]
}

func (o principalBySessionTokenHash) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(principalBySessionTokenHashSQL, from, to, o.args())
}

func (o principalBySessionTokenHash) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(principalBySessionTokenHashSQL)).WriteSQL(ctx, w, d, start)
}
