// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"context"
	"database/sql"
	_ "embed"
	"io"
	"iter"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

//go:embed projects.bob.sql
var formattedQueries_projects string

var activeProjectsSQL = formattedQueries_projects[146:257]

type ActiveProjectsQuery = orm.ModQuery[*dialect.SelectQuery, activeProjects, ActiveProjectsRow, []ActiveProjectsRow, activeProjectsTransformer]

func ActiveProjects() *ActiveProjectsQuery {
	var expressionTypArgs activeProjects

	return &ActiveProjectsQuery{
		Query: orm.Query[activeProjects, ActiveProjectsRow, []ActiveProjectsRow, activeProjectsTransformer]{
			ExecQuery: orm.ExecQuery[activeProjects]{
				BaseQuery: bob.BaseQuery[activeProjects]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (ActiveProjectsRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t ActiveProjectsRow
						row.ScheduleScanByIndex(0, &t.ID)
						row.ScheduleScanByIndex(1, &t.Name)
						row.ScheduleScanByIndex(2, &t.Description)
						row.ScheduleScanByIndex(3, &t.CreatedAt)
						row.ScheduleScanByIndex(4, &t.ArchivedAt)
						return &t, nil
					}, func(v any) (ActiveProjectsRow, error) {
						return *(v.(*ActiveProjectsRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 53))
			q.SetTable(expressionTypArgs.subExpr(59, 67))
			q.AppendWhere(expressionTypArgs.subExpr(74, 93))
			q.CombinedOrder.AppendOrder(expressionTypArgs.subExpr(103, 111))
		}),
	}
}

type ActiveProjectsRow = struct {
	ID          string              `db:"id"`
	Name        string              `db:"name"`
	Description string              `db:"description"`
	CreatedAt   time.Time           `db:"created_at"`
	ArchivedAt  sql.Null[time.Time] `db:"archived_at"`
}

type activeProjectsTransformer = bob.SliceTransformer[ActiveProjectsRow, []ActiveProjectsRow]

type activeProjects struct{}

func (o activeProjects) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
	}
}

func (o activeProjects) raw(from, to int) string {
	return activeProjectsSQL[from:to]
}

func (o activeProjects) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(activeProjectsSQL, from, to, o.args())
}

func (o activeProjects) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(activeProjectsSQL)).WriteSQL(ctx, w, d, start)
}

var projectByIDSQL = formattedQueries_projects[275:380]

type ProjectByIDQuery = orm.ModQuery[*dialect.SelectQuery, projectByID, ProjectByIDRow, []ProjectByIDRow, projectByIDTransformer]

func ProjectByID(ID string) *ProjectByIDQuery {
	var expressionTypArgs projectByID

	expressionTypArgs.ID = psql.Arg(ID)

	return &ProjectByIDQuery{
		Query: orm.Query[projectByID, ProjectByIDRow, []ProjectByIDRow, projectByIDTransformer]{
			ExecQuery: orm.ExecQuery[projectByID]{
				BaseQuery: bob.BaseQuery[projectByID]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (ProjectByIDRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t ProjectByIDRow
						row.ScheduleScanByIndex(0, &t.ID)
						row.ScheduleScanByIndex(1, &t.Name)
						row.ScheduleScanByIndex(2, &t.Description)
						row.ScheduleScanByIndex(3, &t.CreatedAt)
						row.ScheduleScanByIndex(4, &t.ArchivedAt)
						return &t, nil
					}, func(v any) (ProjectByIDRow, error) {
						return *(v.(*ProjectByIDRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(7, 53))
			q.SetTable(expressionTypArgs.subExpr(59, 67))
			q.AppendWhere(expressionTypArgs.subExpr(74, 105))
		}),
	}
}

type ProjectByIDRow = struct {
	ID          string              `db:"id"`
	Name        string              `db:"name"`
	Description string              `db:"description"`
	CreatedAt   time.Time           `db:"created_at"`
	ArchivedAt  sql.Null[time.Time] `db:"archived_at"`
}

type projectByIDTransformer = bob.SliceTransformer[ProjectByIDRow, []ProjectByIDRow]

type projectByID struct {
	ID bob.Expression
}

func (o projectByID) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "id",
			Start:      79,
			Stop:       81,
			Expression: o.ID,
		}) {
			return
		}
	}
}

func (o projectByID) raw(from, to int) string {
	return projectByIDSQL[from:to]
}

func (o projectByID) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(projectByIDSQL, from, to, o.args())
}

func (o projectByID) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(projectByIDSQL)).WriteSQL(ctx, w, d, start)
}
