// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	testutils "github.com/stephenafamo/bob/test/utils"
)

var beforeTestingProjectMembers = func(context.Context, bob.Tx) error {
	return nil
}

func TestProjectMembers(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := ProjectMembers()

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(projectMembersSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := ProjectMembers()

		if _, err := psql.Select(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(projectMembersSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		beforeHookErr := beforeTestingProjectMembers(ctxTx, tx)
		if beforeHookErr != nil {
			t.Fatalf("Error in beforeTesting: %v", beforeHookErr)
		}

		query, args, err := bob.Build(ctxTx, psql.Select(ProjectMembers()))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := rows.Close(); err != nil {
				t.Fatalf("Error closing rows: %v", err)
			}
		}()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 8 {
			t.Fatalf("expected %d columns, got %d", 8, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "project_id" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "project_id", columns[1])
		}

		if columns[2] != "user_id" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "user_id", columns[2])
		}

		if columns[3] != "email" {
			t.Fatalf("expected column %d to be %s, got %s", 3, "email", columns[3])
		}

		if columns[4] != "name" {
			t.Fatalf("expected column %d to be %s, got %s", 4, "name", columns[4])
		}

		if columns[5] != "role" {
			t.Fatalf("expected column %d to be %s, got %s", 5, "role", columns[5])
		}

		if columns[6] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 6, "created_at", columns[6])
		}

		if columns[7] != "updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 7, "updated_at", columns[7])
		}
	})
}

var beforeTestingProjectMembersByProject = func(context.Context, bob.Tx) (string, error) {
	return random_string(nil), nil
}

func TestProjectMembersByProject(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := ProjectMembersByProject(random_string(nil))

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(projectMembersByProjectSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := ProjectMembersByProject(random_string(nil))

		if _, err := psql.Select(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(projectMembersByProjectSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		arg0, beforeHookErr := beforeTestingProjectMembersByProject(ctxTx, tx)
		if beforeHookErr != nil {
			t.Fatalf("Error in beforeTesting: %v", beforeHookErr)
		}

		query, args, err := bob.Build(ctxTx, psql.Select(ProjectMembersByProject(arg0)))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := rows.Close(); err != nil {
				t.Fatalf("Error closing rows: %v", err)
			}
		}()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 8 {
			t.Fatalf("expected %d columns, got %d", 8, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "project_id" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "project_id", columns[1])
		}

		if columns[2] != "user_id" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "user_id", columns[2])
		}

		if columns[3] != "email" {
			t.Fatalf("expected column %d to be %s, got %s", 3, "email", columns[3])
		}

		if columns[4] != "name" {
			t.Fatalf("expected column %d to be %s, got %s", 4, "name", columns[4])
		}

		if columns[5] != "role" {
			t.Fatalf("expected column %d to be %s, got %s", 5, "role", columns[5])
		}

		if columns[6] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 6, "created_at", columns[6])
		}

		if columns[7] != "updated_at" {
			t.Fatalf("expected column %d to be %s, got %s", 7, "updated_at", columns[7])
		}
	})
}
