// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"context"
	_ "embed"
	"io"
	"iter"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/scan"
)

//go:embed project_members.bob.sql
var formattedQueries_project_members string

var projectMembersSQL = formattedQueries_project_members[146:486]

type ProjectMembersQuery = orm.ModQuery[*dialect.SelectQuery, projectMembers, ProjectMembersRow, []ProjectMembersRow, projectMembersTransformer]

func ProjectMembers() *ProjectMembersQuery {
	var expressionTypArgs projectMembers

	return &ProjectMembersQuery{
		Query: orm.Query[projectMembers, ProjectMembersRow, []ProjectMembersRow, projectMembersTransformer]{
			ExecQuery: orm.ExecQuery[projectMembers]{
				BaseQuery: bob.BaseQuery[projectMembers]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (ProjectMembersRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t ProjectMembersRow
						row.ScheduleScanByIndex(0, &t.ID)
						row.ScheduleScanByIndex(1, &t.ProjectID)
						row.ScheduleScanByIndex(2, &t.UserID)
						row.ScheduleScanByIndex(3, &t.Email)
						row.ScheduleScanByIndex(4, &t.Name)
						row.ScheduleScanByIndex(5, &t.Role)
						row.ScheduleScanByIndex(6, &t.CreatedAt)
						row.ScheduleScanByIndex(7, &t.UpdatedAt)
						return &t, nil
					}, func(v any) (ProjectMembersRow, error) {
						return *(v.(*ProjectMembersRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(11, 213))
			q.SetTable(expressionTypArgs.subExpr(219, 283))
			q.CombinedOrder.AppendOrder(expressionTypArgs.subExpr(293, 340))
		}),
	}
}

type ProjectMembersRow = struct {
	ID        string    `db:"id"`
	ProjectID string    `db:"project_id"`
	UserID    string    `db:"user_id"`
	Email     string    `db:"email"`
	Name      string    `db:"name"`
	Role      string    `db:"role"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type projectMembersTransformer = bob.SliceTransformer[ProjectMembersRow, []ProjectMembersRow]

type projectMembers struct{}

func (o projectMembers) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
	}
}

func (o projectMembers) raw(from, to int) string {
	return projectMembersSQL[from:to]
}

func (o projectMembers) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(projectMembersSQL, from, to, o.args())
}

func (o projectMembers) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(projectMembersSQL)).WriteSQL(ctx, w, d, start)
}

var projectMembersByProjectSQL = formattedQueries_project_members[516:894]

type ProjectMembersByProjectQuery = orm.ModQuery[*dialect.SelectQuery, projectMembersByProject, ProjectMembersByProjectRow, []ProjectMembersByProjectRow, projectMembersByProjectTransformer]

func ProjectMembersByProject(ProjectID string) *ProjectMembersByProjectQuery {
	var expressionTypArgs projectMembersByProject

	expressionTypArgs.ProjectID = psql.Arg(ProjectID)

	return &ProjectMembersByProjectQuery{
		Query: orm.Query[projectMembersByProject, ProjectMembersByProjectRow, []ProjectMembersByProjectRow, projectMembersByProjectTransformer]{
			ExecQuery: orm.ExecQuery[projectMembersByProject]{
				BaseQuery: bob.BaseQuery[projectMembersByProject]{
					Expression: expressionTypArgs,
					Dialect:    dialect.Dialect,
					QueryType:  bob.QueryTypeSelect,
				},
			},
			Scanner: func(context.Context, []string) (func(*scan.Row) (any, error), func(any) (ProjectMembersByProjectRow, error)) {
				return func(row *scan.Row) (any, error) {
						var t ProjectMembersByProjectRow
						row.ScheduleScanByIndex(0, &t.ID)
						row.ScheduleScanByIndex(1, &t.ProjectID)
						row.ScheduleScanByIndex(2, &t.UserID)
						row.ScheduleScanByIndex(3, &t.Email)
						row.ScheduleScanByIndex(4, &t.Name)
						row.ScheduleScanByIndex(5, &t.Role)
						row.ScheduleScanByIndex(6, &t.CreatedAt)
						row.ScheduleScanByIndex(7, &t.UpdatedAt)
						return &t, nil
					}, func(v any) (ProjectMembersByProjectRow, error) {
						return *(v.(*ProjectMembersByProjectRow)), nil
					}
			},
		},
		Mod: bob.ModFunc[*dialect.SelectQuery](func(q *dialect.SelectQuery) {
			q.AppendSelect(expressionTypArgs.subExpr(11, 213))
			q.SetTable(expressionTypArgs.subExpr(219, 283))
			q.AppendWhere(expressionTypArgs.subExpr(290, 321))
			q.CombinedOrder.AppendOrder(expressionTypArgs.subExpr(331, 378))
		}),
	}
}

type ProjectMembersByProjectRow = struct {
	ID        string    `db:"id"`
	ProjectID string    `db:"project_id"`
	UserID    string    `db:"user_id"`
	Email     string    `db:"email"`
	Name      string    `db:"name"`
	Role      string    `db:"role"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type projectMembersByProjectTransformer = bob.SliceTransformer[ProjectMembersByProjectRow, []ProjectMembersByProjectRow]

type projectMembersByProject struct {
	ProjectID bob.Expression
}

func (o projectMembersByProject) args() iter.Seq[orm.ArgWithPosition] {
	return func(yield func(arg orm.ArgWithPosition) bool) {
		if !yield(orm.ArgWithPosition{
			Name:       "projectID",
			Start:      319,
			Stop:       321,
			Expression: o.ProjectID,
		}) {
			return
		}
	}
}

func (o projectMembersByProject) raw(from, to int) string {
	return projectMembersByProjectSQL[from:to]
}

func (o projectMembersByProject) subExpr(from, to int) bob.Expression {
	return orm.ArgsToExpression(projectMembersByProjectSQL, from, to, o.args())
}

func (o projectMembersByProject) WriteSQL(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
	return o.subExpr(0, len(projectMembersByProjectSQL)).WriteSQL(ctx, w, d, start)
}
