// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package queries

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	testutils "github.com/stephenafamo/bob/test/utils"
)

var beforeTestingActiveProjects = func(context.Context, bob.Tx) error {
	return nil
}

func TestActiveProjects(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := ActiveProjects()

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(activeProjectsSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := ActiveProjects()

		if _, err := psql.Select(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(activeProjectsSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		beforeHookErr := beforeTestingActiveProjects(ctxTx, tx)
		if beforeHookErr != nil {
			t.Fatalf("Error in beforeTesting: %v", beforeHookErr)
		}

		query, args, err := bob.Build(ctxTx, psql.Select(ActiveProjects()))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := rows.Close(); err != nil {
				t.Fatalf("Error closing rows: %v", err)
			}
		}()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 5 {
			t.Fatalf("expected %d columns, got %d", 5, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "name" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "name", columns[1])
		}

		if columns[2] != "description" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "description", columns[2])
		}

		if columns[3] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 3, "created_at", columns[3])
		}

		if columns[4] != "archived_at" {
			t.Fatalf("expected column %d to be %s, got %s", 4, "archived_at", columns[4])
		}
	})
}

var beforeTestingProjectByID = func(context.Context, bob.Tx) (string, error) {
	return random_string(nil), nil
}

func TestProjectByID(t *testing.T) {
	t.Run("Base", func(t *testing.T) {
		var sb strings.Builder

		query := ProjectByID(random_string(nil))

		if _, err := query.WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		if diff := cmp.Diff(projectByIDSQL, sb.String()); diff != "" {
			t.Fatalf("unexpected result (-got +want):\n%s", diff)
		}
	})

	t.Run("Mod", func(t *testing.T) {
		var sb strings.Builder

		query := ProjectByID(random_string(nil))

		if _, err := psql.Select(query).WriteQuery(t.Context(), &sb, 1); err != nil {
			t.Fatal(err)
		}

		queryDiff, err := testutils.QueryDiff(projectByIDSQL, sb.String(), formatQuery)
		if err != nil {
			t.Fatal(err)
		}
		if queryDiff != "" {
			fmt.Println(sb.String())
			t.Fatalf("unexpected result (-got +want):\n%s", queryDiff)
		}
	})

	t.Run("Scanning", func(t *testing.T) {
		if testDB == nil {
			t.Skip("skipping test, no DSN provided")
		}

		ctxTx, cancel := context.WithCancel(t.Context())
		defer cancel()

		tx, err := testDB.Begin(ctxTx)
		if err != nil {
			t.Fatalf("Error starting transaction: %v", err)
		}

		defer func() {
			if err := tx.Rollback(ctxTx); err != nil {
				t.Fatalf("Error rolling back transaction: %v", err)
			}
		}()

		arg0, beforeHookErr := beforeTestingProjectByID(ctxTx, tx)
		if beforeHookErr != nil {
			t.Fatalf("Error in beforeTesting: %v", beforeHookErr)
		}

		query, args, err := bob.Build(ctxTx, psql.Select(ProjectByID(arg0)))
		if err != nil {
			t.Fatal(err)
		}

		rows, err := tx.QueryContext(ctxTx, query, args...)
		if err != nil {
			t.Fatal(err)
		}
		defer func() {
			if err := rows.Close(); err != nil {
				t.Fatalf("Error closing rows: %v", err)
			}
		}()

		columns, err := rows.Columns()
		if err != nil {
			t.Fatal(err)
		}

		if len(columns) != 5 {
			t.Fatalf("expected %d columns, got %d", 5, len(columns))
		}

		if columns[0] != "id" {
			t.Fatalf("expected column %d to be %s, got %s", 0, "id", columns[0])
		}

		if columns[1] != "name" {
			t.Fatalf("expected column %d to be %s, got %s", 1, "name", columns[1])
		}

		if columns[2] != "description" {
			t.Fatalf("expected column %d to be %s, got %s", 2, "description", columns[2])
		}

		if columns[3] != "created_at" {
			t.Fatalf("expected column %d to be %s, got %s", 3, "created_at", columns[3])
		}

		if columns[4] != "archived_at" {
			t.Fatalf("expected column %d to be %s, got %s", 4, "archived_at", columns[4])
		}
	})
}
