// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: approvals.sql

package sqlcgen

import (
	"context"
	"time"
)

const createApproval = `-- name: CreateApproval :one
INSERT INTO approvals (id,run_id,status,requested_by,approved_by,created_at,approved_at)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, run_id, status, requested_by, approved_by, created_at, approved_at
`

type CreateApprovalParams struct {
	ID          string     `json:"id"`
	RunID       string     `json:"run_id"`
	Status      string     `json:"status"`
	RequestedBy string     `json:"requested_by"`
	ApprovedBy  *string    `json:"approved_by"`
	CreatedAt   time.Time  `json:"created_at"`
	ApprovedAt  *time.Time `json:"approved_at"`
}

func (q *Queries) CreateApproval(ctx context.Context, arg CreateApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, createApproval,
		arg.ID,
		arg.RunID,
		arg.Status,
		arg.RequestedBy,
		arg.ApprovedBy,
		arg.CreatedAt,
		arg.ApprovedAt,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}

const listApprovals = `-- name: ListApprovals :many
SELECT id, run_id, status, requested_by, approved_by, created_at, approved_at FROM approvals WHERE ($1::text='' OR status=$1) ORDER BY created_at DESC
`

func (q *Queries) ListApprovals(ctx context.Context, status string) ([]Approval, error) {
	rows, err := q.db.Query(ctx, listApprovals, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Approval{}
	for rows.Next() {
		var i Approval
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.CreatedAt,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveApproval = `-- name: ResolveApproval :one
UPDATE approvals SET status=$2,approved_by=$3,approved_at=$4
WHERE run_id=$1 AND status='pending' RETURNING id, run_id, status, requested_by, approved_by, created_at, approved_at
`

type ResolveApprovalParams struct {
	RunID      string     `json:"run_id"`
	Status     string     `json:"status"`
	ApprovedBy *string    `json:"approved_by"`
	ApprovedAt *time.Time `json:"approved_at"`
}

func (q *Queries) ResolveApproval(ctx context.Context, arg ResolveApprovalParams) (Approval, error) {
	row := q.db.QueryRow(ctx, resolveApproval,
		arg.RunID,
		arg.Status,
		arg.ApprovedBy,
		arg.ApprovedAt,
	)
	var i Approval
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.ApprovedAt,
	)
	return i, err
}
