// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: artifacts.sql

package sqlcgen

import (
	"context"
	"time"
)

const countArtifacts = `-- name: CountArtifacts :one
SELECT count(*) FROM run_artifacts WHERE ($1::text='' OR run_id=$1)
`

func (q *Queries) CountArtifacts(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRow(ctx, countArtifacts, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createArtifact = `-- name: CreateArtifact :one
INSERT INTO run_artifacts (id,run_id,lease_id,name,path,found,required,size,kind,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id, run_id, lease_id, name, path, found, required, size, kind, created_at
`

type CreateArtifactParams struct {
	ID        string    `json:"id"`
	RunID     string    `json:"run_id"`
	LeaseID   string    `json:"lease_id"`
	Name      string    `json:"name"`
	Path      string    `json:"path"`
	Found     bool      `json:"found"`
	Required  bool      `json:"required"`
	Size      int64     `json:"size"`
	Kind      string    `json:"kind"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateArtifact(ctx context.Context, arg CreateArtifactParams) (RunArtifact, error) {
	row := q.db.QueryRow(ctx, createArtifact,
		arg.ID,
		arg.RunID,
		arg.LeaseID,
		arg.Name,
		arg.Path,
		arg.Found,
		arg.Required,
		arg.Size,
		arg.Kind,
		arg.CreatedAt,
	)
	var i RunArtifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.LeaseID,
		&i.Name,
		&i.Path,
		&i.Found,
		&i.Required,
		&i.Size,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsPage = `-- name: ListArtifactsPage :many
SELECT id, run_id, lease_id, name, path, found, required, size, kind, created_at FROM run_artifacts WHERE ($1::text='' OR run_id=$1)
ORDER BY created_at, name LIMIT $3 OFFSET $2
`

type ListArtifactsPageParams struct {
	RunID      string `json:"run_id"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) ListArtifactsPage(ctx context.Context, arg ListArtifactsPageParams) ([]RunArtifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsPage, arg.RunID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunArtifact{}
	for rows.Next() {
		var i RunArtifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.LeaseID,
			&i.Name,
			&i.Path,
			&i.Found,
			&i.Required,
			&i.Size,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
