// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: audit.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const countAuditEvents = `-- name: CountAuditEvents :one
SELECT count(*) FROM audit_events
`

func (q *Queries) CountAuditEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditEvent = `-- name: CreateAuditEvent :exec
INSERT INTO audit_events (id,actor_id,action,target_id,metadata,created_at)
VALUES ($1,$2,$3,$4,$5,$6)
`

type CreateAuditEventParams struct {
	ID        string          `json:"id"`
	ActorID   string          `json:"actor_id"`
	Action    string          `json:"action"`
	TargetID  string          `json:"target_id"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, createAuditEvent,
		arg.ID,
		arg.ActorID,
		arg.Action,
		arg.TargetID,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const createSecretAccessAudit = `-- name: CreateSecretAccessAudit :one
INSERT INTO audit_events (id,actor_id,action,target_id,metadata,created_at)
VALUES ($1,$2,'secret.access',$3,$4,clock_timestamp())
RETURNING id, actor_id, action, target_id, metadata, created_at
`

type CreateSecretAccessAuditParams struct {
	ID       string          `json:"id"`
	ActorID  string          `json:"actor_id"`
	TargetID string          `json:"target_id"`
	Metadata json.RawMessage `json:"metadata"`
}

func (q *Queries) CreateSecretAccessAudit(ctx context.Context, arg CreateSecretAccessAuditParams) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, createSecretAccessAudit,
		arg.ID,
		arg.ActorID,
		arg.TargetID,
		arg.Metadata,
	)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditEventByID = `-- name: GetAuditEventByID :one
SELECT id, actor_id, action, target_id, metadata, created_at FROM audit_events WHERE id=$1
`

func (q *Queries) GetAuditEventByID(ctx context.Context, id string) (AuditEvent, error) {
	row := q.db.QueryRow(ctx, getAuditEventByID, id)
	var i AuditEvent
	err := row.Scan(
		&i.ID,
		&i.ActorID,
		&i.Action,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getRunContextForSecretAccess = `-- name: GetRunContextForSecretAccess :one
SELECT run_spec,workflow,workflow_state FROM task_runs WHERE id=$1
`

type GetRunContextForSecretAccessRow struct {
	RunSpec       json.RawMessage `json:"run_spec"`
	Workflow      json.RawMessage `json:"workflow"`
	WorkflowState json.RawMessage `json:"workflow_state"`
}

func (q *Queries) GetRunContextForSecretAccess(ctx context.Context, id string) (GetRunContextForSecretAccessRow, error) {
	row := q.db.QueryRow(ctx, getRunContextForSecretAccess, id)
	var i GetRunContextForSecretAccessRow
	err := row.Scan(&i.RunSpec, &i.Workflow, &i.WorkflowState)
	return i, err
}

const listAuditEventsPage = `-- name: ListAuditEventsPage :many
SELECT id, actor_id, action, target_id, metadata, created_at FROM audit_events ORDER BY created_at DESC, id DESC LIMIT $1 OFFSET $2
`

type ListAuditEventsPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditEventsPage(ctx context.Context, arg ListAuditEventsPageParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEventsPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditEvent{}
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
