// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: identity.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (id, name, kind, token_hash, roles, status, created_by, created_at, expires_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING id, name, kind, token_hash, roles, status, created_by, created_at, expires_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Kind      string     `json:"kind"`
	TokenHash string     `json:"token_hash"`
	Roles     []string   `json:"roles"`
	Status    string     `json:"status"`
	CreatedBy string     `json:"created_by"`
	CreatedAt time.Time  `json:"created_at"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.TokenHash,
		arg.Roles,
		arg.Status,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.TokenHash,
		&i.Roles,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, user_id, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
UPDATE api_tokens SET last_used_at = $2
WHERE token_hash = $1 AND status = 'active' AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > $2)
RETURNING id, name, kind, token_hash, roles, status, created_by, created_at, expires_at, last_used_at, revoked_at
`

type GetAPITokenByHashParams struct {
	TokenHash  string     `json:"token_hash"`
	LastUsedAt *time.Time `json:"last_used_at"`
}

func (q *Queries) GetAPITokenByHash(ctx context.Context, arg GetAPITokenByHashParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, arg.TokenHash, arg.LastUsedAt)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.TokenHash,
		&i.Roles,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPrincipalBySessionTokenHash = `-- name: GetPrincipalBySessionTokenHash :one
SELECT users.id, users.email, users.name, users.status, users.global_role,
       users.password_hash, users.created_at, users.updated_at, users.archived_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.revoked_at IS NULL
  AND sessions.expires_at > $2
  AND users.status = 'active'
`

type GetPrincipalBySessionTokenHashParams struct {
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetPrincipalBySessionTokenHash(ctx context.Context, arg GetPrincipalBySessionTokenHashParams) (User, error) {
	row := q.db.QueryRow(ctx, getPrincipalBySessionTokenHash, arg.TokenHash, arg.ExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.GlobalRole,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, status, global_role, password_hash, created_at, updated_at, archived_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.GlobalRole,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const revokeAPIToken = `-- name: RevokeAPIToken :one
UPDATE api_tokens SET status = 'revoked', revoked_at = $2
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, name, kind, token_hash, roles, status, created_by, created_at, expires_at, last_used_at, revoked_at
`

type RevokeAPITokenParams struct {
	ID        string     `json:"id"`
	RevokedAt *time.Time `json:"revoked_at"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, revokeAPIToken, arg.ID, arg.RevokedAt)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.TokenHash,
		&i.Roles,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :execrows
UPDATE sessions SET revoked_at = $2
WHERE token_hash = $1 AND revoked_at IS NULL
`

type RevokeSessionByTokenHashParams struct {
	TokenHash string     `json:"token_hash"`
	RevokedAt *time.Time `json:"revoked_at"`
}

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, arg RevokeSessionByTokenHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSessionByTokenHash, arg.TokenHash, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
