// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlcgen

import (
	"encoding/json"
	"time"
)

type AccessKey struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Name        string    `json:"name"`
	Kind        string    `json:"kind"`
	Fingerprint string    `json:"fingerprint"`
	CreatedAt   time.Time `json:"created_at"`
}

type ApiToken struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Kind       string     `json:"kind"`
	TokenHash  string     `json:"token_hash"`
	Roles      []string   `json:"roles"`
	Status     string     `json:"status"`
	CreatedBy  string     `json:"created_by"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  *time.Time `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

type Approval struct {
	ID          string     `json:"id"`
	RunID       string     `json:"run_id"`
	Status      string     `json:"status"`
	RequestedBy string     `json:"requested_by"`
	ApprovedBy  *string    `json:"approved_by"`
	CreatedAt   time.Time  `json:"created_at"`
	ApprovedAt  *time.Time `json:"approved_at"`
}

type AuditEvent struct {
	ID        string          `json:"id"`
	ActorID   string          `json:"actor_id"`
	Action    string          `json:"action"`
	TargetID  string          `json:"target_id"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
}

type Inventory struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
}

type Project struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ArchivedAt  *time.Time `json:"archived_at"`
}

type ProjectMember struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Repository struct {
	ID         string    `json:"id"`
	ProjectID  string    `json:"project_id"`
	Name       string    `json:"name"`
	Url        string    `json:"url"`
	Provider   string    `json:"provider"`
	DefaultRef string    `json:"default_ref"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type RunArtifact struct {
	ID        string    `json:"id"`
	RunID     string    `json:"run_id"`
	LeaseID   string    `json:"lease_id"`
	Name      string    `json:"name"`
	Path      string    `json:"path"`
	Found     bool      `json:"found"`
	Required  bool      `json:"required"`
	Size      int64     `json:"size"`
	Kind      string    `json:"kind"`
	CreatedAt time.Time `json:"created_at"`
}

type RunLease struct {
	ID            string     `json:"id"`
	RunID         string     `json:"run_id"`
	RunnerID      string     `json:"runner_id"`
	Status        string     `json:"status"`
	ExpiresAt     time.Time  `json:"expires_at"`
	CreatedAt     time.Time  `json:"created_at"`
	CompletedAt   *time.Time `json:"completed_at"`
	Attempt       int32      `json:"attempt"`
	Fence         string     `json:"fence"`
	CompletionKey *string    `json:"completion_key"`
}

type RunLog struct {
	ID                string    `json:"id"`
	RunID             string    `json:"run_id"`
	Sequence          int32     `json:"sequence"`
	Stream            string    `json:"stream"`
	Message           string    `json:"message"`
	CreatedAt         time.Time `json:"created_at"`
	EventKey          *string   `json:"event_key"`
	LeaseID           *string   `json:"lease_id"`
	Attempt           *int32    `json:"attempt"`
	RequestedSequence *int32    `json:"requested_sequence"`
}

type Runner struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	Tags            []string  `json:"tags"`
	Capabilities    []string  `json:"capabilities"`
	Status          string    `json:"status"`
	RegisteredAt    time.Time `json:"registered_at"`
	LastHeartbeatAt time.Time `json:"last_heartbeat_at"`
	TokenHash       string    `json:"token_hash"`
}

type RunnerClaimCursor struct {
	RunnerID     string     `json:"runner_id"`
	RunID        *string    `json:"run_id"`
	UpdatedAt    time.Time  `json:"updated_at"`
	ClaimOrderAt *time.Time `json:"claim_order_at"`
}

type RunnerEnrollment struct {
	ID               string     `json:"id"`
	TokenHash        string     `json:"token_hash"`
	RunnerID         string     `json:"runner_id"`
	RunnerName       string     `json:"runner_name"`
	Tags             []string   `json:"tags"`
	Capabilities     []string   `json:"capabilities"`
	CreatedBy        string     `json:"created_by"`
	CreatedAt        time.Time  `json:"created_at"`
	ExpiresAt        time.Time  `json:"expires_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
	UsedAt           *time.Time `json:"used_at"`
	ConsumeRequestID *string    `json:"consume_request_id"`
	CredentialHash   *string    `json:"credential_hash"`
}

type Session struct {
	ID        string     `json:"id"`
	UserID    string     `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	CreatedAt time.Time  `json:"created_at"`
	RevokedAt *time.Time `json:"revoked_at"`
}

type TaskRun struct {
	ID            string          `json:"id"`
	ProjectID     string          `json:"project_id"`
	TemplateID    *string         `json:"template_id"`
	RunSpec       json.RawMessage `json:"run_spec"`
	Workflow      json.RawMessage `json:"workflow"`
	RunnerTags    []string        `json:"runner_tags"`
	Status        string          `json:"status"`
	RunnerID      *string         `json:"runner_id"`
	RequestedBy   string          `json:"requested_by"`
	StartedAt     time.Time       `json:"started_at"`
	FinishedAt    *time.Time      `json:"finished_at"`
	CreatedAt     time.Time       `json:"created_at"`
	WorkflowState json.RawMessage `json:"workflow_state"`
	NextAttempt   int32           `json:"next_attempt"`
	ClaimOrderAt  time.Time       `json:"claim_order_at"`
}

type TaskTemplate struct {
	ID            string          `json:"id"`
	ProjectID     string          `json:"project_id"`
	Name          string          `json:"name"`
	Kind          string          `json:"kind"`
	RunSpec       json.RawMessage `json:"run_spec"`
	Workflow      json.RawMessage `json:"workflow"`
	WorkflowState json.RawMessage `json:"workflow_state"`
	RunnerTags    []string        `json:"runner_tags"`
	RequiresAck   bool            `json:"requires_ack"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type User struct {
	ID           string     `json:"id"`
	Email        string     `json:"email"`
	Name         string     `json:"name"`
	Status       string     `json:"status"`
	GlobalRole   string     `json:"global_role"`
	PasswordHash string     `json:"password_hash"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	ArchivedAt   *time.Time `json:"archived_at"`
}
