// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlcgen

import (
	"encoding/json"
	"time"
)

type AccessKey struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Name        string    `json:"name"`
	Kind        string    `json:"kind"`
	Fingerprint string    `json:"fingerprint"`
	CreatedAt   time.Time `json:"created_at"`
}

type ApiToken struct {
	ID         string     `json:"id"`
	Name       string     `json:"name"`
	Kind       string     `json:"kind"`
	TokenHash  string     `json:"token_hash"`
	Roles      []string   `json:"roles"`
	Status     string     `json:"status"`
	CreatedBy  string     `json:"created_by"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  *time.Time `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

type Approval struct {
	ID          string     `json:"id"`
	RunID       string     `json:"run_id"`
	Status      string     `json:"status"`
	RequestedBy string     `json:"requested_by"`
	ApprovedBy  *string    `json:"approved_by"`
	CreatedAt   time.Time  `json:"created_at"`
	ApprovedAt  *time.Time `json:"approved_at"`
}

type AuditEvent struct {
	ID        string          `json:"id"`
	ActorID   string          `json:"actor_id"`
	Action    string          `json:"action"`
	TargetID  string          `json:"target_id"`
	Metadata  json.RawMessage `json:"metadata"`
	CreatedAt time.Time       `json:"created_at"`
}

type BackupOperationalResult struct {
	ID          int64     `json:"id"`
	CompletedAt time.Time `json:"completed_at"`
	Outcome     string    `json:"outcome"`
	Reason      string    `json:"reason"`
}

type BackupSchedule struct {
	Singleton           bool      `json:"singleton"`
	Enabled             bool      `json:"enabled"`
	IntervalSeconds     int32     `json:"interval_seconds"`
	RetentionCount      int32     `json:"retention_count"`
	NextRunAt           time.Time `json:"next_run_at"`
	ConsecutiveFailures int32     `json:"consecutive_failures"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type BackupScheduleRun struct {
	ID           string     `json:"id"`
	ScheduledFor time.Time  `json:"scheduled_for"`
	StartedAt    time.Time  `json:"started_at"`
	CompletedAt  *time.Time `json:"completed_at"`
	Status       string     `json:"status"`
	Reason       string     `json:"reason"`
}

type Deployment struct {
	ID                        string     `json:"id"`
	EnvironmentID             string     `json:"environment_id"`
	DesiredRevisionID         string     `json:"desired_revision_id"`
	PreviousHealthyRevisionID *string    `json:"previous_healthy_revision_id"`
	TaskRunID                 string     `json:"task_run_id"`
	IdempotencyKey            string     `json:"idempotency_key"`
	Status                    string     `json:"status"`
	RequestedBy               string     `json:"requested_by"`
	ConfirmedBy               *string    `json:"confirmed_by"`
	CreatedAt                 time.Time  `json:"created_at"`
	UpdatedAt                 time.Time  `json:"updated_at"`
	FinishedAt                *time.Time `json:"finished_at"`
	HealthPassed              *bool      `json:"health_passed"`
	RollbackOfID              *string    `json:"rollback_of_id"`
	FailureCode               string     `json:"failure_code"`
	FenceRequired             bool       `json:"fence_required"`
}

type DeploymentAttempt struct {
	DeploymentID string     `json:"deployment_id"`
	RunID        string     `json:"run_id"`
	LeaseID      string     `json:"lease_id"`
	RunnerID     string     `json:"runner_id"`
	Attempt      int32      `json:"attempt"`
	Fence        string     `json:"fence"`
	CreatedAt    time.Time  `json:"created_at"`
	FinishedAt   *time.Time `json:"finished_at"`
	Status       string     `json:"status"`
}

type DeploymentCancellation struct {
	DeploymentID string    `json:"deployment_id"`
	RequestID    string    `json:"request_id"`
	ActorID      string    `json:"actor_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type DeploymentTransition struct {
	DeploymentID   string          `json:"deployment_id"`
	Attempt        int32           `json:"attempt"`
	TransitionKey  string          `json:"transition_key"`
	ExpectedStatus string          `json:"expected_status"`
	TargetStatus   string          `json:"target_status"`
	HealthPassed   *bool           `json:"health_passed"`
	FailureCode    string          `json:"failure_code"`
	Metadata       json.RawMessage `json:"metadata"`
	CreatedAt      time.Time       `json:"created_at"`
}

type Environment struct {
	ID                       string          `json:"id"`
	ServiceID                string          `json:"service_id"`
	Name                     string          `json:"name"`
	RunnerSelector           []string        `json:"runner_selector"`
	ComposeProject           string          `json:"compose_project"`
	HealthPolicy             json.RawMessage `json:"health_policy"`
	ConfirmationRequired     bool            `json:"confirmation_required"`
	TimeoutSeconds           int32           `json:"timeout_seconds"`
	SecretBindings           json.RawMessage `json:"secret_bindings"`
	RollbackSafe             bool            `json:"rollback_safe"`
	CurrentHealthyRevisionID *string         `json:"current_healthy_revision_id"`
	CreatedAt                time.Time       `json:"created_at"`
}

type IdentityBootstrapState struct {
	Singleton   bool       `json:"singleton"`
	CompletedBy *string    `json:"completed_by"`
	CompletedAt *time.Time `json:"completed_at"`
}

type Inventory struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
}

type OidcExternalIdentity struct {
	Issuer    string    `json:"issuer"`
	Subject   string    `json:"subject"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type OidcLoginFlow struct {
	ID           string    `json:"id"`
	StateHash    string    `json:"state_hash"`
	NonceHash    string    `json:"nonce_hash"`
	VerifierHash string    `json:"verifier_hash"`
	RedirectPath string    `json:"redirect_path"`
	Issuer       string    `json:"issuer"`
	ClientID     string    `json:"client_id"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type Project struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
	ArchivedAt  *time.Time `json:"archived_at"`
}

type ProjectMember struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	UserID    string    `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ProvenanceResolution struct {
	DeploymentID    string    `json:"deployment_id"`
	Attempt         int32     `json:"attempt"`
	ResolutionID    string    `json:"resolution_id"`
	RunID           string    `json:"run_id"`
	LeaseID         string    `json:"lease_id"`
	RunnerID        string    `json:"runner_id"`
	Fence           string    `json:"fence"`
	RevisionID      string    `json:"revision_id"`
	GitCommit       string    `json:"git_commit"`
	ComposeHash     string    `json:"compose_hash"`
	ImageDigests    []string  `json:"image_digests"`
	ContentIdentity string    `json:"content_identity"`
	AuditID         string    `json:"audit_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type Repository struct {
	ID               string          `json:"id"`
	ProjectID        string          `json:"project_id"`
	Name             string          `json:"name"`
	Url              string          `json:"url"`
	Provider         string          `json:"provider"`
	DefaultRef       string          `json:"default_ref"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
	RepositoryPolicy json.RawMessage `json:"repository_policy"`
}

type RepositoryPolicyConfigurationReceipt struct {
	RepositoryID    string    `json:"repository_id"`
	ConfigurationID string    `json:"configuration_id"`
	ActorID         string    `json:"actor_id"`
	PolicySha256    string    `json:"policy_sha256"`
	AuditID         string    `json:"audit_id"`
	CreatedAt       time.Time `json:"created_at"`
}

type Revision struct {
	ID                 string     `json:"id"`
	ServiceID          string     `json:"service_id"`
	RequestedRef       string     `json:"requested_ref"`
	GitCommit          string     `json:"git_commit"`
	ComposeHash        string     `json:"compose_hash"`
	ImageDigests       []string   `json:"image_digests"`
	ContentIdentity    string     `json:"content_identity"`
	CreatedBy          string     `json:"created_by"`
	CreatedAt          time.Time  `json:"created_at"`
	ProvenanceState    string     `json:"provenance_state"`
	ProvenanceResolved bool       `json:"provenance_resolved"`
	ResolvedAt         *time.Time `json:"resolved_at"`
}

type RunArtifact struct {
	ID        string    `json:"id"`
	RunID     string    `json:"run_id"`
	LeaseID   string    `json:"lease_id"`
	Name      string    `json:"name"`
	Path      string    `json:"path"`
	Found     bool      `json:"found"`
	Required  bool      `json:"required"`
	Size      int64     `json:"size"`
	Kind      string    `json:"kind"`
	CreatedAt time.Time `json:"created_at"`
}

type RunLease struct {
	ID            string     `json:"id"`
	RunID         string     `json:"run_id"`
	RunnerID      string     `json:"runner_id"`
	Status        string     `json:"status"`
	ExpiresAt     time.Time  `json:"expires_at"`
	CreatedAt     time.Time  `json:"created_at"`
	CompletedAt   *time.Time `json:"completed_at"`
	Attempt       int32      `json:"attempt"`
	Fence         string     `json:"fence"`
	CompletionKey *string    `json:"completion_key"`
}

type RunLog struct {
	ID                string    `json:"id"`
	RunID             string    `json:"run_id"`
	Sequence          int32     `json:"sequence"`
	Stream            string    `json:"stream"`
	Message           string    `json:"message"`
	CreatedAt         time.Time `json:"created_at"`
	EventKey          *string   `json:"event_key"`
	LeaseID           *string   `json:"lease_id"`
	Attempt           *int32    `json:"attempt"`
	RequestedSequence *int32    `json:"requested_sequence"`
}

type RunLogRetentionPolicy struct {
	Singleton bool      `json:"singleton"`
	Enabled   bool      `json:"enabled"`
	KeepDays  int32     `json:"keep_days"`
	BatchSize int32     `json:"batch_size"`
	Version   int32     `json:"version"`
	UpdatedBy string    `json:"updated_by"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RunLogRetentionReceipt struct {
	RequestID     string    `json:"request_id"`
	BodySha256    string    `json:"body_sha256"`
	KeepDays      int32     `json:"keep_days"`
	BatchSize     int32     `json:"batch_size"`
	PolicyVersion int32     `json:"policy_version"`
	Cutoff        time.Time `json:"cutoff"`
	EligibleLogs  int64     `json:"eligible_logs"`
	EligibleBytes int64     `json:"eligible_bytes"`
	DeletedCount  int64     `json:"deleted_count"`
	DeletedBytes  int64     `json:"deleted_bytes"`
	AuditID       string    `json:"audit_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type Runner struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	Tags            []string  `json:"tags"`
	Capabilities    []string  `json:"capabilities"`
	Status          string    `json:"status"`
	RegisteredAt    time.Time `json:"registered_at"`
	LastHeartbeatAt time.Time `json:"last_heartbeat_at"`
	TokenHash       string    `json:"token_hash"`
}

type RunnerClaimCursor struct {
	RunnerID     string     `json:"runner_id"`
	RunID        *string    `json:"run_id"`
	UpdatedAt    time.Time  `json:"updated_at"`
	ClaimOrderAt *time.Time `json:"claim_order_at"`
}

type RunnerEnrollment struct {
	ID               string     `json:"id"`
	TokenHash        string     `json:"token_hash"`
	RunnerID         string     `json:"runner_id"`
	RunnerName       string     `json:"runner_name"`
	Tags             []string   `json:"tags"`
	Capabilities     []string   `json:"capabilities"`
	CreatedBy        string     `json:"created_by"`
	CreatedAt        time.Time  `json:"created_at"`
	ExpiresAt        time.Time  `json:"expires_at"`
	RevokedAt        *time.Time `json:"revoked_at"`
	UsedAt           *time.Time `json:"used_at"`
	ConsumeRequestID *string    `json:"consume_request_id"`
	CredentialHash   *string    `json:"credential_hash"`
}

type RunnerOperationalObservation struct {
	RunnerID      string    `json:"runner_id"`
	ObservedAt    time.Time `json:"observed_at"`
	JournalDepth  int32     `json:"journal_depth"`
	RetryCount    int32     `json:"retry_count"`
	RenewFailures int32     `json:"renew_failures"`
}

type Service struct {
	ID           string    `json:"id"`
	ProjectID    string    `json:"project_id"`
	Name         string    `json:"name"`
	RepositoryID string    `json:"repository_id"`
	ComposePath  string    `json:"compose_path"`
	Profiles     []string  `json:"profiles"`
	OwnerID      string    `json:"owner_id"`
	CreatedAt    time.Time `json:"created_at"`
}

type Session struct {
	ID         string     `json:"id"`
	UserID     string     `json:"user_id"`
	TokenHash  string     `json:"token_hash"`
	ExpiresAt  time.Time  `json:"expires_at"`
	CreatedAt  time.Time  `json:"created_at"`
	SourceIp   string     `json:"source_ip"`
	UserAgent  string     `json:"user_agent"`
	LastSeenAt *time.Time `json:"last_seen_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

type TaskRun struct {
	ID            string          `json:"id"`
	ProjectID     string          `json:"project_id"`
	TemplateID    *string         `json:"template_id"`
	RunSpec       json.RawMessage `json:"run_spec"`
	Workflow      json.RawMessage `json:"workflow"`
	RunnerTags    []string        `json:"runner_tags"`
	Status        string          `json:"status"`
	RunnerID      *string         `json:"runner_id"`
	RequestedBy   string          `json:"requested_by"`
	StartedAt     time.Time       `json:"started_at"`
	FinishedAt    *time.Time      `json:"finished_at"`
	CreatedAt     time.Time       `json:"created_at"`
	WorkflowState json.RawMessage `json:"workflow_state"`
	NextAttempt   int32           `json:"next_attempt"`
	ClaimOrderAt  time.Time       `json:"claim_order_at"`
}

type TaskTemplate struct {
	ID            string          `json:"id"`
	ProjectID     string          `json:"project_id"`
	Name          string          `json:"name"`
	Kind          string          `json:"kind"`
	RunSpec       json.RawMessage `json:"run_spec"`
	Workflow      json.RawMessage `json:"workflow"`
	WorkflowState json.RawMessage `json:"workflow_state"`
	RunnerTags    []string        `json:"runner_tags"`
	RequiresAck   bool            `json:"requires_ack"`
	CreatedAt     time.Time       `json:"created_at"`
	UpdatedAt     time.Time       `json:"updated_at"`
}

type User struct {
	ID           string     `json:"id"`
	Email        string     `json:"email"`
	Name         string     `json:"name"`
	Status       string     `json:"status"`
	GlobalRole   string     `json:"global_role"`
	PasswordHash string     `json:"password_hash"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	ArchivedAt   *time.Time `json:"archived_at"`
}
