// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: oidc.sql

package sqlcgen

import (
	"context"
	"time"
)

const consumeOIDCLoginFlow = `-- name: ConsumeOIDCLoginFlow :one
DELETE FROM oidc_login_flows
WHERE state_hash = $1
  AND verifier_hash = $2
  AND issuer = $3
  AND client_id = $4
  AND expires_at > $5
RETURNING id, state_hash, nonce_hash, verifier_hash, redirect_path, issuer, client_id, expires_at, created_at
`

type ConsumeOIDCLoginFlowParams struct {
	StateHash    string    `json:"state_hash"`
	VerifierHash string    `json:"verifier_hash"`
	Issuer       string    `json:"issuer"`
	ClientID     string    `json:"client_id"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) ConsumeOIDCLoginFlow(ctx context.Context, arg ConsumeOIDCLoginFlowParams) (OidcLoginFlow, error) {
	row := q.db.QueryRow(ctx, consumeOIDCLoginFlow,
		arg.StateHash,
		arg.VerifierHash,
		arg.Issuer,
		arg.ClientID,
		arg.ExpiresAt,
	)
	var i OidcLoginFlow
	err := row.Scan(
		&i.ID,
		&i.StateHash,
		&i.NonceHash,
		&i.VerifierHash,
		&i.RedirectPath,
		&i.Issuer,
		&i.ClientID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const countActiveOIDCLoginFlows = `-- name: CountActiveOIDCLoginFlows :one
SELECT count(*) FROM oidc_login_flows WHERE expires_at > $1
`

func (q *Queries) CountActiveOIDCLoginFlows(ctx context.Context, expiresAt time.Time) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveOIDCLoginFlows, expiresAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOIDCIdentity = `-- name: CreateOIDCIdentity :exec
INSERT INTO oidc_external_identities (issuer, subject, user_id, created_at)
VALUES ($1,$2,$3,$4)
`

type CreateOIDCIdentityParams struct {
	Issuer    string    `json:"issuer"`
	Subject   string    `json:"subject"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateOIDCIdentity(ctx context.Context, arg CreateOIDCIdentityParams) error {
	_, err := q.db.Exec(ctx, createOIDCIdentity,
		arg.Issuer,
		arg.Subject,
		arg.UserID,
		arg.CreatedAt,
	)
	return err
}

const createOIDCLoginFlow = `-- name: CreateOIDCLoginFlow :exec
INSERT INTO oidc_login_flows
  (id, state_hash, nonce_hash, verifier_hash, redirect_path, issuer, client_id, expires_at, created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type CreateOIDCLoginFlowParams struct {
	ID           string    `json:"id"`
	StateHash    string    `json:"state_hash"`
	NonceHash    string    `json:"nonce_hash"`
	VerifierHash string    `json:"verifier_hash"`
	RedirectPath string    `json:"redirect_path"`
	Issuer       string    `json:"issuer"`
	ClientID     string    `json:"client_id"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateOIDCLoginFlow(ctx context.Context, arg CreateOIDCLoginFlowParams) error {
	_, err := q.db.Exec(ctx, createOIDCLoginFlow,
		arg.ID,
		arg.StateHash,
		arg.NonceHash,
		arg.VerifierHash,
		arg.RedirectPath,
		arg.Issuer,
		arg.ClientID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createOIDCUser = `-- name: CreateOIDCUser :exec
INSERT INTO users (id, email, name, status, global_role, password_hash, created_at, updated_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$7)
`

type CreateOIDCUserParams struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	Status       string    `json:"status"`
	GlobalRole   string    `json:"global_role"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) CreateOIDCUser(ctx context.Context, arg CreateOIDCUserParams) error {
	_, err := q.db.Exec(ctx, createOIDCUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Status,
		arg.GlobalRole,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredOIDCLoginFlows = `-- name: DeleteExpiredOIDCLoginFlows :execrows
DELETE FROM oidc_login_flows AS expired
WHERE expired.id IN (
  SELECT candidate.id FROM oidc_login_flows AS candidate
  WHERE candidate.expires_at <= $1
  ORDER BY candidate.expires_at, candidate.id
  LIMIT $2
)
`

type DeleteExpiredOIDCLoginFlowsParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) DeleteExpiredOIDCLoginFlows(ctx context.Context, arg DeleteExpiredOIDCLoginFlowsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredOIDCLoginFlows, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOIDCUser = `-- name: GetOIDCUser :one
SELECT users.id, users.email, users.name, users.status, users.global_role,
       users.password_hash, users.created_at, users.updated_at, users.archived_at
FROM oidc_external_identities AS identity
JOIN users ON users.id = identity.user_id
WHERE identity.issuer = $1 AND identity.subject = $2
FOR SHARE OF users
`

type GetOIDCUserParams struct {
	Issuer  string `json:"issuer"`
	Subject string `json:"subject"`
}

func (q *Queries) GetOIDCUser(ctx context.Context, arg GetOIDCUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getOIDCUser, arg.Issuer, arg.Subject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.GlobalRole,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const lockOIDCLoginFlows = `-- name: LockOIDCLoginFlows :exec
SELECT pg_advisory_xact_lock(704320031)
`

func (q *Queries) LockOIDCLoginFlows(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockOIDCLoginFlows)
	return err
}
