// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: schema.sql

package sqlcgen

import (
	"context"
)

const schedulerSchemaCompatible = `-- name: SchedulerSchemaCompatible :one
SELECT nerocd_scheduler_schema_compatible()
   AND nerocd_replay_schema_compatible()
   AND nerocd_enrollment_schema_compatible()
   AND nerocd_deployment_schema_compatible()
AND nerocd_provenance_schema_compatible()
AND nerocd_repository_policy_schema_compatible()
AND nerocd_identity_schema_compatible()
AND nerocd_oidc_schema_compatible()
AND nerocd_observability_schema_compatible()
AND nerocd_retention_schema_compatible() AS compatible
`

func (q *Queries) SchedulerSchemaCompatible(ctx context.Context) (*bool, error) {
	row := q.db.QueryRow(ctx, schedulerSchemaCompatible)
	var compatible *bool
	err := row.Scan(&compatible)
	return compatible, err
}
