// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: sources.sql

package sqlcgen

import (
	"context"
	"time"
)

const createAccessKey = `-- name: CreateAccessKey :one
INSERT INTO access_keys (id,project_id,name,kind,fingerprint,created_at)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, project_id, name, kind, fingerprint, created_at
`

type CreateAccessKeyParams struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Name        string    `json:"name"`
	Kind        string    `json:"kind"`
	Fingerprint string    `json:"fingerprint"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateAccessKey(ctx context.Context, arg CreateAccessKeyParams) (AccessKey, error) {
	row := q.db.QueryRow(ctx, createAccessKey,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Fingerprint,
		arg.CreatedAt,
	)
	var i AccessKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories (id,project_id,name,kind,source,created_at)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, project_id, name, kind, source, created_at
`

type CreateInventoryParams struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Source,
		arg.CreatedAt,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (id,project_id,name,url,provider,default_ref,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id, project_id, name, url, provider, default_ref, created_at, updated_at
`

type CreateRepositoryParams struct {
	ID         string    `json:"id"`
	ProjectID  string    `json:"project_id"`
	Name       string    `json:"name"`
	Url        string    `json:"url"`
	Provider   string    `json:"provider"`
	DefaultRef string    `json:"default_ref"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Url,
		arg.Provider,
		arg.DefaultRef,
		arg.CreatedAt,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.Provider,
		&i.DefaultRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccessKeys = `-- name: ListAccessKeys :many
SELECT id, project_id, name, kind, fingerprint, created_at FROM access_keys
WHERE ($1::text='' OR project_id=$1)
ORDER BY name
`

func (q *Queries) ListAccessKeys(ctx context.Context, projectID string) ([]AccessKey, error) {
	rows, err := q.db.Query(ctx, listAccessKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessKey{}
	for rows.Next() {
		var i AccessKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.Fingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventories = `-- name: ListInventories :many
SELECT id, project_id, name, kind, source, created_at FROM inventories
WHERE ($1::text='' OR project_id=$1)
ORDER BY name
`

func (q *Queries) ListInventories(ctx context.Context, projectID string) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, listInventories, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, project_id, name, url, provider, default_ref, created_at, updated_at FROM repositories
WHERE ($1::text='' OR project_id=$1)
ORDER BY name
`

func (q *Queries) ListRepositories(ctx context.Context, projectID string) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Url,
			&i.Provider,
			&i.DefaultRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
