// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: sources.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	"time"
)

const createAccessKey = `-- name: CreateAccessKey :one
INSERT INTO access_keys (id,project_id,name,kind,fingerprint,created_at)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, project_id, name, kind, fingerprint, created_at
`

type CreateAccessKeyParams struct {
	ID          string    `json:"id"`
	ProjectID   string    `json:"project_id"`
	Name        string    `json:"name"`
	Kind        string    `json:"kind"`
	Fingerprint string    `json:"fingerprint"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateAccessKey(ctx context.Context, arg CreateAccessKeyParams) (AccessKey, error) {
	row := q.db.QueryRow(ctx, createAccessKey,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Fingerprint,
		arg.CreatedAt,
	)
	var i AccessKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Fingerprint,
		&i.CreatedAt,
	)
	return i, err
}

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories (id,project_id,name,kind,source,created_at)
VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, project_id, name, kind, source, created_at
`

type CreateInventoryParams struct {
	ID        string    `json:"id"`
	ProjectID string    `json:"project_id"`
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	Source    string    `json:"source"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRow(ctx, createInventory,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Source,
		arg.CreatedAt,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (id,project_id,name,url,provider,default_ref,repository_policy,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id, project_id, name, url, provider, default_ref, created_at, updated_at, repository_policy
`

type CreateRepositoryParams struct {
	ID               string          `json:"id"`
	ProjectID        string          `json:"project_id"`
	Name             string          `json:"name"`
	Url              string          `json:"url"`
	Provider         string          `json:"provider"`
	DefaultRef       string          `json:"default_ref"`
	RepositoryPolicy json.RawMessage `json:"repository_policy"`
	CreatedAt        time.Time       `json:"created_at"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Url,
		arg.Provider,
		arg.DefaultRef,
		arg.RepositoryPolicy,
		arg.CreatedAt,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.Provider,
		&i.DefaultRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPolicy,
	)
	return i, err
}

const createRepositoryPolicyConfigurationReceipt = `-- name: CreateRepositoryPolicyConfigurationReceipt :exec
INSERT INTO repository_policy_configuration_receipts (repository_id, configuration_id, actor_id, policy_sha256, audit_id, created_at)
VALUES ($1,$2,$3,$4,$5,clock_timestamp())
`

type CreateRepositoryPolicyConfigurationReceiptParams struct {
	RepositoryID    string `json:"repository_id"`
	ConfigurationID string `json:"configuration_id"`
	ActorID         string `json:"actor_id"`
	PolicySha256    string `json:"policy_sha256"`
	AuditID         string `json:"audit_id"`
}

func (q *Queries) CreateRepositoryPolicyConfigurationReceipt(ctx context.Context, arg CreateRepositoryPolicyConfigurationReceiptParams) error {
	_, err := q.db.Exec(ctx, createRepositoryPolicyConfigurationReceipt,
		arg.RepositoryID,
		arg.ConfigurationID,
		arg.ActorID,
		arg.PolicySha256,
		arg.AuditID,
	)
	return err
}

const getRepositoryPolicyConfigurationReceipt = `-- name: GetRepositoryPolicyConfigurationReceipt :one
SELECT repository_id, configuration_id, actor_id, policy_sha256, audit_id, created_at
FROM repository_policy_configuration_receipts
WHERE repository_id=$1 AND configuration_id=$2
`

type GetRepositoryPolicyConfigurationReceiptParams struct {
	RepositoryID    string `json:"repository_id"`
	ConfigurationID string `json:"configuration_id"`
}

func (q *Queries) GetRepositoryPolicyConfigurationReceipt(ctx context.Context, arg GetRepositoryPolicyConfigurationReceiptParams) (RepositoryPolicyConfigurationReceipt, error) {
	row := q.db.QueryRow(ctx, getRepositoryPolicyConfigurationReceipt, arg.RepositoryID, arg.ConfigurationID)
	var i RepositoryPolicyConfigurationReceipt
	err := row.Scan(
		&i.RepositoryID,
		&i.ConfigurationID,
		&i.ActorID,
		&i.PolicySha256,
		&i.AuditID,
		&i.CreatedAt,
	)
	return i, err
}

const listAccessKeys = `-- name: ListAccessKeys :many
SELECT id, project_id, name, kind, fingerprint, created_at FROM access_keys
WHERE ($1::text='' OR project_id=$1)
ORDER BY name
`

func (q *Queries) ListAccessKeys(ctx context.Context, projectID string) ([]AccessKey, error) {
	rows, err := q.db.Query(ctx, listAccessKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessKey{}
	for rows.Next() {
		var i AccessKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.Fingerprint,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventories = `-- name: ListInventories :many
SELECT id, project_id, name, kind, source, created_at FROM inventories
WHERE ($1::text='' OR project_id=$1)
ORDER BY name
`

func (q *Queries) ListInventories(ctx context.Context, projectID string) ([]Inventory, error) {
	rows, err := q.db.Query(ctx, listInventories, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Inventory{}
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, project_id, name, url, provider, default_ref, created_at, updated_at, repository_policy FROM repositories
WHERE ($1::text='' OR project_id=$1)
ORDER BY name
`

func (q *Queries) ListRepositories(ctx context.Context, projectID string) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositories, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Url,
			&i.Provider,
			&i.DefaultRef,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepositoryPolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRepositoryForPolicyConfiguration = `-- name: LockRepositoryForPolicyConfiguration :one
SELECT id, project_id, name, url, provider, default_ref, created_at, updated_at, repository_policy FROM repositories WHERE id=$1 AND project_id=$2 FOR UPDATE
`

type LockRepositoryForPolicyConfigurationParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) LockRepositoryForPolicyConfiguration(ctx context.Context, arg LockRepositoryForPolicyConfigurationParams) (Repository, error) {
	row := q.db.QueryRow(ctx, lockRepositoryForPolicyConfiguration, arg.ID, arg.ProjectID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Url,
		&i.Provider,
		&i.DefaultRef,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepositoryPolicy,
	)
	return i, err
}

const repositoryPolicyActorAuthorized = `-- name: RepositoryPolicyActorAuthorized :one
SELECT EXISTS (
  SELECT 1 FROM users WHERE users.id=$2 AND users.global_role='system_admin'
  UNION ALL
  SELECT 1 FROM project_members WHERE project_id=$1 AND user_id=$2 AND role IN ('owner','maintainer')
)
`

type RepositoryPolicyActorAuthorizedParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) RepositoryPolicyActorAuthorized(ctx context.Context, arg RepositoryPolicyActorAuthorizedParams) (bool, error) {
	row := q.db.QueryRow(ctx, repositoryPolicyActorAuthorized, arg.ProjectID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const setRepositoryPolicyConfiguration = `-- name: SetRepositoryPolicyConfiguration :exec
UPDATE repositories SET repository_policy=$2, updated_at=clock_timestamp()
WHERE id=$1 AND repository_policy->>'state'='legacy_unverified'
`

type SetRepositoryPolicyConfigurationParams struct {
	ID               string          `json:"id"`
	RepositoryPolicy json.RawMessage `json:"repository_policy"`
}

func (q *Queries) SetRepositoryPolicyConfiguration(ctx context.Context, arg SetRepositoryPolicyConfigurationParams) error {
	_, err := q.db.Exec(ctx, setRepositoryPolicyConfiguration, arg.ID, arg.RepositoryPolicy)
	return err
}
