// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var AuditEventErrors = &auditEventErrors{
	ErrUniqueAuditEventsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "audit_events",
		columns: []string{"id"},
		s:       "audit_events_pkey",
	},
}

type auditEventErrors struct {
	ErrUniqueAuditEventsPkey *UniqueConstraintError
}
