// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var RepositoryErrors = &repositoryErrors{
	ErrUniqueRepositoriesPkey: &UniqueConstraintError{
		schema:  "",
		table:   "repositories",
		columns: []string{"id"},
		s:       "repositories_pkey",
	},
}

type repositoryErrors struct {
	ErrUniqueRepositoriesPkey *UniqueConstraintError
}
