// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var SessionErrors = &sessionErrors{
	ErrUniqueSessionsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "sessions",
		columns: []string{"id"},
		s:       "sessions_pkey",
	},

	ErrUniqueSessionsTokenHashKey: &UniqueConstraintError{
		schema:  "",
		table:   "sessions",
		columns: []string{"token_hash"},
		s:       "sessions_token_hash_key",
	},
}

type sessionErrors struct {
	ErrUniqueSessionsPkey *UniqueConstraintError

	ErrUniqueSessionsTokenHashKey *UniqueConstraintError
}
