// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"testing"
)

// Test that Project has a C field with count pointers for to-many relationships
func TestProjectCountStruct(t *testing.T) {
	var m Project
	_ = m.C // Verify C field exists

	// Verify AccessKeys count field exists and is *int64
	var _ *int64 = m.C.AccessKeys

	// Verify Inventories count field exists and is *int64
	var _ *int64 = m.C.Inventories

	// Verify ProjectMembers count field exists and is *int64
	var _ *int64 = m.C.ProjectMembers

	// Verify Repositories count field exists and is *int64
	var _ *int64 = m.C.Repositories

	// Verify TaskRuns count field exists and is *int64
	var _ *int64 = m.C.TaskRuns

	// Verify TaskTemplates count field exists and is *int64
	var _ *int64 = m.C.TaskTemplates
}

// Test that Project has LoadCount methods for to-many relationships
func TestProjectLoadCountMethods(t *testing.T) {
	var m *Project
	var ms ProjectSlice
	ctx := context.Background()

	// Verify LoadCountAccessKeys method exists on single model
	_ = m.LoadCountAccessKeys(ctx, nil)

	// Verify LoadCountAccessKeys method exists on slice
	_ = ms.LoadCountAccessKeys(ctx, nil)

	// Verify LoadCountInventories method exists on single model
	_ = m.LoadCountInventories(ctx, nil)

	// Verify LoadCountInventories method exists on slice
	_ = ms.LoadCountInventories(ctx, nil)

	// Verify LoadCountProjectMembers method exists on single model
	_ = m.LoadCountProjectMembers(ctx, nil)

	// Verify LoadCountProjectMembers method exists on slice
	_ = ms.LoadCountProjectMembers(ctx, nil)

	// Verify LoadCountRepositories method exists on single model
	_ = m.LoadCountRepositories(ctx, nil)

	// Verify LoadCountRepositories method exists on slice
	_ = ms.LoadCountRepositories(ctx, nil)

	// Verify LoadCountTaskRuns method exists on single model
	_ = m.LoadCountTaskRuns(ctx, nil)

	// Verify LoadCountTaskRuns method exists on slice
	_ = ms.LoadCountTaskRuns(ctx, nil)

	// Verify LoadCountTaskTemplates method exists on single model
	_ = m.LoadCountTaskTemplates(ctx, nil)

	// Verify LoadCountTaskTemplates method exists on slice
	_ = ms.LoadCountTaskTemplates(ctx, nil)
}

// Test that SelectThenLoadCount has Project with methods for to-many relationships
func TestSelectThenLoadCountProject(t *testing.T) {
	_ = SelectThenLoadCount.Project

	// Verify AccessKeys loader exists
	_ = SelectThenLoadCount.Project.AccessKeys

	// Verify Inventories loader exists
	_ = SelectThenLoadCount.Project.Inventories

	// Verify ProjectMembers loader exists
	_ = SelectThenLoadCount.Project.ProjectMembers

	// Verify Repositories loader exists
	_ = SelectThenLoadCount.Project.Repositories

	// Verify TaskRuns loader exists
	_ = SelectThenLoadCount.Project.TaskRuns

	// Verify TaskTemplates loader exists
	_ = SelectThenLoadCount.Project.TaskTemplates
}

// Test that PreloadCount has Project with methods for to-many relationships
func TestPreloadCountProject(t *testing.T) {
	_ = PreloadCount.Project

	// Verify AccessKeys preloader exists and returns a Preloader
	_ = PreloadCount.Project.AccessKeys()

	// Verify Inventories preloader exists and returns a Preloader
	_ = PreloadCount.Project.Inventories()

	// Verify ProjectMembers preloader exists and returns a Preloader
	_ = PreloadCount.Project.ProjectMembers()

	// Verify Repositories preloader exists and returns a Preloader
	_ = PreloadCount.Project.Repositories()

	// Verify TaskRuns preloader exists and returns a Preloader
	_ = PreloadCount.Project.TaskRuns()

	// Verify TaskTemplates preloader exists and returns a Preloader
	_ = PreloadCount.Project.TaskTemplates()
}

// Test that Project has PreloadCount method
func TestProjectPreloadCountMethod(t *testing.T) {
	var m *Project

	_ = m.PreloadCount("AccessKeys", 0)

	_ = m.PreloadCount("Inventories", 0)

	_ = m.PreloadCount("ProjectMembers", 0)

	_ = m.PreloadCount("Repositories", 0)

	_ = m.PreloadCount("TaskRuns", 0)

	_ = m.PreloadCount("TaskTemplates", 0)
}

// Test that RunLease has a C field with count pointers for to-many relationships
func TestRunLeaseCountStruct(t *testing.T) {
	var m RunLease
	_ = m.C // Verify C field exists

	// Verify LeaseRunArtifacts count field exists and is *int64
	var _ *int64 = m.C.LeaseRunArtifacts
}

// Test that RunLease has LoadCount methods for to-many relationships
func TestRunLeaseLoadCountMethods(t *testing.T) {
	var m *RunLease
	var ms RunLeaseSlice
	ctx := context.Background()

	// Verify LoadCountLeaseRunArtifacts method exists on single model
	_ = m.LoadCountLeaseRunArtifacts(ctx, nil)

	// Verify LoadCountLeaseRunArtifacts method exists on slice
	_ = ms.LoadCountLeaseRunArtifacts(ctx, nil)
}

// Test that SelectThenLoadCount has RunLease with methods for to-many relationships
func TestSelectThenLoadCountRunLease(t *testing.T) {
	_ = SelectThenLoadCount.RunLease

	// Verify LeaseRunArtifacts loader exists
	_ = SelectThenLoadCount.RunLease.LeaseRunArtifacts
}

// Test that PreloadCount has RunLease with methods for to-many relationships
func TestPreloadCountRunLease(t *testing.T) {
	_ = PreloadCount.RunLease

	// Verify LeaseRunArtifacts preloader exists and returns a Preloader
	_ = PreloadCount.RunLease.LeaseRunArtifacts()
}

// Test that RunLease has PreloadCount method
func TestRunLeasePreloadCountMethod(t *testing.T) {
	var m *RunLease

	_ = m.PreloadCount("LeaseRunArtifacts", 0)
}

// Test that Runner has a C field with count pointers for to-many relationships
func TestRunnerCountStruct(t *testing.T) {
	var m Runner
	_ = m.C // Verify C field exists

	// Verify RunLeases count field exists and is *int64
	var _ *int64 = m.C.RunLeases
}

// Test that Runner has LoadCount methods for to-many relationships
func TestRunnerLoadCountMethods(t *testing.T) {
	var m *Runner
	var ms RunnerSlice
	ctx := context.Background()

	// Verify LoadCountRunLeases method exists on single model
	_ = m.LoadCountRunLeases(ctx, nil)

	// Verify LoadCountRunLeases method exists on slice
	_ = ms.LoadCountRunLeases(ctx, nil)
}

// Test that SelectThenLoadCount has Runner with methods for to-many relationships
func TestSelectThenLoadCountRunner(t *testing.T) {
	_ = SelectThenLoadCount.Runner

	// Verify RunLeases loader exists
	_ = SelectThenLoadCount.Runner.RunLeases
}

// Test that PreloadCount has Runner with methods for to-many relationships
func TestPreloadCountRunner(t *testing.T) {
	_ = PreloadCount.Runner

	// Verify RunLeases preloader exists and returns a Preloader
	_ = PreloadCount.Runner.RunLeases()
}

// Test that Runner has PreloadCount method
func TestRunnerPreloadCountMethod(t *testing.T) {
	var m *Runner

	_ = m.PreloadCount("RunLeases", 0)
}

// Test that TaskRun has a C field with count pointers for to-many relationships
func TestTaskRunCountStruct(t *testing.T) {
	var m TaskRun
	_ = m.C // Verify C field exists

	// Verify RunRunArtifacts count field exists and is *int64
	var _ *int64 = m.C.RunRunArtifacts

	// Verify RunRunLeases count field exists and is *int64
	var _ *int64 = m.C.RunRunLeases

	// Verify RunRunLogs count field exists and is *int64
	var _ *int64 = m.C.RunRunLogs
}

// Test that TaskRun has LoadCount methods for to-many relationships
func TestTaskRunLoadCountMethods(t *testing.T) {
	var m *TaskRun
	var ms TaskRunSlice
	ctx := context.Background()

	// Verify LoadCountRunRunArtifacts method exists on single model
	_ = m.LoadCountRunRunArtifacts(ctx, nil)

	// Verify LoadCountRunRunArtifacts method exists on slice
	_ = ms.LoadCountRunRunArtifacts(ctx, nil)

	// Verify LoadCountRunRunLeases method exists on single model
	_ = m.LoadCountRunRunLeases(ctx, nil)

	// Verify LoadCountRunRunLeases method exists on slice
	_ = ms.LoadCountRunRunLeases(ctx, nil)

	// Verify LoadCountRunRunLogs method exists on single model
	_ = m.LoadCountRunRunLogs(ctx, nil)

	// Verify LoadCountRunRunLogs method exists on slice
	_ = ms.LoadCountRunRunLogs(ctx, nil)
}

// Test that SelectThenLoadCount has TaskRun with methods for to-many relationships
func TestSelectThenLoadCountTaskRun(t *testing.T) {
	_ = SelectThenLoadCount.TaskRun

	// Verify RunRunArtifacts loader exists
	_ = SelectThenLoadCount.TaskRun.RunRunArtifacts

	// Verify RunRunLeases loader exists
	_ = SelectThenLoadCount.TaskRun.RunRunLeases

	// Verify RunRunLogs loader exists
	_ = SelectThenLoadCount.TaskRun.RunRunLogs
}

// Test that PreloadCount has TaskRun with methods for to-many relationships
func TestPreloadCountTaskRun(t *testing.T) {
	_ = PreloadCount.TaskRun

	// Verify RunRunArtifacts preloader exists and returns a Preloader
	_ = PreloadCount.TaskRun.RunRunArtifacts()

	// Verify RunRunLeases preloader exists and returns a Preloader
	_ = PreloadCount.TaskRun.RunRunLeases()

	// Verify RunRunLogs preloader exists and returns a Preloader
	_ = PreloadCount.TaskRun.RunRunLogs()
}

// Test that TaskRun has PreloadCount method
func TestTaskRunPreloadCountMethod(t *testing.T) {
	var m *TaskRun

	_ = m.PreloadCount("RunRunArtifacts", 0)

	_ = m.PreloadCount("RunRunLeases", 0)

	_ = m.PreloadCount("RunRunLogs", 0)
}

// Test that TaskTemplate has a C field with count pointers for to-many relationships
func TestTaskTemplateCountStruct(t *testing.T) {
	var m TaskTemplate
	_ = m.C // Verify C field exists

	// Verify TemplateTaskRuns count field exists and is *int64
	var _ *int64 = m.C.TemplateTaskRuns
}

// Test that TaskTemplate has LoadCount methods for to-many relationships
func TestTaskTemplateLoadCountMethods(t *testing.T) {
	var m *TaskTemplate
	var ms TaskTemplateSlice
	ctx := context.Background()

	// Verify LoadCountTemplateTaskRuns method exists on single model
	_ = m.LoadCountTemplateTaskRuns(ctx, nil)

	// Verify LoadCountTemplateTaskRuns method exists on slice
	_ = ms.LoadCountTemplateTaskRuns(ctx, nil)
}

// Test that SelectThenLoadCount has TaskTemplate with methods for to-many relationships
func TestSelectThenLoadCountTaskTemplate(t *testing.T) {
	_ = SelectThenLoadCount.TaskTemplate

	// Verify TemplateTaskRuns loader exists
	_ = SelectThenLoadCount.TaskTemplate.TemplateTaskRuns
}

// Test that PreloadCount has TaskTemplate with methods for to-many relationships
func TestPreloadCountTaskTemplate(t *testing.T) {
	_ = PreloadCount.TaskTemplate

	// Verify TemplateTaskRuns preloader exists and returns a Preloader
	_ = PreloadCount.TaskTemplate.TemplateTaskRuns()
}

// Test that TaskTemplate has PreloadCount method
func TestTaskTemplatePreloadCountMethod(t *testing.T) {
	var m *TaskTemplate

	_ = m.PreloadCount("TemplateTaskRuns", 0)
}

// Test that User has a C field with count pointers for to-many relationships
func TestUserCountStruct(t *testing.T) {
	var m User
	_ = m.C // Verify C field exists

	// Verify CreatedByAPITokens count field exists and is *int64
	var _ *int64 = m.C.CreatedByAPITokens

	// Verify ApprovedByApprovals count field exists and is *int64
	var _ *int64 = m.C.ApprovedByApprovals

	// Verify RequestedByApprovals count field exists and is *int64
	var _ *int64 = m.C.RequestedByApprovals

	// Verify ProjectMembers count field exists and is *int64
	var _ *int64 = m.C.ProjectMembers

	// Verify Sessions count field exists and is *int64
	var _ *int64 = m.C.Sessions

	// Verify RequestedByTaskRuns count field exists and is *int64
	var _ *int64 = m.C.RequestedByTaskRuns
}

// Test that User has LoadCount methods for to-many relationships
func TestUserLoadCountMethods(t *testing.T) {
	var m *User
	var ms UserSlice
	ctx := context.Background()

	// Verify LoadCountCreatedByAPITokens method exists on single model
	_ = m.LoadCountCreatedByAPITokens(ctx, nil)

	// Verify LoadCountCreatedByAPITokens method exists on slice
	_ = ms.LoadCountCreatedByAPITokens(ctx, nil)

	// Verify LoadCountApprovedByApprovals method exists on single model
	_ = m.LoadCountApprovedByApprovals(ctx, nil)

	// Verify LoadCountApprovedByApprovals method exists on slice
	_ = ms.LoadCountApprovedByApprovals(ctx, nil)

	// Verify LoadCountRequestedByApprovals method exists on single model
	_ = m.LoadCountRequestedByApprovals(ctx, nil)

	// Verify LoadCountRequestedByApprovals method exists on slice
	_ = ms.LoadCountRequestedByApprovals(ctx, nil)

	// Verify LoadCountProjectMembers method exists on single model
	_ = m.LoadCountProjectMembers(ctx, nil)

	// Verify LoadCountProjectMembers method exists on slice
	_ = ms.LoadCountProjectMembers(ctx, nil)

	// Verify LoadCountSessions method exists on single model
	_ = m.LoadCountSessions(ctx, nil)

	// Verify LoadCountSessions method exists on slice
	_ = ms.LoadCountSessions(ctx, nil)

	// Verify LoadCountRequestedByTaskRuns method exists on single model
	_ = m.LoadCountRequestedByTaskRuns(ctx, nil)

	// Verify LoadCountRequestedByTaskRuns method exists on slice
	_ = ms.LoadCountRequestedByTaskRuns(ctx, nil)
}

// Test that SelectThenLoadCount has User with methods for to-many relationships
func TestSelectThenLoadCountUser(t *testing.T) {
	_ = SelectThenLoadCount.User

	// Verify CreatedByAPITokens loader exists
	_ = SelectThenLoadCount.User.CreatedByAPITokens

	// Verify ApprovedByApprovals loader exists
	_ = SelectThenLoadCount.User.ApprovedByApprovals

	// Verify RequestedByApprovals loader exists
	_ = SelectThenLoadCount.User.RequestedByApprovals

	// Verify ProjectMembers loader exists
	_ = SelectThenLoadCount.User.ProjectMembers

	// Verify Sessions loader exists
	_ = SelectThenLoadCount.User.Sessions

	// Verify RequestedByTaskRuns loader exists
	_ = SelectThenLoadCount.User.RequestedByTaskRuns
}

// Test that PreloadCount has User with methods for to-many relationships
func TestPreloadCountUser(t *testing.T) {
	_ = PreloadCount.User

	// Verify CreatedByAPITokens preloader exists and returns a Preloader
	_ = PreloadCount.User.CreatedByAPITokens()

	// Verify ApprovedByApprovals preloader exists and returns a Preloader
	_ = PreloadCount.User.ApprovedByApprovals()

	// Verify RequestedByApprovals preloader exists and returns a Preloader
	_ = PreloadCount.User.RequestedByApprovals()

	// Verify ProjectMembers preloader exists and returns a Preloader
	_ = PreloadCount.User.ProjectMembers()

	// Verify Sessions preloader exists and returns a Preloader
	_ = PreloadCount.User.Sessions()

	// Verify RequestedByTaskRuns preloader exists and returns a Preloader
	_ = PreloadCount.User.RequestedByTaskRuns()
}

// Test that User has PreloadCount method
func TestUserPreloadCountMethod(t *testing.T) {
	var m *User

	_ = m.PreloadCount("CreatedByAPITokens", 0)

	_ = m.PreloadCount("ApprovedByApprovals", 0)

	_ = m.PreloadCount("RequestedByApprovals", 0)

	_ = m.PreloadCount("ProjectMembers", 0)

	_ = m.PreloadCount("Sessions", 0)

	_ = m.PreloadCount("RequestedByTaskRuns", 0)
}
