// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"

	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor[bob.Tx]

// Make sure the type AccessKey runs hooks after queries
var _ bob.HookableType = &AccessKey{}

// Make sure the type APIToken runs hooks after queries
var _ bob.HookableType = &APIToken{}

// Make sure the type Approval runs hooks after queries
var _ bob.HookableType = &Approval{}

// Make sure the type AuditEvent runs hooks after queries
var _ bob.HookableType = &AuditEvent{}

// Make sure the type Inventory runs hooks after queries
var _ bob.HookableType = &Inventory{}

// Make sure the type ProjectMember runs hooks after queries
var _ bob.HookableType = &ProjectMember{}

// Make sure the type Project runs hooks after queries
var _ bob.HookableType = &Project{}

// Make sure the type Repository runs hooks after queries
var _ bob.HookableType = &Repository{}

// Make sure the type RunArtifact runs hooks after queries
var _ bob.HookableType = &RunArtifact{}

// Make sure the type RunLease runs hooks after queries
var _ bob.HookableType = &RunLease{}

// Make sure the type RunLog runs hooks after queries
var _ bob.HookableType = &RunLog{}

// Make sure the type Runner runs hooks after queries
var _ bob.HookableType = &Runner{}

// Make sure the type Session runs hooks after queries
var _ bob.HookableType = &Session{}

// Make sure the type TaskRun runs hooks after queries
var _ bob.HookableType = &TaskRun{}

// Make sure the type TaskTemplate runs hooks after queries
var _ bob.HookableType = &TaskTemplate{}

// Make sure the type User runs hooks after queries
var _ bob.HookableType = &User{}

// Make sure the type pq.StringArray satisfies database/sql.Scanner
var _ sql.Scanner = (*pq.StringArray)(nil)

// Make sure the type pq.StringArray satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(pq.StringArray)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql.Scanner
var _ sql.Scanner = (*types.JSON[json.RawMessage])(nil)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.JSON[json.RawMessage])
