// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Inventory is an object representing the database table.
type Inventory struct {
	ID        string    `db:"id,pk" json:"id"`
	ProjectID string    `db:"project_id" json:"project_id"`
	Name      string    `db:"name" json:"name"`
	Kind      string    `db:"kind" json:"kind"`
	Source    string    `db:"source" json:"source"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`

	R inventoryR `db:"-" json:"-"`
}

// InventorySlice is an alias for a slice of pointers to Inventory.
// This should almost always be used instead of []*Inventory.
type InventorySlice []*Inventory

// Inventories contains methods to work with the inventories table
var Inventories = psql.NewTablex[*Inventory, InventorySlice, *InventorySetter]("", "inventories", buildInventoryColumns("inventories"))

// InventoriesQuery is a query on the inventories table
type InventoriesQuery = *psql.ViewQuery[*Inventory, InventorySlice]

// inventoryR is where relationships are stored.
type inventoryR struct {
	Project *Project `json:"Project"` // inventories.inventories_project_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded inventoryRLoaded `db:"-" json:"-"`
}

// inventoryRLoaded tracks which relationships on Inventory have been loaded.
type inventoryRLoaded struct {
	Project bool `json:"Project"` // inventories.inventories_project_id_fkey
}

func buildInventoryColumns(tableName string) inventoryColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "project_id", "name", "kind", "source", "created_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return inventoryColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildInventoryColumn(tableName, "id"),
		ProjectID:   buildInventoryColumn(tableName, "project_id"),
		Name:        buildInventoryColumn(tableName, "name"),
		Kind:        buildInventoryColumn(tableName, "kind"),
		Source:      buildInventoryColumn(tableName, "source"),
		CreatedAt:   buildInventoryColumn(tableName, "created_at"),
	}
}

type inventoryColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         inventoryColumn
	ProjectID  inventoryColumn
	Name       inventoryColumn
	Kind       inventoryColumn
	Source     inventoryColumn
	CreatedAt  inventoryColumn
}

// Alias returns the current table alias for the columns set.
func (c inventoryColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (inventoryColumns) AliasedAs(tableName string) inventoryColumns {
	return buildInventoryColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c inventoryColumns) Unqualified() inventoryColumns {
	return buildInventoryColumns("")
}

func buildInventoryColumn(alias, name string) inventoryColumn {
	return inventoryColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type inventoryColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c inventoryColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c inventoryColumn) ShouldOmitParens() bool {
	return true
}

// InventorySetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type InventorySetter struct {
	ID        *string    `db:"id,pk" json:"id"`
	ProjectID *string    `db:"project_id" json:"project_id"`
	Name      *string    `db:"name" json:"name"`
	Kind      *string    `db:"kind" json:"kind"`
	Source    *string    `db:"source" json:"source"`
	CreatedAt *time.Time `db:"created_at" json:"created_at"`
}

func (s InventorySetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.ProjectID != nil {
		vals = append(vals, "project_id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.Kind != nil {
		vals = append(vals, "kind")
	}
	if s.Source != nil {
		vals = append(vals, "source")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	return vals
}

func (s InventorySetter) Overwrite(t *Inventory) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.ProjectID != nil {
		t.ProjectID = func() string {
			if s.ProjectID == nil {
				return *new(string)
			}
			return *s.ProjectID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.Kind != nil {
		t.Kind = func() string {
			if s.Kind == nil {
				return *new(string)
			}
			return *s.Kind
		}()
	}
	if s.Source != nil {
		t.Source = func() string {
			if s.Source == nil {
				return *new(string)
			}
			return *s.Source
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
}

func (s *InventorySetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Inventories.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID != nil {
			vals[0] = psql.Arg(func() string {
				if s.ID == nil {
					return *new(string)
				}
				return *s.ID
			}())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.ProjectID != nil {
			vals[1] = psql.Arg(func() string {
				if s.ProjectID == nil {
					return *new(string)
				}
				return *s.ProjectID
			}())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name != nil {
			vals[2] = psql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Kind != nil {
			vals[3] = psql.Arg(func() string {
				if s.Kind == nil {
					return *new(string)
				}
				return *s.Kind
			}())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Source != nil {
			vals[4] = psql.Arg(func() string {
				if s.Source == nil {
					return *new(string)
				}
				return *s.Source
			}())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[5] = psql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s InventorySetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s InventorySetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.ProjectID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "project_id")...),
			psql.Arg(s.ProjectID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Kind != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "kind")...),
			psql.Arg(s.Kind),
		}})
	}

	if s.Source != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "source")...),
			psql.Arg(s.Source),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	return exprs
}

// FindInventory retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindInventory(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Inventory, error) {
	if len(cols) == 0 {
		return Inventories.Query(
			sm.Where(Inventories.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Inventories.Query(
		sm.Where(Inventories.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Inventories.Columns.Only(cols...)),
	).One(ctx, exec)
}

// InventoryExists checks the presence of a single record by primary key
func InventoryExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Inventories.Query(
		sm.Where(Inventories.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Inventory is retrieved from the database
func (o *Inventory) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Inventories.AfterSelectHooks.RunHooks(ctx, exec, InventorySlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Inventories.AfterInsertHooks.RunHooks(ctx, exec, InventorySlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Inventories.AfterUpdateHooks.RunHooks(ctx, exec, InventorySlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Inventories.AfterDeleteHooks.RunHooks(ctx, exec, InventorySlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Inventories.AfterMergeHooks.RunHooks(ctx, exec, InventorySlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Inventory
func (o *Inventory) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Inventory) pkEQ() dialect.Expression {
	return psql.Quote("inventories", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Inventory
func (o *Inventory) Update(ctx context.Context, exec bob.Executor, s *InventorySetter) error {
	v, err := Inventories.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Inventory record with an executor
func (o *Inventory) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Inventories.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Inventory using the executor
func (o *Inventory) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Inventories.Query(
		sm.Where(Inventories.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after InventorySlice is retrieved from the database
func (o InventorySlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Inventories.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Inventories.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Inventories.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Inventories.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Inventories.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o InventorySlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("inventories", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o InventorySlice) copyMatchingRows(from ...*Inventory) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o InventorySlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Inventories.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Inventory:
				o.copyMatchingRows(retrieved)
			case []*Inventory:
				o.copyMatchingRows(retrieved...)
			case InventorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Inventory or a slice of Inventory
				// then run the AfterUpdateHooks on the slice
				_, err = Inventories.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o InventorySlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Inventories.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Inventory:
				o.copyMatchingRows(retrieved)
			case []*Inventory:
				o.copyMatchingRows(retrieved...)
			case InventorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Inventory or a slice of Inventory
				// then run the AfterDeleteHooks on the slice
				_, err = Inventories.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o InventorySlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Inventories.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Inventory:
				o.copyMatchingRows(retrieved)
			case []*Inventory:
				o.copyMatchingRows(retrieved...)
			case InventorySlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Inventory or a slice of Inventory
				// then run the AfterMergeHooks on the slice
				_, err = Inventories.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o InventorySlice) UpdateAll(ctx context.Context, exec bob.Executor, vals InventorySetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Inventories.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o InventorySlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Inventories.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o InventorySlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Inventories.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Project starts a query for related objects on projects
func (o *Inventory) Project(mods ...bob.Mod[*dialect.SelectQuery]) ProjectsQuery {
	return Projects.Query(append(mods,
		sm.Where(Projects.Columns.ID.EQ(psql.Arg(o.ProjectID))),
	)...)
}

func (os InventorySlice) Project(mods ...bob.Mod[*dialect.SelectQuery]) ProjectsQuery {
	pkProjectID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkProjectID = append(pkProjectID, o.ProjectID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkProjectID), "text[]")),
	))

	return Projects.Query(append(mods,
		sm.Where(psql.Group(Projects.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func attachInventoryProject0(ctx context.Context, exec bob.Executor, count int, inventory0 *Inventory, project1 *Project) (*Inventory, error) {
	setter := &InventorySetter{
		ProjectID: func() *string { return &project1.ID }(),
	}

	err := inventory0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachInventoryProject0: %w", err)
	}

	return inventory0, nil
}

func (inventory0 *Inventory) InsertProject(ctx context.Context, exec bob.Executor, related *ProjectSetter) error {
	var err error

	project1, err := Projects.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachInventoryProject0(ctx, exec, 1, inventory0, project1)
	if err != nil {
		return err
	}

	inventory0.R.Project = project1
	inventory0.R.Loaded.Project = true

	return nil
}

func (inventory0 *Inventory) AttachProject(ctx context.Context, exec bob.Executor, project1 *Project) error {
	var err error

	_, err = attachInventoryProject0(ctx, exec, 1, inventory0, project1)
	if err != nil {
		return err
	}

	inventory0.R.Project = project1
	inventory0.R.Loaded.Project = true

	return nil
}

type inventoryWhere[Q psql.Filterable] struct {
	ID        psql.WhereMod[Q, string]
	ProjectID psql.WhereMod[Q, string]
	Name      psql.WhereMod[Q, string]
	Kind      psql.WhereMod[Q, string]
	Source    psql.WhereMod[Q, string]
	CreatedAt psql.WhereMod[Q, time.Time]
}

func (inventoryWhere[Q]) AliasedAs(alias string) inventoryWhere[Q] {
	return buildInventoryWhere[Q](buildInventoryColumns(alias))
}

func buildInventoryWhere[Q psql.Filterable](cols inventoryColumns) inventoryWhere[Q] {
	return inventoryWhere[Q]{
		ID:        psql.Where[Q, string](cols.ID.Expression),
		ProjectID: psql.Where[Q, string](cols.ProjectID.Expression),
		Name:      psql.Where[Q, string](cols.Name.Expression),
		Kind:      psql.Where[Q, string](cols.Kind.Expression),
		Source:    psql.Where[Q, string](cols.Source.Expression),
		CreatedAt: psql.Where[Q, time.Time](cols.CreatedAt.Expression),
	}
}

func (o *Inventory) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Project":
		rel, ok := retrieved.(*Project)
		if !ok {
			return fmt.Errorf("inventory cannot load %T as %q", retrieved, name)
		}

		o.R.Project = rel
		o.R.Loaded.Project = true

		return nil
	default:
		return fmt.Errorf("inventory has no relationship %q", name)
	}
}

type inventoryPreloader struct {
	Project func(...psql.PreloadOption) psql.Preloader
}

func buildInventoryPreloader() inventoryPreloader {
	return inventoryPreloader{
		Project: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Project, ProjectSlice](psql.PreloadRel{
				Name: "Project",
				Sides: []psql.PreloadSide{
					{
						From:        Inventories,
						To:          Projects,
						FromColumns: []string{"project_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Projects.Columns.Names(), opts...)
		},
	}
}

type inventoryThenLoader[Q orm.Loadable] struct {
	Project func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildInventoryThenLoader[Q orm.Loadable]() inventoryThenLoader[Q] {
	type ProjectLoadInterface interface {
		LoadProject(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return inventoryThenLoader[Q]{
		Project: thenLoadBuilder[Q](
			"Project",
			func(ctx context.Context, exec bob.Executor, retrieved ProjectLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadProject(ctx, exec, mods...)
			},
		),
	}
}

// LoadProject loads the inventory's Project into the .R struct
func (o *Inventory) LoadProject(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Project = nil
	o.R.Loaded.Project = false

	related, err := o.Project(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.Project = related
	o.R.Loaded.Project = true
	return nil
}

// LoadProject loads the inventory's Project into the .R struct
func (os InventorySlice) LoadProject(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	projects, err := os.Project(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Project = nil
		o.R.Loaded.Project = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range projects {

			if !(o.ProjectID == rel.ID) {
				continue
			}

			o.R.Project = rel
			break
		}
	}

	return nil
}

type inventoryJoins[Q dialect.Joinable] struct {
	typ     string
	Project modAs[Q, projectColumns]
}

func (j inventoryJoins[Q]) aliasedAs(alias string) inventoryJoins[Q] {
	return buildInventoryJoins[Q](buildInventoryColumns(alias), j.typ)
}

func buildInventoryJoins[Q dialect.Joinable](cols inventoryColumns, typ string) inventoryJoins[Q] {
	return inventoryJoins[Q]{
		typ: typ,
		Project: modAs[Q, projectColumns]{
			c: Projects.Columns,
			f: func(to projectColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Projects.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.ProjectID),
					))
				}

				return mods
			},
		},
	}
}
