// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"io"
	"time"

	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// Project is an object representing the database table.
type Project struct {
	ID          string              `db:"id,pk" json:"id"`
	Name        string              `db:"name" json:"name"`
	Description string              `db:"description" json:"description"`
	CreatedAt   time.Time           `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time           `db:"updated_at" json:"updated_at"`
	ArchivedAt  sql.Null[time.Time] `db:"archived_at" json:"archived_at"`

	R projectR `db:"-" json:"-"`

	C projectC `db:"-" json:"-"`
}

// ProjectSlice is an alias for a slice of pointers to Project.
// This should almost always be used instead of []*Project.
type ProjectSlice []*Project

// Projects contains methods to work with the projects table
var Projects = psql.NewTablex[*Project, ProjectSlice, *ProjectSetter]("", "projects", buildProjectColumns("projects"))

// ProjectsQuery is a query on the projects table
type ProjectsQuery = *psql.ViewQuery[*Project, ProjectSlice]

// projectR is where relationships are stored.
type projectR struct {
	AccessKeys     AccessKeySlice     `json:"AccessKeys"`     // access_keys.access_keys_project_id_fkey
	Inventories    InventorySlice     `json:"Inventories"`    // inventories.inventories_project_id_fkey
	ProjectMembers ProjectMemberSlice `json:"ProjectMembers"` // project_members.project_members_project_id_fkey
	Repositories   RepositorySlice    `json:"Repositories"`   // repositories.repositories_project_id_fkey
	TaskRuns       TaskRunSlice       `json:"TaskRuns"`       // task_runs.task_runs_project_id_fkey
	TaskTemplates  TaskTemplateSlice  `json:"TaskTemplates"`  // task_templates.task_templates_project_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded projectRLoaded `db:"-" json:"-"`
}

// projectRLoaded tracks which relationships on Project have been loaded.
type projectRLoaded struct {
	AccessKeys     bool `json:"AccessKeys"`     // access_keys.access_keys_project_id_fkey
	Inventories    bool `json:"Inventories"`    // inventories.inventories_project_id_fkey
	ProjectMembers bool `json:"ProjectMembers"` // project_members.project_members_project_id_fkey
	Repositories   bool `json:"Repositories"`   // repositories.repositories_project_id_fkey
	TaskRuns       bool `json:"TaskRuns"`       // task_runs.task_runs_project_id_fkey
	TaskTemplates  bool `json:"TaskTemplates"`  // task_templates.task_templates_project_id_fkey
}

func buildProjectColumns(tableName string) projectColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name", "description", "created_at", "updated_at", "archived_at",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return projectColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildProjectColumn(tableName, "id"),
		Name:        buildProjectColumn(tableName, "name"),
		Description: buildProjectColumn(tableName, "description"),
		CreatedAt:   buildProjectColumn(tableName, "created_at"),
		UpdatedAt:   buildProjectColumn(tableName, "updated_at"),
		ArchivedAt:  buildProjectColumn(tableName, "archived_at"),
	}
}

type projectColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          projectColumn
	Name        projectColumn
	Description projectColumn
	CreatedAt   projectColumn
	UpdatedAt   projectColumn
	ArchivedAt  projectColumn
}

// Alias returns the current table alias for the columns set.
func (c projectColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (projectColumns) AliasedAs(tableName string) projectColumns {
	return buildProjectColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c projectColumns) Unqualified() projectColumns {
	return buildProjectColumns("")
}

func buildProjectColumn(alias, name string) projectColumn {
	return projectColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type projectColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c projectColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c projectColumn) ShouldOmitParens() bool {
	return true
}

// ProjectSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ProjectSetter struct {
	ID          *string              `db:"id,pk" json:"id"`
	Name        *string              `db:"name" json:"name"`
	Description *string              `db:"description" json:"description"`
	CreatedAt   *time.Time           `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time           `db:"updated_at" json:"updated_at"`
	ArchivedAt  *sql.Null[time.Time] `db:"archived_at" json:"archived_at"`
}

func (s ProjectSetter) SetColumns() []string {
	vals := make([]string, 0, 6)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.Description != nil {
		vals = append(vals, "description")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	if s.ArchivedAt != nil {
		vals = append(vals, "archived_at")
	}
	return vals
}

func (s ProjectSetter) Overwrite(t *Project) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.Description != nil {
		t.Description = func() string {
			if s.Description == nil {
				return *new(string)
			}
			return *s.Description
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
	if s.ArchivedAt != nil {
		t.ArchivedAt = func() sql.Null[time.Time] {
			if s.ArchivedAt == nil {
				return *new(sql.Null[time.Time])
			}
			v := s.ArchivedAt
			return *v
		}()
	}
}

func (s *ProjectSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Projects.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 6)
		if s.ID != nil {
			vals[0] = psql.Arg(func() string {
				if s.ID == nil {
					return *new(string)
				}
				return *s.ID
			}())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name != nil {
			vals[1] = psql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Description != nil {
			vals[2] = psql.Arg(func() string {
				if s.Description == nil {
					return *new(string)
				}
				return *s.Description
			}())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[3] = psql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt != nil {
			vals[4] = psql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.ArchivedAt != nil {
			vals[5] = psql.Arg(func() sql.Null[time.Time] {
				if s.ArchivedAt == nil {
					return *new(sql.Null[time.Time])
				}
				v := s.ArchivedAt
				return *v
			}())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ProjectSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ProjectSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 6)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Description != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.ArchivedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "archived_at")...),
			psql.Arg(s.ArchivedAt),
		}})
	}

	return exprs
}

// FindProject retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindProject(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*Project, error) {
	if len(cols) == 0 {
		return Projects.Query(
			sm.Where(Projects.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Projects.Query(
		sm.Where(Projects.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Projects.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ProjectExists checks the presence of a single record by primary key
func ProjectExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return Projects.Query(
		sm.Where(Projects.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Project is retrieved from the database
func (o *Project) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Projects.AfterSelectHooks.RunHooks(ctx, exec, ProjectSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Projects.AfterInsertHooks.RunHooks(ctx, exec, ProjectSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Projects.AfterUpdateHooks.RunHooks(ctx, exec, ProjectSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Projects.AfterDeleteHooks.RunHooks(ctx, exec, ProjectSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = Projects.AfterMergeHooks.RunHooks(ctx, exec, ProjectSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Project
func (o *Project) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Project) pkEQ() dialect.Expression {
	return psql.Quote("projects", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Project
func (o *Project) Update(ctx context.Context, exec bob.Executor, s *ProjectSetter) error {
	v, err := Projects.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Project record with an executor
func (o *Project) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Projects.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Project using the executor
func (o *Project) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Projects.Query(
		sm.Where(Projects.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ProjectSlice is retrieved from the database
func (o ProjectSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Projects.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Projects.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Projects.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Projects.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = Projects.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ProjectSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("projects", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ProjectSlice) copyMatchingRows(from ...*Project) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ProjectSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Projects.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Project:
				o.copyMatchingRows(retrieved)
			case []*Project:
				o.copyMatchingRows(retrieved...)
			case ProjectSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Project or a slice of Project
				// then run the AfterUpdateHooks on the slice
				_, err = Projects.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ProjectSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Projects.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Project:
				o.copyMatchingRows(retrieved)
			case []*Project:
				o.copyMatchingRows(retrieved...)
			case ProjectSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Project or a slice of Project
				// then run the AfterDeleteHooks on the slice
				_, err = Projects.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o ProjectSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Projects.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Project:
				o.copyMatchingRows(retrieved)
			case []*Project:
				o.copyMatchingRows(retrieved...)
			case ProjectSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Project or a slice of Project
				// then run the AfterMergeHooks on the slice
				_, err = Projects.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o ProjectSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ProjectSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Projects.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ProjectSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Projects.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ProjectSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Projects.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// AccessKeys starts a query for related objects on access_keys
func (o *Project) AccessKeys(mods ...bob.Mod[*dialect.SelectQuery]) AccessKeysQuery {
	return AccessKeys.Query(append(mods,
		sm.Where(AccessKeys.Columns.ProjectID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ProjectSlice) AccessKeys(mods ...bob.Mod[*dialect.SelectQuery]) AccessKeysQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	return AccessKeys.Query(append(mods,
		sm.Where(psql.Group(AccessKeys.Columns.ProjectID).OP("IN", PKArgExpr)),
	)...)
}

// Inventories starts a query for related objects on inventories
func (o *Project) Inventories(mods ...bob.Mod[*dialect.SelectQuery]) InventoriesQuery {
	return Inventories.Query(append(mods,
		sm.Where(Inventories.Columns.ProjectID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ProjectSlice) Inventories(mods ...bob.Mod[*dialect.SelectQuery]) InventoriesQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	return Inventories.Query(append(mods,
		sm.Where(psql.Group(Inventories.Columns.ProjectID).OP("IN", PKArgExpr)),
	)...)
}

// ProjectMembers starts a query for related objects on project_members
func (o *Project) ProjectMembers(mods ...bob.Mod[*dialect.SelectQuery]) ProjectMembersQuery {
	return ProjectMembers.Query(append(mods,
		sm.Where(ProjectMembers.Columns.ProjectID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ProjectSlice) ProjectMembers(mods ...bob.Mod[*dialect.SelectQuery]) ProjectMembersQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	return ProjectMembers.Query(append(mods,
		sm.Where(psql.Group(ProjectMembers.Columns.ProjectID).OP("IN", PKArgExpr)),
	)...)
}

// Repositories starts a query for related objects on repositories
func (o *Project) Repositories(mods ...bob.Mod[*dialect.SelectQuery]) RepositoriesQuery {
	return Repositories.Query(append(mods,
		sm.Where(Repositories.Columns.ProjectID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ProjectSlice) Repositories(mods ...bob.Mod[*dialect.SelectQuery]) RepositoriesQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	return Repositories.Query(append(mods,
		sm.Where(psql.Group(Repositories.Columns.ProjectID).OP("IN", PKArgExpr)),
	)...)
}

// TaskRuns starts a query for related objects on task_runs
func (o *Project) TaskRuns(mods ...bob.Mod[*dialect.SelectQuery]) TaskRunsQuery {
	return TaskRuns.Query(append(mods,
		sm.Where(TaskRuns.Columns.ProjectID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ProjectSlice) TaskRuns(mods ...bob.Mod[*dialect.SelectQuery]) TaskRunsQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	return TaskRuns.Query(append(mods,
		sm.Where(psql.Group(TaskRuns.Columns.ProjectID).OP("IN", PKArgExpr)),
	)...)
}

// TaskTemplates starts a query for related objects on task_templates
func (o *Project) TaskTemplates(mods ...bob.Mod[*dialect.SelectQuery]) TaskTemplatesQuery {
	return TaskTemplates.Query(append(mods,
		sm.Where(TaskTemplates.Columns.ProjectID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ProjectSlice) TaskTemplates(mods ...bob.Mod[*dialect.SelectQuery]) TaskTemplatesQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	return TaskTemplates.Query(append(mods,
		sm.Where(psql.Group(TaskTemplates.Columns.ProjectID).OP("IN", PKArgExpr)),
	)...)
}

func insertProjectAccessKeys0(ctx context.Context, exec bob.Executor, accessKeys1 []*AccessKeySetter, project0 *Project) (AccessKeySlice, error) {
	for i := range accessKeys1 {
		accessKeys1[i].ProjectID = func() *string { return &project0.ID }()
	}

	ret, err := AccessKeys.Insert(bob.ToMods(accessKeys1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertProjectAccessKeys0: %w", err)
	}

	return ret, nil
}

func attachProjectAccessKeys0(ctx context.Context, exec bob.Executor, count int, accessKeys1 AccessKeySlice, project0 *Project) (AccessKeySlice, error) {
	setter := &AccessKeySetter{
		ProjectID: func() *string { return &project0.ID }(),
	}

	err := accessKeys1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachProjectAccessKeys0: %w", err)
	}

	return accessKeys1, nil
}

func (project0 *Project) InsertAccessKeys(ctx context.Context, exec bob.Executor, related ...*AccessKeySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	accessKeys1, err := insertProjectAccessKeys0(ctx, exec, related, project0)
	if err != nil {
		return err
	}

	project0.R.AccessKeys = append(project0.R.AccessKeys, accessKeys1...)

	return nil
}

func (project0 *Project) AttachAccessKeys(ctx context.Context, exec bob.Executor, related ...*AccessKey) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	accessKeys1 := AccessKeySlice(related)

	_, err = attachProjectAccessKeys0(ctx, exec, len(related), accessKeys1, project0)
	if err != nil {
		return err
	}

	project0.R.AccessKeys = append(project0.R.AccessKeys, accessKeys1...)

	return nil
}

func insertProjectInventories0(ctx context.Context, exec bob.Executor, inventories1 []*InventorySetter, project0 *Project) (InventorySlice, error) {
	for i := range inventories1 {
		inventories1[i].ProjectID = func() *string { return &project0.ID }()
	}

	ret, err := Inventories.Insert(bob.ToMods(inventories1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertProjectInventories0: %w", err)
	}

	return ret, nil
}

func attachProjectInventories0(ctx context.Context, exec bob.Executor, count int, inventories1 InventorySlice, project0 *Project) (InventorySlice, error) {
	setter := &InventorySetter{
		ProjectID: func() *string { return &project0.ID }(),
	}

	err := inventories1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachProjectInventories0: %w", err)
	}

	return inventories1, nil
}

func (project0 *Project) InsertInventories(ctx context.Context, exec bob.Executor, related ...*InventorySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	inventories1, err := insertProjectInventories0(ctx, exec, related, project0)
	if err != nil {
		return err
	}

	project0.R.Inventories = append(project0.R.Inventories, inventories1...)

	return nil
}

func (project0 *Project) AttachInventories(ctx context.Context, exec bob.Executor, related ...*Inventory) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	inventories1 := InventorySlice(related)

	_, err = attachProjectInventories0(ctx, exec, len(related), inventories1, project0)
	if err != nil {
		return err
	}

	project0.R.Inventories = append(project0.R.Inventories, inventories1...)

	return nil
}

func insertProjectProjectMembers0(ctx context.Context, exec bob.Executor, projectMembers1 []*ProjectMemberSetter, project0 *Project) (ProjectMemberSlice, error) {
	for i := range projectMembers1 {
		projectMembers1[i].ProjectID = func() *string { return &project0.ID }()
	}

	ret, err := ProjectMembers.Insert(bob.ToMods(projectMembers1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertProjectProjectMembers0: %w", err)
	}

	return ret, nil
}

func attachProjectProjectMembers0(ctx context.Context, exec bob.Executor, count int, projectMembers1 ProjectMemberSlice, project0 *Project) (ProjectMemberSlice, error) {
	setter := &ProjectMemberSetter{
		ProjectID: func() *string { return &project0.ID }(),
	}

	err := projectMembers1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachProjectProjectMembers0: %w", err)
	}

	return projectMembers1, nil
}

func (project0 *Project) InsertProjectMembers(ctx context.Context, exec bob.Executor, related ...*ProjectMemberSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	projectMembers1, err := insertProjectProjectMembers0(ctx, exec, related, project0)
	if err != nil {
		return err
	}

	project0.R.ProjectMembers = append(project0.R.ProjectMembers, projectMembers1...)

	return nil
}

func (project0 *Project) AttachProjectMembers(ctx context.Context, exec bob.Executor, related ...*ProjectMember) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	projectMembers1 := ProjectMemberSlice(related)

	_, err = attachProjectProjectMembers0(ctx, exec, len(related), projectMembers1, project0)
	if err != nil {
		return err
	}

	project0.R.ProjectMembers = append(project0.R.ProjectMembers, projectMembers1...)

	return nil
}

func insertProjectRepositories0(ctx context.Context, exec bob.Executor, repositories1 []*RepositorySetter, project0 *Project) (RepositorySlice, error) {
	for i := range repositories1 {
		repositories1[i].ProjectID = func() *string { return &project0.ID }()
	}

	ret, err := Repositories.Insert(bob.ToMods(repositories1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertProjectRepositories0: %w", err)
	}

	return ret, nil
}

func attachProjectRepositories0(ctx context.Context, exec bob.Executor, count int, repositories1 RepositorySlice, project0 *Project) (RepositorySlice, error) {
	setter := &RepositorySetter{
		ProjectID: func() *string { return &project0.ID }(),
	}

	err := repositories1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachProjectRepositories0: %w", err)
	}

	return repositories1, nil
}

func (project0 *Project) InsertRepositories(ctx context.Context, exec bob.Executor, related ...*RepositorySetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	repositories1, err := insertProjectRepositories0(ctx, exec, related, project0)
	if err != nil {
		return err
	}

	project0.R.Repositories = append(project0.R.Repositories, repositories1...)

	return nil
}

func (project0 *Project) AttachRepositories(ctx context.Context, exec bob.Executor, related ...*Repository) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	repositories1 := RepositorySlice(related)

	_, err = attachProjectRepositories0(ctx, exec, len(related), repositories1, project0)
	if err != nil {
		return err
	}

	project0.R.Repositories = append(project0.R.Repositories, repositories1...)

	return nil
}

func insertProjectTaskRuns0(ctx context.Context, exec bob.Executor, taskRuns1 []*TaskRunSetter, project0 *Project) (TaskRunSlice, error) {
	for i := range taskRuns1 {
		taskRuns1[i].ProjectID = func() *string { return &project0.ID }()
	}

	ret, err := TaskRuns.Insert(bob.ToMods(taskRuns1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertProjectTaskRuns0: %w", err)
	}

	return ret, nil
}

func attachProjectTaskRuns0(ctx context.Context, exec bob.Executor, count int, taskRuns1 TaskRunSlice, project0 *Project) (TaskRunSlice, error) {
	setter := &TaskRunSetter{
		ProjectID: func() *string { return &project0.ID }(),
	}

	err := taskRuns1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachProjectTaskRuns0: %w", err)
	}

	return taskRuns1, nil
}

func (project0 *Project) InsertTaskRuns(ctx context.Context, exec bob.Executor, related ...*TaskRunSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	taskRuns1, err := insertProjectTaskRuns0(ctx, exec, related, project0)
	if err != nil {
		return err
	}

	project0.R.TaskRuns = append(project0.R.TaskRuns, taskRuns1...)

	return nil
}

func (project0 *Project) AttachTaskRuns(ctx context.Context, exec bob.Executor, related ...*TaskRun) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	taskRuns1 := TaskRunSlice(related)

	_, err = attachProjectTaskRuns0(ctx, exec, len(related), taskRuns1, project0)
	if err != nil {
		return err
	}

	project0.R.TaskRuns = append(project0.R.TaskRuns, taskRuns1...)

	return nil
}

func insertProjectTaskTemplates0(ctx context.Context, exec bob.Executor, taskTemplates1 []*TaskTemplateSetter, project0 *Project) (TaskTemplateSlice, error) {
	for i := range taskTemplates1 {
		taskTemplates1[i].ProjectID = func() *string { return &project0.ID }()
	}

	ret, err := TaskTemplates.Insert(bob.ToMods(taskTemplates1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertProjectTaskTemplates0: %w", err)
	}

	return ret, nil
}

func attachProjectTaskTemplates0(ctx context.Context, exec bob.Executor, count int, taskTemplates1 TaskTemplateSlice, project0 *Project) (TaskTemplateSlice, error) {
	setter := &TaskTemplateSetter{
		ProjectID: func() *string { return &project0.ID }(),
	}

	err := taskTemplates1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachProjectTaskTemplates0: %w", err)
	}

	return taskTemplates1, nil
}

func (project0 *Project) InsertTaskTemplates(ctx context.Context, exec bob.Executor, related ...*TaskTemplateSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	taskTemplates1, err := insertProjectTaskTemplates0(ctx, exec, related, project0)
	if err != nil {
		return err
	}

	project0.R.TaskTemplates = append(project0.R.TaskTemplates, taskTemplates1...)

	return nil
}

func (project0 *Project) AttachTaskTemplates(ctx context.Context, exec bob.Executor, related ...*TaskTemplate) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	taskTemplates1 := TaskTemplateSlice(related)

	_, err = attachProjectTaskTemplates0(ctx, exec, len(related), taskTemplates1, project0)
	if err != nil {
		return err
	}

	project0.R.TaskTemplates = append(project0.R.TaskTemplates, taskTemplates1...)

	return nil
}

type projectWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, string]
	Name        psql.WhereMod[Q, string]
	Description psql.WhereMod[Q, string]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
	ArchivedAt  psql.WhereNullMod[Q, time.Time]
}

func (projectWhere[Q]) AliasedAs(alias string) projectWhere[Q] {
	return buildProjectWhere[Q](buildProjectColumns(alias))
}

func buildProjectWhere[Q psql.Filterable](cols projectColumns) projectWhere[Q] {
	return projectWhere[Q]{
		ID:          psql.Where[Q, string](cols.ID.Expression),
		Name:        psql.Where[Q, string](cols.Name.Expression),
		Description: psql.Where[Q, string](cols.Description.Expression),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt.Expression),
		ArchivedAt:  psql.WhereNull[Q, time.Time](cols.ArchivedAt.Expression),
	}
}

func (o *Project) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "AccessKeys":
		rels, ok := retrieved.(AccessKeySlice)
		if !ok {
			return fmt.Errorf("project cannot load %T as %q", retrieved, name)
		}

		o.R.AccessKeys = rels
		o.R.Loaded.AccessKeys = true

		return nil
	case "Inventories":
		rels, ok := retrieved.(InventorySlice)
		if !ok {
			return fmt.Errorf("project cannot load %T as %q", retrieved, name)
		}

		o.R.Inventories = rels
		o.R.Loaded.Inventories = true

		return nil
	case "ProjectMembers":
		rels, ok := retrieved.(ProjectMemberSlice)
		if !ok {
			return fmt.Errorf("project cannot load %T as %q", retrieved, name)
		}

		o.R.ProjectMembers = rels
		o.R.Loaded.ProjectMembers = true

		return nil
	case "Repositories":
		rels, ok := retrieved.(RepositorySlice)
		if !ok {
			return fmt.Errorf("project cannot load %T as %q", retrieved, name)
		}

		o.R.Repositories = rels
		o.R.Loaded.Repositories = true

		return nil
	case "TaskRuns":
		rels, ok := retrieved.(TaskRunSlice)
		if !ok {
			return fmt.Errorf("project cannot load %T as %q", retrieved, name)
		}

		o.R.TaskRuns = rels
		o.R.Loaded.TaskRuns = true

		return nil
	case "TaskTemplates":
		rels, ok := retrieved.(TaskTemplateSlice)
		if !ok {
			return fmt.Errorf("project cannot load %T as %q", retrieved, name)
		}

		o.R.TaskTemplates = rels
		o.R.Loaded.TaskTemplates = true

		return nil
	default:
		return fmt.Errorf("project has no relationship %q", name)
	}
}

type projectPreloader struct{}

func buildProjectPreloader() projectPreloader {
	return projectPreloader{}
}

type projectThenLoader[Q orm.Loadable] struct {
	AccessKeys     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Inventories    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ProjectMembers func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Repositories   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	TaskRuns       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	TaskTemplates  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildProjectThenLoader[Q orm.Loadable]() projectThenLoader[Q] {
	type AccessKeysLoadInterface interface {
		LoadAccessKeys(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type InventoriesLoadInterface interface {
		LoadInventories(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ProjectMembersLoadInterface interface {
		LoadProjectMembers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type RepositoriesLoadInterface interface {
		LoadRepositories(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TaskRunsLoadInterface interface {
		LoadTaskRuns(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TaskTemplatesLoadInterface interface {
		LoadTaskTemplates(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return projectThenLoader[Q]{
		AccessKeys: thenLoadBuilder[Q](
			"AccessKeys",
			func(ctx context.Context, exec bob.Executor, retrieved AccessKeysLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadAccessKeys(ctx, exec, mods...)
			},
		),
		Inventories: thenLoadBuilder[Q](
			"Inventories",
			func(ctx context.Context, exec bob.Executor, retrieved InventoriesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadInventories(ctx, exec, mods...)
			},
		),
		ProjectMembers: thenLoadBuilder[Q](
			"ProjectMembers",
			func(ctx context.Context, exec bob.Executor, retrieved ProjectMembersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadProjectMembers(ctx, exec, mods...)
			},
		),
		Repositories: thenLoadBuilder[Q](
			"Repositories",
			func(ctx context.Context, exec bob.Executor, retrieved RepositoriesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadRepositories(ctx, exec, mods...)
			},
		),
		TaskRuns: thenLoadBuilder[Q](
			"TaskRuns",
			func(ctx context.Context, exec bob.Executor, retrieved TaskRunsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTaskRuns(ctx, exec, mods...)
			},
		),
		TaskTemplates: thenLoadBuilder[Q](
			"TaskTemplates",
			func(ctx context.Context, exec bob.Executor, retrieved TaskTemplatesLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTaskTemplates(ctx, exec, mods...)
			},
		),
	}
}

// LoadAccessKeys loads the project's AccessKeys into the .R struct
func (o *Project) LoadAccessKeys(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.AccessKeys = nil
	o.R.Loaded.AccessKeys = false

	related, err := o.AccessKeys(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.AccessKeys = related
	o.R.Loaded.AccessKeys = true
	return nil
}

// LoadAccessKeys loads the project's AccessKeys into the .R struct
func (os ProjectSlice) LoadAccessKeys(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	accessKeys, err := os.AccessKeys(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.AccessKeys = nil
		o.R.Loaded.AccessKeys = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range accessKeys {

			if !(o.ID == rel.ProjectID) {
				continue
			}

			o.R.AccessKeys = append(o.R.AccessKeys, rel)
		}
	}

	return nil
}

// LoadInventories loads the project's Inventories into the .R struct
func (o *Project) LoadInventories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Inventories = nil
	o.R.Loaded.Inventories = false

	related, err := o.Inventories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.Inventories = related
	o.R.Loaded.Inventories = true
	return nil
}

// LoadInventories loads the project's Inventories into the .R struct
func (os ProjectSlice) LoadInventories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	inventories, err := os.Inventories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Inventories = nil
		o.R.Loaded.Inventories = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range inventories {

			if !(o.ID == rel.ProjectID) {
				continue
			}

			o.R.Inventories = append(o.R.Inventories, rel)
		}
	}

	return nil
}

// LoadProjectMembers loads the project's ProjectMembers into the .R struct
func (o *Project) LoadProjectMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.ProjectMembers = nil
	o.R.Loaded.ProjectMembers = false

	related, err := o.ProjectMembers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.ProjectMembers = related
	o.R.Loaded.ProjectMembers = true
	return nil
}

// LoadProjectMembers loads the project's ProjectMembers into the .R struct
func (os ProjectSlice) LoadProjectMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	projectMembers, err := os.ProjectMembers(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.ProjectMembers = nil
		o.R.Loaded.ProjectMembers = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range projectMembers {

			if !(o.ID == rel.ProjectID) {
				continue
			}

			o.R.ProjectMembers = append(o.R.ProjectMembers, rel)
		}
	}

	return nil
}

// LoadRepositories loads the project's Repositories into the .R struct
func (o *Project) LoadRepositories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Repositories = nil
	o.R.Loaded.Repositories = false

	related, err := o.Repositories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.Repositories = related
	o.R.Loaded.Repositories = true
	return nil
}

// LoadRepositories loads the project's Repositories into the .R struct
func (os ProjectSlice) LoadRepositories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	repositories, err := os.Repositories(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Repositories = nil
		o.R.Loaded.Repositories = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range repositories {

			if !(o.ID == rel.ProjectID) {
				continue
			}

			o.R.Repositories = append(o.R.Repositories, rel)
		}
	}

	return nil
}

// LoadTaskRuns loads the project's TaskRuns into the .R struct
func (o *Project) LoadTaskRuns(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.TaskRuns = nil
	o.R.Loaded.TaskRuns = false

	related, err := o.TaskRuns(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.TaskRuns = related
	o.R.Loaded.TaskRuns = true
	return nil
}

// LoadTaskRuns loads the project's TaskRuns into the .R struct
func (os ProjectSlice) LoadTaskRuns(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	taskRuns, err := os.TaskRuns(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.TaskRuns = nil
		o.R.Loaded.TaskRuns = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range taskRuns {

			if !(o.ID == rel.ProjectID) {
				continue
			}

			o.R.TaskRuns = append(o.R.TaskRuns, rel)
		}
	}

	return nil
}

// LoadTaskTemplates loads the project's TaskTemplates into the .R struct
func (o *Project) LoadTaskTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.TaskTemplates = nil
	o.R.Loaded.TaskTemplates = false

	related, err := o.TaskTemplates(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.TaskTemplates = related
	o.R.Loaded.TaskTemplates = true
	return nil
}

// LoadTaskTemplates loads the project's TaskTemplates into the .R struct
func (os ProjectSlice) LoadTaskTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	taskTemplates, err := os.TaskTemplates(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.TaskTemplates = nil
		o.R.Loaded.TaskTemplates = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range taskTemplates {

			if !(o.ID == rel.ProjectID) {
				continue
			}

			o.R.TaskTemplates = append(o.R.TaskTemplates, rel)
		}
	}

	return nil
}

// projectC is where relationship counts are stored.
type projectC struct {
	AccessKeys     *int64 `json:"AccessKeys"`
	Inventories    *int64 `json:"Inventories"`
	ProjectMembers *int64 `json:"ProjectMembers"`
	Repositories   *int64 `json:"Repositories"`
	TaskRuns       *int64 `json:"TaskRuns"`
	TaskTemplates  *int64 `json:"TaskTemplates"`
}

// PreloadCount sets a count in the C struct by name
func (o *Project) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "AccessKeys":
		o.C.AccessKeys = &count
	case "Inventories":
		o.C.Inventories = &count
	case "ProjectMembers":
		o.C.ProjectMembers = &count
	case "Repositories":
		o.C.Repositories = &count
	case "TaskRuns":
		o.C.TaskRuns = &count
	case "TaskTemplates":
		o.C.TaskTemplates = &count
	}
	return nil
}

type projectCountPreloader struct {
	AccessKeys     func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	Inventories    func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	ProjectMembers func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	Repositories   func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	TaskRuns       func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	TaskTemplates  func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildProjectCountPreloader() projectCountPreloader {
	return projectCountPreloader{
		AccessKeys: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Project]("AccessKeys", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Projects.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(AccessKeys.NameAsExpr()),
					sm.Where(psql.Quote(AccessKeys.Alias(), "project_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		Inventories: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Project]("Inventories", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Projects.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Inventories.NameAsExpr()),
					sm.Where(psql.Quote(Inventories.Alias(), "project_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		ProjectMembers: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Project]("ProjectMembers", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Projects.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(ProjectMembers.NameAsExpr()),
					sm.Where(psql.Quote(ProjectMembers.Alias(), "project_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		Repositories: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Project]("Repositories", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Projects.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Repositories.NameAsExpr()),
					sm.Where(psql.Quote(Repositories.Alias(), "project_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		TaskRuns: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Project]("TaskRuns", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Projects.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(TaskRuns.NameAsExpr()),
					sm.Where(psql.Quote(TaskRuns.Alias(), "project_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		TaskTemplates: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Project]("TaskTemplates", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Projects.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(TaskTemplates.NameAsExpr()),
					sm.Where(psql.Quote(TaskTemplates.Alias(), "project_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type projectCountThenLoader[Q orm.Loadable] struct {
	AccessKeys     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Inventories    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	ProjectMembers func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Repositories   func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	TaskRuns       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	TaskTemplates  func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildProjectCountThenLoader[Q orm.Loadable]() projectCountThenLoader[Q] {
	type AccessKeysCountInterface interface {
		LoadCountAccessKeys(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type InventoriesCountInterface interface {
		LoadCountInventories(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ProjectMembersCountInterface interface {
		LoadCountProjectMembers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type RepositoriesCountInterface interface {
		LoadCountRepositories(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TaskRunsCountInterface interface {
		LoadCountTaskRuns(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TaskTemplatesCountInterface interface {
		LoadCountTaskTemplates(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return projectCountThenLoader[Q]{
		AccessKeys: countThenLoadBuilder[Q](
			"AccessKeys",
			func(ctx context.Context, exec bob.Executor, retrieved AccessKeysCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountAccessKeys(ctx, exec, mods...)
			},
		),
		Inventories: countThenLoadBuilder[Q](
			"Inventories",
			func(ctx context.Context, exec bob.Executor, retrieved InventoriesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountInventories(ctx, exec, mods...)
			},
		),
		ProjectMembers: countThenLoadBuilder[Q](
			"ProjectMembers",
			func(ctx context.Context, exec bob.Executor, retrieved ProjectMembersCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountProjectMembers(ctx, exec, mods...)
			},
		),
		Repositories: countThenLoadBuilder[Q](
			"Repositories",
			func(ctx context.Context, exec bob.Executor, retrieved RepositoriesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountRepositories(ctx, exec, mods...)
			},
		),
		TaskRuns: countThenLoadBuilder[Q](
			"TaskRuns",
			func(ctx context.Context, exec bob.Executor, retrieved TaskRunsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTaskRuns(ctx, exec, mods...)
			},
		),
		TaskTemplates: countThenLoadBuilder[Q](
			"TaskTemplates",
			func(ctx context.Context, exec bob.Executor, retrieved TaskTemplatesCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTaskTemplates(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountAccessKeys loads the count of AccessKeys into the C struct
func (o *Project) LoadCountAccessKeys(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.AccessKeys(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.AccessKeys = &count
	return nil
}

// LoadCountAccessKeys loads the count of AccessKeys for a slice in a single batch query
func (os ProjectSlice) LoadCountAccessKeys(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			AccessKeys.Columns.ProjectID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(AccessKeys.NameAsExpr()),

		// WHERE fk IN (parent PKs)
		sm.Where(AccessKeys.Columns.ProjectID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(AccessKeys.Columns.ProjectID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.AccessKeys = &count
	}

	return nil
}

// LoadCountInventories loads the count of Inventories into the C struct
func (o *Project) LoadCountInventories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Inventories(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Inventories = &count
	return nil
}

// LoadCountInventories loads the count of Inventories for a slice in a single batch query
func (os ProjectSlice) LoadCountInventories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Inventories.Columns.ProjectID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Inventories.NameAsExpr()),

		// WHERE fk IN (parent PKs)
		sm.Where(Inventories.Columns.ProjectID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Inventories.Columns.ProjectID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Inventories = &count
	}

	return nil
}

// LoadCountProjectMembers loads the count of ProjectMembers into the C struct
func (o *Project) LoadCountProjectMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.ProjectMembers(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.ProjectMembers = &count
	return nil
}

// LoadCountProjectMembers loads the count of ProjectMembers for a slice in a single batch query
func (os ProjectSlice) LoadCountProjectMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			ProjectMembers.Columns.ProjectID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(ProjectMembers.NameAsExpr()),

		// WHERE fk IN (parent PKs)
		sm.Where(ProjectMembers.Columns.ProjectID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(ProjectMembers.Columns.ProjectID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.ProjectMembers = &count
	}

	return nil
}

// LoadCountRepositories loads the count of Repositories into the C struct
func (o *Project) LoadCountRepositories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Repositories(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Repositories = &count
	return nil
}

// LoadCountRepositories loads the count of Repositories for a slice in a single batch query
func (os ProjectSlice) LoadCountRepositories(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			Repositories.Columns.ProjectID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(Repositories.NameAsExpr()),

		// WHERE fk IN (parent PKs)
		sm.Where(Repositories.Columns.ProjectID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(Repositories.Columns.ProjectID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.Repositories = &count
	}

	return nil
}

// LoadCountTaskRuns loads the count of TaskRuns into the C struct
func (o *Project) LoadCountTaskRuns(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.TaskRuns(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.TaskRuns = &count
	return nil
}

// LoadCountTaskRuns loads the count of TaskRuns for a slice in a single batch query
func (os ProjectSlice) LoadCountTaskRuns(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			TaskRuns.Columns.ProjectID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(TaskRuns.NameAsExpr()),

		// WHERE fk IN (parent PKs)
		sm.Where(TaskRuns.Columns.ProjectID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(TaskRuns.Columns.ProjectID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.TaskRuns = &count
	}

	return nil
}

// LoadCountTaskTemplates loads the count of TaskTemplates into the C struct
func (o *Project) LoadCountTaskTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.TaskTemplates(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.TaskTemplates = &count
	return nil
}

// LoadCountTaskTemplates loads the count of TaskTemplates for a slice in a single batch query
func (os ProjectSlice) LoadCountTaskTemplates(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			TaskTemplates.Columns.ProjectID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(TaskTemplates.NameAsExpr()),

		// WHERE fk IN (parent PKs)
		sm.Where(TaskTemplates.Columns.ProjectID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(TaskTemplates.Columns.ProjectID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.TaskTemplates = &count
	}

	return nil
}

type projectJoins[Q dialect.Joinable] struct {
	typ            string
	AccessKeys     modAs[Q, accessKeyColumns]
	Inventories    modAs[Q, inventoryColumns]
	ProjectMembers modAs[Q, projectMemberColumns]
	Repositories   modAs[Q, repositoryColumns]
	TaskRuns       modAs[Q, taskRunColumns]
	TaskTemplates  modAs[Q, taskTemplateColumns]
}

func (j projectJoins[Q]) aliasedAs(alias string) projectJoins[Q] {
	return buildProjectJoins[Q](buildProjectColumns(alias), j.typ)
}

func buildProjectJoins[Q dialect.Joinable](cols projectColumns, typ string) projectJoins[Q] {
	return projectJoins[Q]{
		typ: typ,
		AccessKeys: modAs[Q, accessKeyColumns]{
			c: AccessKeys.Columns,
			f: func(to accessKeyColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, AccessKeys.NameExpr().As(to.Alias())).On(
						to.ProjectID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Inventories: modAs[Q, inventoryColumns]{
			c: Inventories.Columns,
			f: func(to inventoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Inventories.NameExpr().As(to.Alias())).On(
						to.ProjectID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		ProjectMembers: modAs[Q, projectMemberColumns]{
			c: ProjectMembers.Columns,
			f: func(to projectMemberColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, ProjectMembers.NameExpr().As(to.Alias())).On(
						to.ProjectID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Repositories: modAs[Q, repositoryColumns]{
			c: Repositories.Columns,
			f: func(to repositoryColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Repositories.NameExpr().As(to.Alias())).On(
						to.ProjectID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		TaskRuns: modAs[Q, taskRunColumns]{
			c: TaskRuns.Columns,
			f: func(to taskRunColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, TaskRuns.NameExpr().As(to.Alias())).On(
						to.ProjectID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		TaskTemplates: modAs[Q, taskTemplateColumns]{
			c: TaskTemplates.Columns,
			f: func(to taskTemplateColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, TaskTemplates.NameExpr().As(to.Alias())).On(
						to.ProjectID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
