// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"time"

	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types"
	"github.com/stephenafamo/bob/types/pgtypes"
	"github.com/stephenafamo/scan"
)

// TaskTemplate is an object representing the database table.
type TaskTemplate struct {
	ID          string                      `db:"id,pk" json:"id"`
	ProjectID   string                      `db:"project_id" json:"project_id"`
	Name        string                      `db:"name" json:"name"`
	Kind        string                      `db:"kind" json:"kind"`
	RunnerTags  pq.StringArray              `db:"runner_tags" json:"runner_tags"`
	RequiresAck bool                        `db:"requires_ack" json:"requires_ack"`
	CreatedAt   time.Time                   `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time                   `db:"updated_at" json:"updated_at"`
	RunSpec     types.JSON[json.RawMessage] `db:"run_spec" json:"run_spec"`
	Workflow    types.JSON[json.RawMessage] `db:"workflow" json:"workflow"`

	R taskTemplateR `db:"-" json:"-"`

	C taskTemplateC `db:"-" json:"-"`
}

// TaskTemplateSlice is an alias for a slice of pointers to TaskTemplate.
// This should almost always be used instead of []*TaskTemplate.
type TaskTemplateSlice []*TaskTemplate

// TaskTemplates contains methods to work with the task_templates table
var TaskTemplates = psql.NewTablex[*TaskTemplate, TaskTemplateSlice, *TaskTemplateSetter]("", "task_templates", buildTaskTemplateColumns("task_templates"))

// TaskTemplatesQuery is a query on the task_templates table
type TaskTemplatesQuery = *psql.ViewQuery[*TaskTemplate, TaskTemplateSlice]

// taskTemplateR is where relationships are stored.
type taskTemplateR struct {
	TemplateTaskRuns TaskRunSlice `json:"TemplateTaskRuns"` // task_runs.task_runs_template_id_fkey
	Project          *Project     `json:"Project"`          // task_templates.task_templates_project_id_fkey
	// Loaded reports whether each relationship has been loaded.
	// A relationship's bool is set by Load*, Preload, ThenLoad, factory builds,
	// and to-one Attach/Insert operations. To-many Attach/Insert operations leave it unchanged.
	Loaded taskTemplateRLoaded `db:"-" json:"-"`
}

// taskTemplateRLoaded tracks which relationships on TaskTemplate have been loaded.
type taskTemplateRLoaded struct {
	TemplateTaskRuns bool `json:"TemplateTaskRuns"` // task_runs.task_runs_template_id_fkey
	Project          bool `json:"Project"`          // task_templates.task_templates_project_id_fkey
}

func buildTaskTemplateColumns(tableName string) taskTemplateColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "project_id", "name", "kind", "runner_tags", "requires_ack", "created_at", "updated_at", "run_spec", "workflow",
	)

	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}

	return taskTemplateColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          buildTaskTemplateColumn(tableName, "id"),
		ProjectID:   buildTaskTemplateColumn(tableName, "project_id"),
		Name:        buildTaskTemplateColumn(tableName, "name"),
		Kind:        buildTaskTemplateColumn(tableName, "kind"),
		RunnerTags:  buildTaskTemplateColumn(tableName, "runner_tags"),
		RequiresAck: buildTaskTemplateColumn(tableName, "requires_ack"),
		CreatedAt:   buildTaskTemplateColumn(tableName, "created_at"),
		UpdatedAt:   buildTaskTemplateColumn(tableName, "updated_at"),
		RunSpec:     buildTaskTemplateColumn(tableName, "run_spec"),
		Workflow:    buildTaskTemplateColumn(tableName, "workflow"),
	}
}

type taskTemplateColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          taskTemplateColumn
	ProjectID   taskTemplateColumn
	Name        taskTemplateColumn
	Kind        taskTemplateColumn
	RunnerTags  taskTemplateColumn
	RequiresAck taskTemplateColumn
	CreatedAt   taskTemplateColumn
	UpdatedAt   taskTemplateColumn
	RunSpec     taskTemplateColumn
	Workflow    taskTemplateColumn
}

// Alias returns the current table alias for the columns set.
func (c taskTemplateColumns) Alias() string {
	return c.tableAlias
}

// AliasedAs returns a copy of the columns set qualified by tableName.
func (taskTemplateColumns) AliasedAs(tableName string) taskTemplateColumns {
	return buildTaskTemplateColumns(tableName)
}

// Unqualified returns a copy of the columns set without table qualification.
func (c taskTemplateColumns) Unqualified() taskTemplateColumns {
	return buildTaskTemplateColumns("")
}

func buildTaskTemplateColumn(alias, name string) taskTemplateColumn {
	return taskTemplateColumn{
		Expression: psql.Quote(alias, name),
		alias:      alias,
		name:       name,
	}
}

type taskTemplateColumn struct {
	psql.Expression
	alias string
	name  string
}

// Name returns the unqualified column name.
func (c taskTemplateColumn) Name() string {
	return c.name
}

// ShouldOmitParens prevents automatic parenthesis wrapping in expression builders.
func (c taskTemplateColumn) ShouldOmitParens() bool {
	return true
}

// TaskTemplateSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TaskTemplateSetter struct {
	ID          *string                      `db:"id,pk" json:"id"`
	ProjectID   *string                      `db:"project_id" json:"project_id"`
	Name        *string                      `db:"name" json:"name"`
	Kind        *string                      `db:"kind" json:"kind"`
	RunnerTags  *pq.StringArray              `db:"runner_tags" json:"runner_tags"`
	RequiresAck *bool                        `db:"requires_ack" json:"requires_ack"`
	CreatedAt   *time.Time                   `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time                   `db:"updated_at" json:"updated_at"`
	RunSpec     *types.JSON[json.RawMessage] `db:"run_spec" json:"run_spec"`
	Workflow    *types.JSON[json.RawMessage] `db:"workflow" json:"workflow"`
}

func (s TaskTemplateSetter) SetColumns() []string {
	vals := make([]string, 0, 10)
	if s.ID != nil {
		vals = append(vals, "id")
	}
	if s.ProjectID != nil {
		vals = append(vals, "project_id")
	}
	if s.Name != nil {
		vals = append(vals, "name")
	}
	if s.Kind != nil {
		vals = append(vals, "kind")
	}
	if s.RunnerTags != nil {
		vals = append(vals, "runner_tags")
	}
	if s.RequiresAck != nil {
		vals = append(vals, "requires_ack")
	}
	if s.CreatedAt != nil {
		vals = append(vals, "created_at")
	}
	if s.UpdatedAt != nil {
		vals = append(vals, "updated_at")
	}
	if s.RunSpec != nil {
		vals = append(vals, "run_spec")
	}
	if s.Workflow != nil {
		vals = append(vals, "workflow")
	}
	return vals
}

func (s TaskTemplateSetter) Overwrite(t *TaskTemplate) {
	if s.ID != nil {
		t.ID = func() string {
			if s.ID == nil {
				return *new(string)
			}
			return *s.ID
		}()
	}
	if s.ProjectID != nil {
		t.ProjectID = func() string {
			if s.ProjectID == nil {
				return *new(string)
			}
			return *s.ProjectID
		}()
	}
	if s.Name != nil {
		t.Name = func() string {
			if s.Name == nil {
				return *new(string)
			}
			return *s.Name
		}()
	}
	if s.Kind != nil {
		t.Kind = func() string {
			if s.Kind == nil {
				return *new(string)
			}
			return *s.Kind
		}()
	}
	if s.RunnerTags != nil {
		t.RunnerTags = func() pq.StringArray {
			if s.RunnerTags == nil {
				return *new(pq.StringArray)
			}
			return *s.RunnerTags
		}()
	}
	if s.RequiresAck != nil {
		t.RequiresAck = func() bool {
			if s.RequiresAck == nil {
				return *new(bool)
			}
			return *s.RequiresAck
		}()
	}
	if s.CreatedAt != nil {
		t.CreatedAt = func() time.Time {
			if s.CreatedAt == nil {
				return *new(time.Time)
			}
			return *s.CreatedAt
		}()
	}
	if s.UpdatedAt != nil {
		t.UpdatedAt = func() time.Time {
			if s.UpdatedAt == nil {
				return *new(time.Time)
			}
			return *s.UpdatedAt
		}()
	}
	if s.RunSpec != nil {
		t.RunSpec = func() types.JSON[json.RawMessage] {
			if s.RunSpec == nil {
				return *new(types.JSON[json.RawMessage])
			}
			return *s.RunSpec
		}()
	}
	if s.Workflow != nil {
		t.Workflow = func() types.JSON[json.RawMessage] {
			if s.Workflow == nil {
				return *new(types.JSON[json.RawMessage])
			}
			return *s.Workflow
		}()
	}
}

func (s *TaskTemplateSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return TaskTemplates.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 10)
		if s.ID != nil {
			vals[0] = psql.Arg(func() string {
				if s.ID == nil {
					return *new(string)
				}
				return *s.ID
			}())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.ProjectID != nil {
			vals[1] = psql.Arg(func() string {
				if s.ProjectID == nil {
					return *new(string)
				}
				return *s.ProjectID
			}())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name != nil {
			vals[2] = psql.Arg(func() string {
				if s.Name == nil {
					return *new(string)
				}
				return *s.Name
			}())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Kind != nil {
			vals[3] = psql.Arg(func() string {
				if s.Kind == nil {
					return *new(string)
				}
				return *s.Kind
			}())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.RunnerTags != nil {
			vals[4] = psql.Arg(func() pq.StringArray {
				if s.RunnerTags == nil {
					return *new(pq.StringArray)
				}
				return *s.RunnerTags
			}())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.RequiresAck != nil {
			vals[5] = psql.Arg(func() bool {
				if s.RequiresAck == nil {
					return *new(bool)
				}
				return *s.RequiresAck
			}())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.CreatedAt != nil {
			vals[6] = psql.Arg(func() time.Time {
				if s.CreatedAt == nil {
					return *new(time.Time)
				}
				return *s.CreatedAt
			}())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.UpdatedAt != nil {
			vals[7] = psql.Arg(func() time.Time {
				if s.UpdatedAt == nil {
					return *new(time.Time)
				}
				return *s.UpdatedAt
			}())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if s.RunSpec != nil {
			vals[8] = psql.Arg(func() types.JSON[json.RawMessage] {
				if s.RunSpec == nil {
					return *new(types.JSON[json.RawMessage])
				}
				return *s.RunSpec
			}())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		if s.Workflow != nil {
			vals[9] = psql.Arg(func() types.JSON[json.RawMessage] {
				if s.Workflow == nil {
					return *new(types.JSON[json.RawMessage])
				}
				return *s.Workflow
			}())
		} else {
			vals[9] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TaskTemplateSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TaskTemplateSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 10)

	if s.ID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.ProjectID != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "project_id")...),
			psql.Arg(s.ProjectID),
		}})
	}

	if s.Name != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Kind != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "kind")...),
			psql.Arg(s.Kind),
		}})
	}

	if s.RunnerTags != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "runner_tags")...),
			psql.Arg(s.RunnerTags),
		}})
	}

	if s.RequiresAck != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "requires_ack")...),
			psql.Arg(s.RequiresAck),
		}})
	}

	if s.CreatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "created_at")...),
			psql.Arg(s.CreatedAt),
		}})
	}

	if s.UpdatedAt != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "updated_at")...),
			psql.Arg(s.UpdatedAt),
		}})
	}

	if s.RunSpec != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "run_spec")...),
			psql.Arg(s.RunSpec),
		}})
	}

	if s.Workflow != nil {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "workflow")...),
			psql.Arg(s.Workflow),
		}})
	}

	return exprs
}

// FindTaskTemplate retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTaskTemplate(ctx context.Context, exec bob.Executor, IDPK string, cols ...string) (*TaskTemplate, error) {
	if len(cols) == 0 {
		return TaskTemplates.Query(
			sm.Where(TaskTemplates.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return TaskTemplates.Query(
		sm.Where(TaskTemplates.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(TaskTemplates.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TaskTemplateExists checks the presence of a single record by primary key
func TaskTemplateExists(ctx context.Context, exec bob.Executor, IDPK string) (bool, error) {
	return TaskTemplates.Query(
		sm.Where(TaskTemplates.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after TaskTemplate is retrieved from the database
func (o *TaskTemplate) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = TaskTemplates.AfterSelectHooks.RunHooks(ctx, exec, TaskTemplateSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = TaskTemplates.AfterInsertHooks.RunHooks(ctx, exec, TaskTemplateSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = TaskTemplates.AfterUpdateHooks.RunHooks(ctx, exec, TaskTemplateSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = TaskTemplates.AfterDeleteHooks.RunHooks(ctx, exec, TaskTemplateSlice{o})
	case bob.QueryTypeMerge:
		ctx, err = TaskTemplates.AfterMergeHooks.RunHooks(ctx, exec, TaskTemplateSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the TaskTemplate
func (o *TaskTemplate) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *TaskTemplate) pkEQ() dialect.Expression {
	return psql.Quote("task_templates", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the TaskTemplate
func (o *TaskTemplate) Update(ctx context.Context, exec bob.Executor, s *TaskTemplateSetter) error {
	v, err := TaskTemplates.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single TaskTemplate record with an executor
func (o *TaskTemplate) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := TaskTemplates.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the TaskTemplate using the executor
func (o *TaskTemplate) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := TaskTemplates.Query(
		sm.Where(TaskTemplates.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TaskTemplateSlice is retrieved from the database
func (o TaskTemplateSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = TaskTemplates.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = TaskTemplates.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = TaskTemplates.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = TaskTemplates.AfterDeleteHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeMerge:
		ctx, err = TaskTemplates.AfterMergeHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TaskTemplateSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("task_templates", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TaskTemplateSlice) copyMatchingRows(from ...*TaskTemplate) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TaskTemplateSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return TaskTemplates.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *TaskTemplate:
				o.copyMatchingRows(retrieved)
			case []*TaskTemplate:
				o.copyMatchingRows(retrieved...)
			case TaskTemplateSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a TaskTemplate or a slice of TaskTemplate
				// then run the AfterUpdateHooks on the slice
				_, err = TaskTemplates.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TaskTemplateSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return TaskTemplates.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *TaskTemplate:
				o.copyMatchingRows(retrieved)
			case []*TaskTemplate:
				o.copyMatchingRows(retrieved...)
			case TaskTemplateSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a TaskTemplate or a slice of TaskTemplate
				// then run the AfterDeleteHooks on the slice
				_, err = TaskTemplates.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// MergeMod modifies a merge query to run BeforeMergeHooks and AfterMergeHooks
// and updates the slice with the returned rows.
func (o TaskTemplateSlice) MergeMod() bob.Mod[*dialect.MergeQuery] {
	return bob.ModFunc[*dialect.MergeQuery](func(q *dialect.MergeQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return TaskTemplates.BeforeMergeHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *TaskTemplate:
				o.copyMatchingRows(retrieved)
			case []*TaskTemplate:
				o.copyMatchingRows(retrieved...)
			case TaskTemplateSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a TaskTemplate or a slice of TaskTemplate
				// then run the AfterMergeHooks on the slice
				_, err = TaskTemplates.AfterMergeHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))
	})
}

func (o TaskTemplateSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TaskTemplateSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := TaskTemplates.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TaskTemplateSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := TaskTemplates.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TaskTemplateSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := TaskTemplates.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// TemplateTaskRuns starts a query for related objects on task_runs
func (o *TaskTemplate) TemplateTaskRuns(mods ...bob.Mod[*dialect.SelectQuery]) TaskRunsQuery {
	return TaskRuns.Query(append(mods,
		sm.Where(TaskRuns.Columns.TemplateID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os TaskTemplateSlice) TemplateTaskRuns(mods ...bob.Mod[*dialect.SelectQuery]) TaskRunsQuery {
	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	return TaskRuns.Query(append(mods,
		sm.Where(psql.Group(TaskRuns.Columns.TemplateID).OP("IN", PKArgExpr)),
	)...)
}

// Project starts a query for related objects on projects
func (o *TaskTemplate) Project(mods ...bob.Mod[*dialect.SelectQuery]) ProjectsQuery {
	return Projects.Query(append(mods,
		sm.Where(Projects.Columns.ID.EQ(psql.Arg(o.ProjectID))),
	)...)
}

func (os TaskTemplateSlice) Project(mods ...bob.Mod[*dialect.SelectQuery]) ProjectsQuery {
	pkProjectID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkProjectID = append(pkProjectID, o.ProjectID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkProjectID), "text[]")),
	))

	return Projects.Query(append(mods,
		sm.Where(psql.Group(Projects.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertTaskTemplateTemplateTaskRuns0(ctx context.Context, exec bob.Executor, taskRuns1 []*TaskRunSetter, taskTemplate0 *TaskTemplate) (TaskRunSlice, error) {
	for i := range taskRuns1 {
		taskRuns1[i].TemplateID = func() *sql.Null[string] { v := sql.Null[string]{V: taskTemplate0.ID, Valid: true}; return &v }()
	}

	ret, err := TaskRuns.Insert(bob.ToMods(taskRuns1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertTaskTemplateTemplateTaskRuns0: %w", err)
	}

	return ret, nil
}

func attachTaskTemplateTemplateTaskRuns0(ctx context.Context, exec bob.Executor, count int, taskRuns1 TaskRunSlice, taskTemplate0 *TaskTemplate) (TaskRunSlice, error) {
	setter := &TaskRunSetter{
		TemplateID: func() *sql.Null[string] { v := sql.Null[string]{V: taskTemplate0.ID, Valid: true}; return &v }(),
	}

	err := taskRuns1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachTaskTemplateTemplateTaskRuns0: %w", err)
	}

	return taskRuns1, nil
}

func (taskTemplate0 *TaskTemplate) InsertTemplateTaskRuns(ctx context.Context, exec bob.Executor, related ...*TaskRunSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	taskRuns1, err := insertTaskTemplateTemplateTaskRuns0(ctx, exec, related, taskTemplate0)
	if err != nil {
		return err
	}

	taskTemplate0.R.TemplateTaskRuns = append(taskTemplate0.R.TemplateTaskRuns, taskRuns1...)

	return nil
}

func (taskTemplate0 *TaskTemplate) AttachTemplateTaskRuns(ctx context.Context, exec bob.Executor, related ...*TaskRun) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	taskRuns1 := TaskRunSlice(related)

	_, err = attachTaskTemplateTemplateTaskRuns0(ctx, exec, len(related), taskRuns1, taskTemplate0)
	if err != nil {
		return err
	}

	taskTemplate0.R.TemplateTaskRuns = append(taskTemplate0.R.TemplateTaskRuns, taskRuns1...)

	return nil
}

func attachTaskTemplateProject0(ctx context.Context, exec bob.Executor, count int, taskTemplate0 *TaskTemplate, project1 *Project) (*TaskTemplate, error) {
	setter := &TaskTemplateSetter{
		ProjectID: func() *string { return &project1.ID }(),
	}

	err := taskTemplate0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTaskTemplateProject0: %w", err)
	}

	return taskTemplate0, nil
}

func (taskTemplate0 *TaskTemplate) InsertProject(ctx context.Context, exec bob.Executor, related *ProjectSetter) error {
	var err error

	project1, err := Projects.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTaskTemplateProject0(ctx, exec, 1, taskTemplate0, project1)
	if err != nil {
		return err
	}

	taskTemplate0.R.Project = project1
	taskTemplate0.R.Loaded.Project = true

	return nil
}

func (taskTemplate0 *TaskTemplate) AttachProject(ctx context.Context, exec bob.Executor, project1 *Project) error {
	var err error

	_, err = attachTaskTemplateProject0(ctx, exec, 1, taskTemplate0, project1)
	if err != nil {
		return err
	}

	taskTemplate0.R.Project = project1
	taskTemplate0.R.Loaded.Project = true

	return nil
}

type taskTemplateWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, string]
	ProjectID   psql.WhereMod[Q, string]
	Name        psql.WhereMod[Q, string]
	Kind        psql.WhereMod[Q, string]
	RunnerTags  psql.WhereMod[Q, pq.StringArray]
	RequiresAck psql.WhereMod[Q, bool]
	CreatedAt   psql.WhereMod[Q, time.Time]
	UpdatedAt   psql.WhereMod[Q, time.Time]
	RunSpec     psql.WhereMod[Q, types.JSON[json.RawMessage]]
	Workflow    psql.WhereMod[Q, types.JSON[json.RawMessage]]
}

func (taskTemplateWhere[Q]) AliasedAs(alias string) taskTemplateWhere[Q] {
	return buildTaskTemplateWhere[Q](buildTaskTemplateColumns(alias))
}

func buildTaskTemplateWhere[Q psql.Filterable](cols taskTemplateColumns) taskTemplateWhere[Q] {
	return taskTemplateWhere[Q]{
		ID:          psql.Where[Q, string](cols.ID.Expression),
		ProjectID:   psql.Where[Q, string](cols.ProjectID.Expression),
		Name:        psql.Where[Q, string](cols.Name.Expression),
		Kind:        psql.Where[Q, string](cols.Kind.Expression),
		RunnerTags:  psql.Where[Q, pq.StringArray](cols.RunnerTags.Expression),
		RequiresAck: psql.Where[Q, bool](cols.RequiresAck.Expression),
		CreatedAt:   psql.Where[Q, time.Time](cols.CreatedAt.Expression),
		UpdatedAt:   psql.Where[Q, time.Time](cols.UpdatedAt.Expression),
		RunSpec:     psql.Where[Q, types.JSON[json.RawMessage]](cols.RunSpec.Expression),
		Workflow:    psql.Where[Q, types.JSON[json.RawMessage]](cols.Workflow.Expression),
	}
}

func (o *TaskTemplate) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "TemplateTaskRuns":
		rels, ok := retrieved.(TaskRunSlice)
		if !ok {
			return fmt.Errorf("taskTemplate cannot load %T as %q", retrieved, name)
		}

		o.R.TemplateTaskRuns = rels
		o.R.Loaded.TemplateTaskRuns = true

		return nil
	case "Project":
		rel, ok := retrieved.(*Project)
		if !ok {
			return fmt.Errorf("taskTemplate cannot load %T as %q", retrieved, name)
		}

		o.R.Project = rel
		o.R.Loaded.Project = true

		return nil
	default:
		return fmt.Errorf("taskTemplate has no relationship %q", name)
	}
}

type taskTemplatePreloader struct {
	Project func(...psql.PreloadOption) psql.Preloader
}

func buildTaskTemplatePreloader() taskTemplatePreloader {
	return taskTemplatePreloader{
		Project: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Project, ProjectSlice](psql.PreloadRel{
				Name: "Project",
				Sides: []psql.PreloadSide{
					{
						From:        TaskTemplates,
						To:          Projects,
						FromColumns: []string{"project_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Projects.Columns.Names(), opts...)
		},
	}
}

type taskTemplateThenLoader[Q orm.Loadable] struct {
	TemplateTaskRuns func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Project          func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTaskTemplateThenLoader[Q orm.Loadable]() taskTemplateThenLoader[Q] {
	type TemplateTaskRunsLoadInterface interface {
		LoadTemplateTaskRuns(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ProjectLoadInterface interface {
		LoadProject(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return taskTemplateThenLoader[Q]{
		TemplateTaskRuns: thenLoadBuilder[Q](
			"TemplateTaskRuns",
			func(ctx context.Context, exec bob.Executor, retrieved TemplateTaskRunsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTemplateTaskRuns(ctx, exec, mods...)
			},
		),
		Project: thenLoadBuilder[Q](
			"Project",
			func(ctx context.Context, exec bob.Executor, retrieved ProjectLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadProject(ctx, exec, mods...)
			},
		),
	}
}

// LoadTemplateTaskRuns loads the taskTemplate's TemplateTaskRuns into the .R struct
func (o *TaskTemplate) LoadTemplateTaskRuns(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.TemplateTaskRuns = nil
	o.R.Loaded.TemplateTaskRuns = false

	related, err := o.TemplateTaskRuns(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	o.R.TemplateTaskRuns = related
	o.R.Loaded.TemplateTaskRuns = true
	return nil
}

// LoadTemplateTaskRuns loads the taskTemplate's TemplateTaskRuns into the .R struct
func (os TaskTemplateSlice) LoadTemplateTaskRuns(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	taskRuns, err := os.TemplateTaskRuns(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.TemplateTaskRuns = nil
		o.R.Loaded.TemplateTaskRuns = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range taskRuns {

			if !rel.TemplateID.Valid {
				continue
			}
			if !(rel.TemplateID.Valid && o.ID == rel.TemplateID.V) {
				continue
			}

			o.R.TemplateTaskRuns = append(o.R.TemplateTaskRuns, rel)
		}
	}

	return nil
}

// LoadProject loads the taskTemplate's Project into the .R struct
func (o *TaskTemplate) LoadProject(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Project = nil
	o.R.Loaded.Project = false

	related, err := o.Project(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R.Project = related
	o.R.Loaded.Project = true
	return nil
}

// LoadProject loads the taskTemplate's Project into the .R struct
func (os TaskTemplateSlice) LoadProject(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	projects, err := os.Project(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Project = nil
		o.R.Loaded.Project = true
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range projects {

			if !(o.ProjectID == rel.ID) {
				continue
			}

			o.R.Project = rel
			break
		}
	}

	return nil
}

// taskTemplateC is where relationship counts are stored.
type taskTemplateC struct {
	TemplateTaskRuns *int64 `json:"TemplateTaskRuns"`
}

// PreloadCount sets a count in the C struct by name
func (o *TaskTemplate) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "TemplateTaskRuns":
		o.C.TemplateTaskRuns = &count
	}
	return nil
}

type taskTemplateCountPreloader struct {
	TemplateTaskRuns func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildTaskTemplateCountPreloader() taskTemplateCountPreloader {
	return taskTemplateCountPreloader{
		TemplateTaskRuns: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*TaskTemplate]("TemplateTaskRuns", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = TaskTemplates.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(TaskRuns.NameAsExpr()),
					sm.Where(psql.Quote(TaskRuns.Alias(), "template_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type taskTemplateCountThenLoader[Q orm.Loadable] struct {
	TemplateTaskRuns func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTaskTemplateCountThenLoader[Q orm.Loadable]() taskTemplateCountThenLoader[Q] {
	type TemplateTaskRunsCountInterface interface {
		LoadCountTemplateTaskRuns(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return taskTemplateCountThenLoader[Q]{
		TemplateTaskRuns: countThenLoadBuilder[Q](
			"TemplateTaskRuns",
			func(ctx context.Context, exec bob.Executor, retrieved TemplateTaskRunsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTemplateTaskRuns(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountTemplateTaskRuns loads the count of TemplateTaskRuns into the C struct
func (o *TaskTemplate) LoadCountTemplateTaskRuns(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.TemplateTaskRuns(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.TemplateTaskRuns = &count
	return nil
}

// LoadCountTemplateTaskRuns loads the count of TemplateTaskRuns for a slice in a single batch query
func (os TaskTemplateSlice) LoadCountTemplateTaskRuns(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	// Build the IN arg expression from parent PKs

	pkID := make(pgtypes.Array[string], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "text[]")),
	))

	// countResult holds one scanned row from the batch count query.
	// FK columns are aliased to the parent PK column names for direct map lookup.
	type countResult struct {
		ID    string
		Count int64
	}

	batchMods := []bob.Mod[*dialect.SelectQuery]{
		// SELECT fk AS parent_pk, count(*)
		sm.Columns(
			TaskRuns.Columns.TemplateID.As("id"),
			psql.Raw("count(*) as count"),
		),
		// Single-hop: FROM related table directly
		sm.From(TaskRuns.NameAsExpr()),

		// WHERE fk IN (parent PKs)
		sm.Where(TaskRuns.Columns.TemplateID.OP("IN", PKArgExpr)),
		// GROUP BY fk columns
		sm.GroupBy(TaskRuns.Columns.TemplateID),
	}
	batchMods = append(batchMods, mods...)

	results, err := bob.All(ctx, exec,
		psql.Select(batchMods...),
		scan.StructMapper[countResult](),
	)
	if err != nil {
		return err
	}

	// Single-column FK: direct map lookup
	countMap := make(map[string]int64, len(results))
	for _, r := range results {
		countMap[r.ID] = r.Count
	}
	for _, o := range os {
		if o == nil {
			continue
		}
		count := countMap[o.ID]
		o.C.TemplateTaskRuns = &count
	}

	return nil
}

type taskTemplateJoins[Q dialect.Joinable] struct {
	typ              string
	TemplateTaskRuns modAs[Q, taskRunColumns]
	Project          modAs[Q, projectColumns]
}

func (j taskTemplateJoins[Q]) aliasedAs(alias string) taskTemplateJoins[Q] {
	return buildTaskTemplateJoins[Q](buildTaskTemplateColumns(alias), j.typ)
}

func buildTaskTemplateJoins[Q dialect.Joinable](cols taskTemplateColumns, typ string) taskTemplateJoins[Q] {
	return taskTemplateJoins[Q]{
		typ: typ,
		TemplateTaskRuns: modAs[Q, taskRunColumns]{
			c: TaskRuns.Columns,
			f: func(to taskRunColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, TaskRuns.NameExpr().As(to.Alias())).On(
						to.TemplateID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Project: modAs[Q, projectColumns]{
			c: Projects.Columns,
			f: func(to projectColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Projects.NameExpr().As(to.Alias())).On(
						to.ID.EQ(cols.ProjectID),
					))
				}

				return mods
			},
		},
	}
}
