#!/usr/bin/env bash
# Real, isolated provenance/replay gate. It resolves only: no target Compose
# project is ever applied by the runner or this harness.
set -Eeuo pipefail
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
file="$root/acceptance/runtime-provenance/compose.yaml"
evidence=/tmp/nerocd-provenance-runtime.txt
dir=$(mktemp -d /tmp/nerocd-runtime-provenance.XXXXXXXX)
suffix=$(od -An -N6 -tx1 /dev/urandom | tr -d ' \n')
project="nerocd-provenance-$suffix" image="nerocd-runtime-provenance:$suffix" resolver="nerocd-provenance-resolver:$suffix" gitimg="nerocd-provenance-git:$suffix" pass=false
: >"$evidence"; record(){ printf '%s\n' "$*" >>"$evidence"; }; fail(){ trap - ERR; record "FAIL: $*"; printf 'runtime-provenance: %s\n' "$*" >&2; exit 1; }
compose(){ NEROCD_RUNTIME_IMAGE="$image" NEROCD_RESOLVER_IMAGE="$resolver" NEROCD_GIT_FIXTURE_IMAGE="$gitimg" docker compose -p "$project" -f "$file" "$@"; }
diagnose(){ set +e; record 'diagnostic_begin=true'; record "runner_status=$(compose ps --format json runner 2>/dev/null | jq -c '{State:.State,ExitCode:.ExitCode,Health:.Health}' 2>/dev/null || echo unavailable)"; record "proxy_status=$(curl -fsS "${control:-}/status" 2>/dev/null | jq -c '{lost_provenance_responses,held_provenance_requests,requests,trace}' 2>/dev/null | sed -E 's/(Bearer |fence|PRIVATE KEY)[^ ,"]*/[REDACTED]/g' || echo unavailable)"; compose logs --no-color runner server proxy git 2>/dev/null | sed -E 's/(Bearer |fence|BEGIN [A-Z ]*PRIVATE KEY|ssh:\/\/)[^[:space:]]*/[REDACTED]/g' | tail -n 120 >>"$evidence"; if [[ -n ${jvol:-} ]]; then docker run --rm --network none -v "$jvol:/j:ro" "$gitimg" sh -ec 'find /j -maxdepth 1 -printf "%f|%m|%s\n"' 2>/dev/null | sed -E 's/(token|key|secret|fence)/[REDACTED]/Ig' >>"$evidence"; fi; compose exec -T postgres psql -U nerocd -d nerocd -Atc "select 'deployments='||count(*) from deployments union all select 'leases='||count(*) from run_leases union all select 'attempts='||count(*) from deployment_attempts union all select 'provenance='||count(*) from provenance_resolutions union all select 'secret_audit='||count(*) from audit_events where action='secret.access'" 2>/dev/null >>"$evidence" || true; record 'diagnostic_end=true'; }
cleanup(){ local code=$? ids rem=''; trap - ERR; set +e; if [[ "$pass" != true ]]; then diagnose; fi; compose down --volumes --remove-orphans --rmi local --timeout 4 >/dev/null 2>&1 || true; ids=$(docker ps -aq --filter "label=com.docker.compose.project=$project"); [[ -z "$ids" ]] || docker rm -f $ids >/dev/null 2>&1 || true; ids=$(docker volume ls -q --filter "label=com.docker.compose.project=$project"); [[ -z "$ids" ]] || docker volume rm $ids >/dev/null 2>&1 || true; ids=$(docker network ls -q --filter "label=com.docker.compose.project=$project"); [[ -z "$ids" ]] || docker network rm $ids >/dev/null 2>&1 || true; docker image rm -f "$image" "$resolver" "$gitimg" >/dev/null 2>&1 || true; rem=$(docker ps -aq --filter "label=com.docker.compose.project=$project"; docker volume ls -q --filter "label=com.docker.compose.project=$project"; docker network ls -q --filter "label=com.docker.compose.project=$project"); if [[ -n "$rem" ]]; then code=1; fi; record "cleanup_complete=$([[ -z "$rem" ]] && echo true || echo false)"; if [[ "$pass" == true && $code -eq 0 ]]; then record 'PASS: durable provenance replay with real SSH resolver'; fi; rm -rf -- "$dir"; printf 'runtime provenance evidence: %s\n' "$evidence"; exit "$code"; }
trap cleanup EXIT; trap 'fail "unexpected command failure line $LINENO"' ERR
for x in docker curl jq od; do command -v "$x" >/dev/null || fail "missing $x"; done; docker info >/dev/null || fail 'Docker unavailable'
record "source_commit=$(git -C "$root" rev-parse HEAD)"; record "project=$project"; record "docker=$(docker version --format '{{.Server.Version}}')"; record "compose=$(docker compose version --short)"
docker build --pull -t "$image" "$root" >"$dir/build.log" 2>&1 || fail 'fresh image build failed'; docker build --pull -f "$root/acceptance/runtime-provenance/GitDockerfile" -t "$gitimg" "$root/acceptance/runtime-provenance" >"$dir/git-build.log" 2>&1 || fail 'pinned git fixture image build failed'; record "image=$(docker image inspect -f '{{.Id}}' "$image") git_image=$(docker image inspect -f '{{.Id}}' "$gitimg")"
compose run --rm --no-deps git_init >"$dir/git-init.log" 2>&1 || fail 'git fixture init failed'
compose up -d --wait postgres server proxy git >"$dir/up.log" 2>&1 || fail 'stack failed'
server_port=$(compose port server 8080 | tail -1); server_port=${server_port##*:}; proxy_port=$(compose port proxy 8081 | tail -1); proxy_port=${proxy_port##*:}; base="http://127.0.0.1:$server_port"; control="http://127.0.0.1:$proxy_port/__control"; gitvol=$(docker volume ls -q --filter label=com.docker.compose.project=$project --filter label=com.docker.compose.volume=git-data | head -1); secretvol=$(docker volume ls -q --filter label=com.docker.compose.project=$project --filter label=com.docker.compose.volume=runner-secrets | head -1); if ! docker run --rm --network "${project}_runtime" -v "$gitvol:/git:ro" -v "$secretvol:/secrets:ro" "$gitimg" sh -ec 'command -v ssh ssh-keyscan sshd git; sshd -t -f /git/sshd_config; sshd -T -f /git/sshd_config | grep -qx "passwordauthentication no"; ssh-keyscan -T 5 -p 2222 git >/tmp/known; GIT_SSH_COMMAND="ssh -o BatchMode=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/tmp/known -i /secrets/root/cred_git_deploy -p 2222" git ls-remote ssh://git@git:2222/repo.git >/dev/null' >"$dir/ssh-preflight.log" 2>&1; then record "ssh_preflight_error=$(sed -E 's#(ssh://|git@|/secrets/[^ ]+|Bearer [^ ]+|fence[^ ]*)#[REDACTED]#Ig' "$dir/ssh-preflight.log" | tail -20 | tr '\n' ' ')"; fail 'key-only SSH preflight failed'; fi; ! docker run --rm --network "${project}_runtime" -v "$gitvol:/git:ro" "$gitimg" sh -ec 'ssh-keyscan -T 5 -p 2222 git >/tmp/known; ssh -o BatchMode=yes -o PreferredAuthentications=password -o PasswordAuthentication=yes -o KbdInteractiveAuthentication=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/tmp/known -p 2222 git@git true' >/dev/null 2>&1 || fail 'SSH accepted missing/password credential'; record 'ssh_preflight=publickey_only'
http(){ local method=$1 url=$2 token=$3 body=$4 out=$5; local -a args=(-sS --max-time 10 -o "$out" -w '%{http_code}' -X "$method" -H 'Content-Type: application/json'); [[ -n "$token" ]] && args+=(-H "Authorization: Bearer $token"); args+=(--data "$body" "$url"); curl "${args[@]}"; }
code=$(http POST "$base/api/v1/sessions" '' '{"email":"admin@example.local","password":"admin"}' "$dir/session.json"); [[ $code == 201 ]] || fail 'admin session'; admin=$(jq -er .token "$dir/session.json")
code=$(http POST "$base/api/v1/runners/register" "$admin" '{"id":"runner_provenance","name":"runner_provenance","tags":["provenance-runtime"],"capabilities":["compose-deploy"]}' "$dir/runner.json"); [[ $code == 201 ]] || fail 'runner registration'; token=$(jq -er .token "$dir/runner.json")
printf '%s\n' "$token" | compose run --rm --no-deps credential_init >"$dir/credential.log" 2>&1 || fail 'credential init'
git_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$(compose ps -q git)"); gitvol=$(docker volume ls -q --filter label=com.docker.compose.project=$project --filter label=com.docker.compose.volume=git-data | head -1); fp=$(docker run --rm --network none -v "$gitvol:/git:ro" "$gitimg" sh -c 'ssh-keygen -lf /git/keys/host.pub' | awk '{print $2}')
repo_body=$(jq -cn '{project_id:"proj_platform",name:"runtime-provenance",url:"ssh://git@git:2222/git/repo.git",provider:"git",default_ref:"main"}'); code=$(http POST "$base/api/v1/repositories" "$admin" "$repo_body" "$dir/repo.json"); [[ $code == 201 ]] || fail 'repository create'; repo=$(jq -er .id "$dir/repo.json")
policy=$(jq -cn --arg host git --arg cidr "$git_ip/32" --arg fp "$fp" '{project_id:"proj_platform",configuration_id:"cfg_provenance_a",policy:{version:1,state:"configured",mode:"internal",allowed_schemes:["ssh"],allowed_hosts:[$host],allowed_cidrs:[$cidr],ssh_host_fingerprints:[$fp],credential_reference_id:"cred_git_deploy",allow_internal:true}}'); code=$(http PUT "$base/api/v1/repositories/$repo/policy" "$admin" "$policy" "$dir/policy.json"); [[ $code == 200 ]] || { record "policy_status=$code policy_error=$(jq -r '.error // "unknown"' "$dir/policy.json")"; fail 'repository policy configure'; }
service=$(jq -cn --arg repo "$repo" '{project_id:"proj_platform",name:"runtime-provenance",repository_id:$repo,compose_path:"compose.yaml"}'); code=$(http POST "$base/api/v1/services" "$admin" "$service" "$dir/service.json"); [[ $code == 201 ]] || { record "service_status=$code service_error=$(jq -r '.error // "unknown"' "$dir/service.json")"; fail 'service create'; }; svc=$(jq -er .id "$dir/service.json")
env=$(jq -cn --arg svc "$svc" '{service_id:$svc,name:"runtime",runner_selector:["provenance-runtime"],compose_project:"must-not-exist",timeout_seconds:60,rollback_safe:true,secret_bindings:[{name:"git",provider:"runner_file",reference:"cred_git_deploy",target:"env:GIT_SSH_KEY",required:true,version:"v1",fingerprint:"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}]}'); code=$(http POST "$base/api/v1/environments" "$admin" "$env" "$dir/env.json"); [[ $code == 201 ]] || fail 'environment create'; env_id=$(jq -er .id "$dir/env.json"); compose up -d runner >"$dir/runner-ready.log" 2>&1 || fail 'runner start'; runner_cid=$(compose ps -q runner); [[ -n "$runner_cid" ]] || fail 'runner container missing'; sleep 2
# This is intentionally inside the running, non-root resolver image with the
# exact mounted runner workspace and secret volume. The earlier sidecar check
# proves fixture setup; this one proves the actual GIT_SSH_COMMAND shape and
# toolchain before a deployment is claimable.
if ! compose exec -T -e NEROCD_GIT_IP="$git_ip" runner sh -ec '
  set -eu
  command -v git ssh ssh-keyscan docker
  git --version; ssh -V 2>&1; docker compose version
  work=/workspace/.nerocd-runtime-provenance-preflight
  rm -rf -- "$work"; mkdir -m 700 "$work"
  trap "rm -rf -- \"$work\"" EXIT
  ssh-keyscan -T 5 -p 2222 "$NEROCD_GIT_IP" >"$work/scan" 2>/dev/null
  awk "NF == 3 { \$1=\"git\"; print }" "$work/scan" >"$work/known_hosts"
  test -s "$work/known_hosts"; test -r /secrets/root/cred_git_deploy
  export GIT_SSH_COMMAND="ssh -F /dev/null -o BatchMode=yes -o PreferredAuthentications=publickey -o PubkeyAuthentication=yes -o PasswordAuthentication=no -o KbdInteractiveAuthentication=no -o ChallengeResponseAuthentication=no -o IdentitiesOnly=yes -o IdentityAgent=none -o StrictHostKeyChecking=yes -o UserKnownHostsFile=$work/known_hosts -o GlobalKnownHostsFile=/dev/null -o HostKeyAlias=git -o HostName=$NEROCD_GIT_IP -o Port=2222 -i /secrets/root/cred_git_deploy"
  base="-c core.hooksPath=/dev/null -c protocol.file.allow=never -c protocol.ext.allow=never -c credential.helper= -c http.followRedirects=false"
  env -i PATH="$PATH" HOME="$work" LANG=C LC_ALL=C GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL=/dev/null GIT_TERMINAL_PROMPT=0 GIT_ASKPASS=/bin/false GIT_ALLOW_PROTOCOL=https:http:ssh GIT_SSH_COMMAND="$GIT_SSH_COMMAND" git $base init --quiet "$work/checkout"
  cd "$work/checkout"
  env -i PATH="$PATH" HOME="$work" LANG=C LC_ALL=C GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL=/dev/null GIT_TERMINAL_PROMPT=0 GIT_ASKPASS=/bin/false GIT_ALLOW_PROTOCOL=https:http:ssh GIT_SSH_COMMAND="$GIT_SSH_COMMAND" git $base remote add origin ssh://git@git:2222/git/repo.git
  env -i PATH="$PATH" HOME="$work" LANG=C LC_ALL=C GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL=/dev/null GIT_TERMINAL_PROMPT=0 GIT_ASKPASS=/bin/false GIT_ALLOW_PROTOCOL=https:http:ssh GIT_SSH_COMMAND="$GIT_SSH_COMMAND" git $base fetch --no-tags --depth=1 origin main
  env -i PATH="$PATH" HOME="$work" LANG=C LC_ALL=C GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL=/dev/null GIT_TERMINAL_PROMPT=0 GIT_ASKPASS=/bin/false GIT_ALLOW_PROTOCOL=https:http:ssh GIT_SSH_COMMAND="$GIT_SSH_COMMAND" git $base checkout --detach --quiet FETCH_HEAD
  : > "$work/empty.env"
  env -i PATH="$PATH" HOME="$work" LANG=C LC_ALL=C GIT_CONFIG_NOSYSTEM=1 GIT_CONFIG_GLOBAL=/dev/null GIT_TERMINAL_PROMPT=0 GIT_ASKPASS=/bin/false GIT_ALLOW_PROTOCOL=ssh GIT_SSH_COMMAND="$GIT_SSH_COMMAND" docker compose --project-name must-not-exist --env-file "$work/empty.env" --file compose.yaml config --format json >/dev/null
' >"$dir/runner-preflight.log" 2>&1; then record "runner_preflight_error=$(sed -E 's#(ssh://|git@|/secrets/[^ ]+|Bearer [^ ]+|fence[^ ]*)#[REDACTED]#Ig' "$dir/runner-preflight.log" | tail -20 | tr '\n' ' ')"; fail 'actual runner resolver preflight failed'; fi
record 'runner_preflight=actual_uid_tools_ssh_fetch_compose_config'
docker pause "$runner_cid" >/dev/null || fail 'runner pause before deployment A'
resolve(){ local label=$1 target_env=${2:-$env_id}; code=$(http POST "$base/api/v1/revisions" "$admin" "$(jq -cn --arg s "$svc" '{service_id:$s,requested_ref:"main"}')" "$dir/rev-$label.json"); [[ $code == 201 ]] || { record "revision_status=$code revision_error=$(jq -r '.error // "unknown"' "$dir/rev-$label.json")"; fail "revision $label"; }; rev=$(jq -er .id "$dir/rev-$label.json"); code=$(http POST "$base/api/v1/deployments" "$admin" "$(jq -cn --arg e "$target_env" --arg r "$rev" --arg k "runtime-$label" '{environment_id:$e,desired_revision_id:$r,idempotency_key:$k}')" "$dir/deploy-$label.json"); [[ $code == 201 ]] || { record "deployment_status=$code deployment_error=$(jq -r '.error // "unknown"' "$dir/deploy-$label.json")"; fail "deployment $label"; }; echo "$rev"; }
curl -fsS -X POST "$control/provenance-hold/on" >/dev/null; curl -fsS -X POST "$control/drop-provenance" >/dev/null; proxy_before=$(curl -fsS "$control/status"); rev_a=$(resolve a); docker unpause "$runner_cid" >/dev/null || fail 'runner unpause for deployment A'
jvol=$(docker volume ls -q --filter label=com.docker.compose.project=$project --filter label=com.docker.compose.volume=runner-journal | head -1); [[ -n "$jvol" ]] || fail 'journal volume missing'; deadline=$((SECONDS+45)); held=false; while ((SECONDS<deadline)); do state=$(curl -fsS "$control/status" || true); if [[ $(jq -r .held_provenance_requests <<<"$state") -ge 1 ]]; then held=true; break; fi; sleep .25; done; [[ "$held" == true ]] || fail 'runner did not journal and reach held provenance request'; journal_exists=false; deadline=$((SECONDS+10)); while ((SECONDS<deadline)); do if docker run --rm --network none -v "$jvol:/j:ro" "$gitimg" sh -ec 'test -f /j/journal.json'; then journal_exists=true; break; fi; sleep .25; done; [[ "$journal_exists" == true ]] || fail 'journal.json was not created before provenance send'; docker run --rm --network none -v "$jvol:/j:ro" "$gitimg" cat /j/journal.json >"$dir/journal-pending.json"; jq -e '(.provenance|length)==1' "$dir/journal-pending.json" >/dev/null || fail 'journal did not contain exactly one pending provenance record'; curl -fsS -X POST "$control/provenance-hold/off" >/dev/null
compose stop runner >/dev/null; before=$(sha256sum "$dir/journal-pending.json" | awk '{print $1}'); compose up -d runner >/dev/null; deadline=$((SECONDS+60)); replayed=false; state=''; while ((SECONDS<deadline)); do state=$(curl -fsS "$control/status" || true); pending_count=$(docker run --rm --network none -v "$jvol:/j:ro" "$gitimg" sh -ec 'test -f /j/journal.json && grep -c "\"id\"" /j/journal.json || true'); if [[ $(jq -r .lost_provenance_responses <<<"$state") == 1 && $(jq -r '.requests["/api/v1/runners/deployments/provenance"] // 0' <<<"$state") -ge 2 && "$pending_count" == 0 ]]; then replayed=true; break; fi; sleep .5; done; [[ "$replayed" == true ]] || fail 'lost provenance response did not replay and drain before deadline'; trace=$(jq -r '.trace[]' <<<"$state"); lost_line=$(grep -n 'committed-response-lost:provenance' <<<"$trace" | head -1 | cut -d: -f1); replay_line=$(grep -n 'response:/api/v1/runners/deployments/provenance:200' <<<"$trace" | tail -1 | cut -d: -f1); [[ -n "$lost_line" && -n "$replay_line" && "$replay_line" -gt "$lost_line" ]] || fail 'proxy trace lacks ordered second provenance replay'; between_lost_and_replay=$(sed -n "$((lost_line+1)),$((replay_line-1))p" <<<"$trace"); ! grep -Eq 'response:/api/v1/runners/(heartbeat|claim):' <<<"$between_lost_and_replay" || fail 'heartbeat or claim occurred before replay reconciliation'; record "replay_posts=$(jq -r '.requests["/api/v1/runners/deployments/provenance"]' <<<"$state") ordered_before_heartbeat_claim=true journal_pending=0"
row=$(compose exec -T postgres psql -U nerocd -d nerocd -Atc "select git_commit,compose_hash,array_to_string(image_digests,','),content_identity,provenance_state from revisions where id='$rev_a'"); origin_a=$(docker run --rm --network none -v "$gitvol:/git:ro" "$gitimg" sh -ec 'git --git-dir=/git/repo.git rev-parse refs/heads/main'); [[ "$origin_a" =~ ^[0-9a-f]{40,64}$ ]] || fail 'origin A is not a full commit'; IFS='|' read -r a_commit a_hash a_digests a_identity a_state <<<"$row"; [[ "$a_commit" == "$origin_a" && "$a_hash" =~ ^sha256:[0-9a-f]{64}$ && "$a_digests" =~ ^[a-z0-9][a-z0-9._/:@-]*@sha256:[0-9a-f]{64}(,[a-z0-9][a-z0-9._/:@-]*@sha256:[0-9a-f]{64})*$ && "$a_identity" == "$a_commit:$a_hash" && "$a_state" == resolved ]] || fail 'A provenance was not canonical exact evidence'; a_receipts=$(compose exec -T postgres psql -U nerocd -d nerocd -Atc "select count(*) from provenance_resolutions where revision_id='$rev_a'"); a_audits=$(compose exec -T postgres psql -U nerocd -d nerocd -Atc "select count(*) from audit_events where target_id=(select id from deployments where desired_revision_id='$rev_a') and action='runner.deployment.provenance.resolve'"); [[ "$a_receipts" == 1 && "$a_audits" == 1 ]] || fail 'A replay did not converge to one receipt/audit'; record "A=$row receipt=$a_receipts audit=$a_audits journal_before=$before"
origin_b=$(compose run --rm --no-deps git_advance | tail -1); [[ "$origin_b" =~ ^[0-9a-f]{40,64}$ && "$origin_a" != "$origin_b" ]] || fail 'fixture A/B refs are not distinct full commits'; record "fixture_A=$origin_a fixture_B=$origin_b"
env_b=$(jq -cn --arg svc "$svc" '{service_id:$svc,name:"runtime-b",runner_selector:["provenance-runtime"],compose_project:"must-not-exist-b",timeout_seconds:60,rollback_safe:true,secret_bindings:[{name:"git",provider:"runner_file",reference:"cred_git_deploy",target:"env:GIT_SSH_KEY",required:true,version:"v1",fingerprint:"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}]}'); code=$(http POST "$base/api/v1/environments" "$admin" "$env_b" "$dir/env-b.json"); [[ $code == 201 ]] || fail 'environment B create'; env_b_id=$(jq -er .id "$dir/env-b.json")
rev_b=$(resolve b "$env_b_id"); deadline=$((SECONDS+60)); while ((SECONDS<deadline)); do b=$(compose exec -T postgres psql -U nerocd -d nerocd -Atc "select provenance_state from revisions where id='$rev_b'"); [[ $b == resolved ]] && break || true; sleep .5; done; [[ $b == resolved ]] || fail 'B did not resolve'; b_row=$(compose exec -T postgres psql -U nerocd -d nerocd -Atc "select git_commit,compose_hash,array_to_string(image_digests,','),content_identity,provenance_state from revisions where id='$rev_b'"); IFS='|' read -r b_commit b_hash b_digests b_identity b_state <<<"$b_row"; [[ "$b_commit" == "$origin_b" && "$b_commit" != "$a_commit" && "$b_hash" =~ ^sha256:[0-9a-f]{64}$ && "$b_digests" =~ ^[a-z0-9][a-z0-9._/:@-]*@sha256:[0-9a-f]{64}(,[a-z0-9][a-z0-9._/:@-]*@sha256:[0-9a-f]{64})*$ && "$b_identity" == "$b_commit:$b_hash" && "$b_state" == resolved ]] || fail 'B provenance was not canonical exact evidence'; a_after=$(compose exec -T postgres psql -U nerocd -d nerocd -Atc "select git_commit,compose_hash,array_to_string(image_digests,','),content_identity,provenance_state from revisions where id='$rev_a'"); [[ "$a_after" == "$row" ]] || fail 'A provenance changed after main advanced'; b_receipts=$(compose exec -T postgres psql -U nerocd -d nerocd -Atc "select count(*) from provenance_resolutions where revision_id='$rev_b'"); b_audits=$(compose exec -T postgres psql -U nerocd -d nerocd -Atc "select count(*) from audit_events where target_id=(select id from deployments where desired_revision_id='$rev_b') and action='runner.deployment.provenance.resolve'"); [[ "$b_receipts" == 1 && "$b_audits" == 1 ]] || fail 'B did not converge to one receipt/audit'; record "A_immutable=$a_after B=$b_row receipt=$b_receipts audit=$b_audits"
compose logs --no-color >"$dir/logs.txt" || true; ! grep -Eiq 'BEGIN (OPENSSH|RSA|EC|DSA) PRIVATE KEY|Bearer [A-Za-z0-9._-]+|runner_provenance.*token' "$dir/logs.txt" "$dir/journal-pending.json" || fail 'secret disclosure scan'
record 'target_compose_mutation=none; compose up/down is intentionally outside resolver'; pass=true
