import { type FormEvent, type ReactNode, useRef, useState } from "react";
import { Activity, ArchiveRestore, Database, HeartPulse, ListRestart, ShieldAlert } from "lucide-react";
import type { OperationsStatus, RunLogRetentionExecution, RunLogRetentionStatus } from "@/api";
import { MetricCard } from "@/components/common/MetricCard";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

function seconds(value: number | undefined): string {
  if (!Number.isFinite(value) || value === undefined) return "—";
  if (value < 60) return `${Math.round(value)}s`;
  return `${Math.round(value / 60)}m`;
}

export function OperationsView({ status, loading, unavailable, canAdmin, retention, retentionLoading, retentionUnavailable, retentionBusy, retentionExecution, onRetentionUpdate, onRetentionExecute }: { status?: OperationsStatus; loading: boolean; unavailable: boolean; canAdmin: boolean; retention?: RunLogRetentionStatus; retentionLoading?: boolean; retentionUnavailable?: boolean; retentionBusy?: boolean; retentionExecution?: RunLogRetentionExecution; onRetentionUpdate?: (input: { enabled: boolean; keep_days: number; batch_size: number }) => void; onRetentionExecute?: (policyVersion: number, requestID: string) => void }): ReactNode {
  if (!canAdmin) return <Card><CardContent className="p-6" role="alert">System Operations is restricted to global administrators.</CardContent></Card>;
  if (loading) return <Card><CardContent className="p-6" role="status">Loading authoritative operations status…</CardContent></Card>;
  if (unavailable || !status) return <Card className="border-warning/30"><CardContent className="p-6" role="alert"><div className="flex gap-2"><ShieldAlert className="mt-0.5 h-5 w-5 text-warning" /><div><p className="font-medium">Operations status is temporarily unavailable</p><p className="mt-1 text-sm text-muted-foreground">No partial operational snapshot is shown. Check readiness and retry after the database and schema are healthy.</p></div></div></CardContent></Card>;
  const snapshot = status.snapshot;
  const activeDeployments = (snapshot.deployments.applying ?? 0) + (snapshot.deployments.verifying ?? 0) + (snapshot.deployments.rolling_back ?? 0);
  return <section className="space-y-6" aria-label="System Operations status" aria-live="polite">
    <div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-semibold">System Operations</h2><p className="text-sm text-muted-foreground">Authoritative PostgreSQL snapshot. Refreshes while this page is visible.</p></div><span className="rounded-full bg-success/10 px-3 py-1 text-sm font-medium text-success">Ready</span></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <MetricCard label="Queued work" value={snapshot.queue_depth} caption={`Oldest ${seconds(snapshot.queue_oldest_age_seconds)}`} icon={ListRestart} tone={snapshot.queue_depth > 0 ? "warning" : "neutral"} />
      <MetricCard label="Active leases" value={snapshot.active_leases} caption={`${snapshot.expired_leases} expired lease${snapshot.expired_leases === 1 ? "" : "s"}`} icon={Activity} tone={snapshot.expired_leases > 0 ? "warning" : "success"} />
      <MetricCard label="Runner heartbeat" value={seconds(snapshot.oldest_runner_heartbeat_seconds)} caption={`Journal depth ${snapshot.runner_journal_depth}`} icon={HeartPulse} tone={snapshot.oldest_runner_heartbeat_seconds > 120 ? "warning" : "success"} />
      <MetricCard label="Backup" value={snapshot.backup_outcome} caption={snapshot.backup_schedule_status === "disabled" ? "Local schedule disabled" : `${snapshot.backup_schedule_status}; next ${seconds(snapshot.backup_schedule_next_seconds)}`} icon={ArchiveRestore} tone={snapshot.backup_outcome === "failure" || snapshot.backup_schedule_status === "backoff" ? "warning" : snapshot.backup_outcome === "success" ? "success" : "neutral"} />
    </div>
    <div className="grid gap-4 lg:grid-cols-2">
      <Card><CardHeader><CardTitle>Deployments</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p><strong>{activeDeployments}</strong> active apply, verify, or rollback operation{activeDeployments === 1 ? "" : "s"}.</p><p className="text-muted-foreground">Health: {snapshot.deployment_health_passed} passed · {snapshot.deployment_health_failed} failed</p><p className="text-muted-foreground">Rollbacks: {snapshot.rollback_succeeded} succeeded · {snapshot.rollback_failed} failed</p></CardContent></Card>
      <Card><CardHeader><CardTitle>Database and runner telemetry</CardTitle></CardHeader><CardContent className="space-y-2 text-sm"><p><strong>{snapshot.pool.acquired}</strong> PostgreSQL connections acquired of {snapshot.pool.total}; {snapshot.pool.idle} idle.</p><p className="text-muted-foreground">Runner retries: {snapshot.runner_retry_count} · renewal failures: {snapshot.runner_renew_failures}</p><p className="text-muted-foreground">Backup schedule: {snapshot.backup_schedule_status} · {snapshot.backup_schedule_failures} consecutive failure{snapshot.backup_schedule_failures === 1 ? "" : "s"}</p><p className="text-muted-foreground">Backup reason: {snapshot.backup_reason}</p></CardContent></Card>
    </div>
    <RunLogRetentionCard status={retention} loading={retentionLoading} unavailable={retentionUnavailable} busy={retentionBusy} execution={retentionExecution} onUpdate={onRetentionUpdate} onExecute={onRetentionExecute} />
    <Card><CardHeader><CardTitle>Operator response</CardTitle></CardHeader><CardContent className="text-sm text-muted-foreground"><p>Investigate an increasing queue age, expired leases, stale runner heartbeats, failed deployment health, or failed backups. The page intentionally omits raw metrics, identifiers, paths, and diagnostic payloads; use the protected operational runbook and audited resources for follow-up.</p></CardContent></Card>
  </section>;
}

function RunLogRetentionCard({ status, loading, unavailable, busy, execution, onUpdate, onExecute }: { status?: RunLogRetentionStatus; loading?: boolean; unavailable?: boolean; busy?: boolean; execution?: RunLogRetentionExecution; onUpdate?: (input: { enabled: boolean; keep_days: number; batch_size: number }) => void; onExecute?: (policyVersion: number, requestID: string) => void }): ReactNode {
  const [confirming, setConfirming] = useState(false);
  const requestID = useRef<string>("");
  const policy = status?.policy;
  const preview = status?.preview;
  if (loading) return <Card><CardHeader><CardTitle>Run-log retention</CardTitle></CardHeader><CardContent role="status">Loading retention policy…</CardContent></Card>;
  if (unavailable || !policy || !preview) return <Card><CardHeader><CardTitle>Run-log retention</CardTitle></CardHeader><CardContent role="alert">Retention controls are unavailable. No deletion can be requested until the authoritative policy is available.</CardContent></Card>;
  const update = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); onUpdate?.({ enabled: form.get("enabled") === "on", keep_days: Number(form.get("keep_days")), batch_size: Number(form.get("batch_size")) }); };
  const openConfirm = () => { requestID.current = crypto.randomUUID(); setConfirming(true); };
  return <Card><CardHeader><CardTitle>Manual run-log retention</CardTitle></CardHeader><CardContent className="grid gap-4"><p className="text-sm text-muted-foreground">Only terminal-run logs older than the policy cutoff and without an active lease are eligible. Artifacts, audit evidence, deployments, and runs are never removed.</p><dl className="grid gap-1 text-sm sm:grid-cols-3"><div><dt className="text-muted-foreground">Eligible logs</dt><dd>{preview.eligible_logs}</dd></div><div><dt className="text-muted-foreground">Eligible bytes</dt><dd>{preview.eligible_bytes}</dd></div><div><dt className="text-muted-foreground">Cutoff</dt><dd><time dateTime={preview.cutoff}>{new Date(preview.cutoff).toLocaleString()}</time></dd></div></dl><form className="grid gap-3 sm:grid-cols-3" aria-label="Run-log retention policy" onSubmit={update}><label className="flex items-center gap-2 text-sm"><input name="enabled" type="checkbox" defaultChecked={policy.enabled} /> Enable manual retention</label><label className="grid gap-1 text-sm">Keep days<Input name="keep_days" type="number" min={1} max={3650} defaultValue={policy.keep_days} required /></label><label className="grid gap-1 text-sm">Batch size<Input name="batch_size" type="number" min={1} max={10000} defaultValue={policy.batch_size} required /></label><div className="sm:col-span-3 flex flex-wrap gap-2"><Button type="submit" variant="outline" disabled={busy}>Save policy</Button><Button type="button" disabled={!policy.enabled || busy} onClick={openConfirm}>Previewed delete batch</Button></div></form>{execution ? <p className="rounded border p-3 text-sm" role="status">Execution receipt: deleted {execution.deleted} logs ({execution.deleted_bytes} bytes). Aggregate result only.</p> : null}<Dialog open={confirming} onOpenChange={setConfirming}><DialogContent><DialogHeader><DialogTitle>Execute one retention batch?</DialogTitle><DialogDescription>This is a bounded, audited deletion of up to {policy.batch_size} eligible terminal-run log records. The request is idempotent; it cannot delete artifacts, audit records, deployments, or runs.</DialogDescription></DialogHeader><dl className="grid gap-1 text-sm"><div>Eligible logs: {preview.eligible_logs}</div><div>Eligible bytes: {preview.eligible_bytes}</div><div>Cutoff: {new Date(preview.cutoff).toLocaleString()}</div></dl><DialogFooter><Button variant="outline" onClick={() => setConfirming(false)}>Cancel</Button><Button disabled={busy} onClick={() => { onExecute?.(policy.version, requestID.current); setConfirming(false); }}>Execute retained batch</Button></DialogFooter></DialogContent></Dialog></CardContent></Card>;
}
