import { type FormEvent, type ReactNode, useState } from "react";
import { Archive, FolderKanban, GitBranch, Pencil, Plus } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import type { Project, Repository } from "@/api";
import { EmptyState } from "@/components/common/EmptyState";
import { SkeletonCard } from "@/components/common/SkeletonCard";
import { formatDate } from "@/lib/format";
import { matchesQuery } from "@/lib/format";
export function ProjectsView({ projects, repositories, q, loading, projectBusyID, repositoryBusy, onCreateProject, onUpdateProject, onArchiveProject, onCreateRepository }: { projects: Project[]; repositories: Repository[]; q?: string; loading?: boolean; projectBusyID?: string; repositoryBusy?: boolean; onCreateProject: (input: { name: string; description: string }) => void; onUpdateProject: (input: { id: string; name: string; description: string }) => void; onArchiveProject: (id: string) => void; onCreateRepository: (input: { project_id: string; name: string; url: string; provider: string; default_ref: string }) => void }): ReactNode {
  const [editing, setEditing] = useState<string>();
  if (loading) return <SkeletonCard rows={5} />;
  const submit = (event: FormEvent<HTMLFormElement>, action: (form: FormData) => void) => { event.preventDefault(); action(new FormData(event.currentTarget)); event.currentTarget.reset(); };
  const visibleProjects = projects.filter((project) => matchesQuery(q, project.id, project.name, project.description));
  return <section className="grid gap-4 xl:grid-cols-[1fr_380px]"><div className="grid gap-3">{!visibleProjects.length ? <EmptyState title="No projects" icon={FolderKanban} /> : visibleProjects.map((project) => <Card key={project.id}><CardContent className="flex items-center justify-between gap-3 p-4"><div><strong>{project.name}</strong><p className="text-sm text-muted-foreground">{project.description}</p><p className="text-xs text-muted-foreground">Created {formatDate(project.created_at)} · {repositories.filter((repo) => repo.project_id === project.id).length} sources</p></div><div className="flex gap-2"><Button size="sm" variant="outline" onClick={() => setEditing(project.id)}><Pencil className="mr-1 h-4 w-4" />Edit</Button><Button size="sm" variant="outline" disabled={projectBusyID === project.id} onClick={() => onArchiveProject(project.id)}><Archive className="mr-1 h-4 w-4" />Archive</Button></div>{editing === project.id ? <form className="col-span-2 grid gap-2" onSubmit={(event) => submit(event, (form) => { onUpdateProject({ id: project.id, name: String(form.get("name")), description: String(form.get("description")) }); setEditing(undefined); })}><Input name="name" defaultValue={project.name} required /><Textarea name="description" defaultValue={project.description} /><Button type="submit">Save project</Button></form> : null}</CardContent></Card>)}</div><Card><CardHeader><CardTitle>Configure project</CardTitle></CardHeader><CardContent className="grid gap-6"><form className="grid gap-2" onSubmit={(event) => submit(event, (form) => onCreateProject({ name: String(form.get("name")), description: String(form.get("description")) }))}><Input name="name" placeholder="Project name" required /><Textarea name="description" placeholder="Description" /><Button type="submit"><Plus className="mr-1 h-4 w-4" />Create project</Button></form><form className="grid gap-2 border-t pt-5" onSubmit={(event) => submit(event, (form) => onCreateRepository({ project_id: String(form.get("project_id")), name: String(form.get("name")), url: String(form.get("url")), provider: String(form.get("provider")), default_ref: String(form.get("default_ref")) }))}><Select name="project_id" required>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</Select><Input name="name" placeholder="Repository name" required /><Input name="url" placeholder="Repository URL" required /><Input name="provider" defaultValue="git" /><Input name="default_ref" defaultValue="main" /><Button type="submit" disabled={repositoryBusy}><GitBranch className="mr-1 h-4 w-4" />Register source</Button></form></CardContent></Card></section>;
}
