import { type FormEvent, type ReactNode } from "react";
import { Settings, Shield, User, Users } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import type { Principal, Project, ProjectMember, ProjectMemberInput } from "@/api";
import { SkeletonCard } from "@/components/common/SkeletonCard";
import { Badge } from "@/components/ui/badge";
import { projectName } from "@/lib/format";
export function SettingsView({ principal, projects, members, loading, updatingMember, onUpsertMember }: { principal: Principal; projects: Project[]; members: ProjectMember[]; loading?: boolean; updatingMember?: boolean; onUpsertMember: (input: ProjectMemberInput) => void }): ReactNode { if (loading) return <SkeletonCard rows={6} />; const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); onUpsertMember({ project_id: String(form.get("project_id")), email: String(form.get("email")), role: String(form.get("role")) as ProjectMemberInput["role"] }); event.currentTarget.reset(); }; return <section className="grid min-w-0 gap-4 lg:grid-cols-2"><Card className="min-w-0"><CardHeader><CardTitle>Principal</CardTitle></CardHeader><CardContent className="grid min-w-0 gap-2"><p className="min-w-0 break-words"><User className="mr-2 inline h-4 w-4" />{principal.name}</p><p className="min-w-0 break-words"><Shield className="mr-2 inline h-4 w-4" />{principal.email}</p><p className="min-w-0 break-words"><Settings className="mr-2 inline h-4 w-4" />{principal.roles.join(", ")}</p></CardContent></Card><Card className="min-w-0"><CardHeader><CardTitle><Users className="mr-2 inline h-4 w-4" />Project access</CardTitle></CardHeader><CardContent className="grid min-w-0 gap-4"><form className="grid min-w-0 gap-2" onSubmit={submit}><Select name="project_id" required>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</Select><Input name="email" type="email" defaultValue={principal.email} required /><Select name="role" defaultValue="viewer"><option>viewer</option><option>maintainer</option><option>owner</option></Select><Button type="submit" disabled={updatingMember}>Update access</Button></form>{members.map((member) => <div key={member.id} className="flex min-w-0 flex-wrap items-start justify-between gap-2 rounded border p-2"><span className="min-w-0 break-words">{member.email} · {projectName(projects, member.project_id)}</span><Badge>{member.role}</Badge></div>)}</CardContent></Card></section>; }
