import { type FormEvent, type ReactNode, useState } from "react";
import { Layers3, Pencil, Play, Plus } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import type { Project, TaskTemplate, TemplateInput } from "@/api";
import { EmptyState } from "@/components/common/EmptyState";
import { SkeletonTable } from "@/components/common/SkeletonCard";
import { matchesQuery, projectName } from "@/lib/format";
const inputFrom = (form: FormData, existing?: TaskTemplate): TemplateInput => { const kind = String(form.get("kind") ?? existing?.kind ?? "shell"); const command = String(form.get("command") ?? "").trim().split(/\s+/).filter(Boolean); return { project_id: String(form.get("project_id") ?? existing?.project_id ?? ""), name: String(form.get("name") ?? existing?.name ?? ""), kind, run_spec: { ...(existing?.run_spec ?? { inputs: {} }), type: kind, ...(command.length ? { process: { ...existing?.run_spec.process, command } } : {}) }, workflow: existing?.workflow ?? { steps: [] }, runner_tags: String(form.get("runner_tags") ?? existing?.runner_tags.join(", ") ?? "").split(",").map((tag) => tag.trim()).filter(Boolean), requires_ack: form.has("requires_ack") }; };
export function TemplatesView({ projects, templates, q, loading, creating, updatingID, requestingID, onCreate, onUpdate, onRequestRun }: { projects: Project[]; templates: TaskTemplate[]; q?: string; loading?: boolean; creating?: boolean; updatingID?: string; requestingID?: string; onCreate: (input: TemplateInput) => void; onUpdate: (input: TemplateInput & { id: string }) => void; onRequestRun: (templateID: string) => void }): ReactNode {
  const [editing, setEditing] = useState<string>();
  if (loading) return <SkeletonTable rows={6} />;
  const submit = (event: FormEvent<HTMLFormElement>, action: (form: FormData) => void) => { event.preventDefault(); action(new FormData(event.currentTarget)); event.currentTarget.reset(); };
  const fields = (template?: TaskTemplate) => <><Select name="project_id" defaultValue={template?.project_id} required>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</Select><Input name="name" defaultValue={template?.name} placeholder="Template name" required /><Select name="kind" defaultValue={template?.kind ?? "shell"}>{["ansible", "opentofu", "shell", "terraform", "python", "powershell"].map((kind) => <option key={kind}>{kind}</option>)}</Select><Input name="runner_tags" defaultValue={template?.runner_tags.join(", ")} placeholder="linux, prod" /><Input name="command" defaultValue={template?.run_spec.process?.command.join(" ")} placeholder="Command" /><label className="flex gap-2"><input name="requires_ack" type="checkbox" defaultChecked={template?.requires_ack} />Requires approval</label></>;
  const visibleTemplates = templates.filter((template) => matchesQuery(q, template.id, template.name, template.kind, template.project_id, template.runner_tags.join(" ")));
  return <section className="grid gap-4 xl:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle>Create template</CardTitle></CardHeader><CardContent><form className="grid gap-3" onSubmit={(event) => submit(event, (form) => onCreate(inputFrom(form)))}>{fields()}<Button type="submit" disabled={creating}><Plus className="mr-1 h-4 w-4" />Create template</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Template inventory</CardTitle></CardHeader><CardContent className="p-0">{!visibleTemplates.length ? <EmptyState title="No templates" icon={Layers3} /> : <Table><TableHeader><TableRow><TableHead>Name</TableHead><TableHead>Project</TableHead><TableHead>Kind</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{visibleTemplates.map((template) => <TableRow key={template.id}><TableCell>{template.name}</TableCell><TableCell>{projectName(projects, template.project_id)}</TableCell><TableCell><Badge>{template.kind}</Badge></TableCell><TableCell><div className="flex gap-2"><Button size="sm" disabled={requestingID === template.id} onClick={() => onRequestRun(template.id)}><Play className="mr-1 h-4 w-4" />Play</Button><Button size="sm" variant="outline" onClick={() => setEditing(template.id)}><Pencil className="mr-1 h-4 w-4" />Edit</Button></div>{editing === template.id ? <form className="mt-3 grid gap-2" onSubmit={(event) => submit(event, (form) => { onUpdate({ ...inputFrom(form, template), id: template.id }); setEditing(undefined); })}>{fields(template)}<Button type="submit" disabled={updatingID === template.id}>Save template</Button></form> : null}</TableCell></TableRow>)}</TableBody></Table>}</CardContent></Card></section>;
}
