// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	models "nerocd/internal/store/bobgen/models"
)

type APITokenMod interface {
	Apply(context.Context, *APITokenTemplate)
}

type APITokenModFunc func(context.Context, *APITokenTemplate)

func (f APITokenModFunc) Apply(ctx context.Context, n *APITokenTemplate) {
	f(ctx, n)
}

type APITokenModSlice []APITokenMod

func (mods APITokenModSlice) Apply(ctx context.Context, n *APITokenTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// APITokenTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type APITokenTemplate struct {
	ID         func() string
	Name       func() string
	Kind       func() string
	TokenHash  func() string
	Roles      func() pq.StringArray
	Status     func() string
	CreatedBy  func() string
	CreatedAt  func() time.Time
	ExpiresAt  func() sql.Null[time.Time]
	LastUsedAt func() sql.Null[time.Time]
	RevokedAt  func() sql.Null[time.Time]

	r apiTokenR
	f *Factory

	alreadyPersisted bool
}

type apiTokenR struct {
	CreatedByUser *apiTokenRCreatedByUserR
}

type apiTokenRCreatedByUserR struct {
	o *UserTemplate
}

// Apply mods to the APITokenTemplate
func (o *APITokenTemplate) Apply(ctx context.Context, mods ...APITokenMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.APIToken
// according to the relationships in the template. Nothing is inserted into the db
func (t APITokenTemplate) setModelRels(o *models.APIToken) {
	if t.r.CreatedByUser != nil {
		rel := t.r.CreatedByUser.o.Build()
		o.CreatedBy = rel.ID // h2
		o.R.CreatedByUser = rel
		o.R.Loaded.CreatedByUser = true
	}
}

// BuildSetter returns an *models.APITokenSetter
// this does nothing with the relationship templates
func (o APITokenTemplate) BuildSetter() *models.APITokenSetter {
	m := &models.APITokenSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *string { return &val }()
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = func() *string { return &val }()
	}
	if o.Kind != nil {
		val := o.Kind()
		m.Kind = func() *string { return &val }()
	}
	if o.TokenHash != nil {
		val := o.TokenHash()
		m.TokenHash = func() *string { return &val }()
	}
	if o.Roles != nil {
		val := o.Roles()
		m.Roles = func() *pq.StringArray { return &val }()
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = func() *string { return &val }()
	}
	if o.CreatedBy != nil {
		val := o.CreatedBy()
		m.CreatedBy = func() *string { return &val }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.ExpiresAt != nil {
		val := o.ExpiresAt()
		m.ExpiresAt = func() *sql.Null[time.Time] { v := val; return &v }()
	}
	if o.LastUsedAt != nil {
		val := o.LastUsedAt()
		m.LastUsedAt = func() *sql.Null[time.Time] { v := val; return &v }()
	}
	if o.RevokedAt != nil {
		val := o.RevokedAt()
		m.RevokedAt = func() *sql.Null[time.Time] { v := val; return &v }()
	}

	return m
}

// BuildManySetter returns an []*models.APITokenSetter
// this does nothing with the relationship templates
func (o APITokenTemplate) BuildManySetter(number int) []*models.APITokenSetter {
	m := make([]*models.APITokenSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.APIToken
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use APITokenTemplate.Create
func (o APITokenTemplate) Build() *models.APIToken {
	m := &models.APIToken{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Kind != nil {
		m.Kind = o.Kind()
	}
	if o.TokenHash != nil {
		m.TokenHash = o.TokenHash()
	}
	if o.Roles != nil {
		m.Roles = o.Roles()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.CreatedBy != nil {
		m.CreatedBy = o.CreatedBy()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.ExpiresAt != nil {
		m.ExpiresAt = o.ExpiresAt()
	}
	if o.LastUsedAt != nil {
		m.LastUsedAt = o.LastUsedAt()
	}
	if o.RevokedAt != nil {
		m.RevokedAt = o.RevokedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.APITokenSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use APITokenTemplate.CreateMany
func (o APITokenTemplate) BuildMany(number int) models.APITokenSlice {
	m := make(models.APITokenSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableAPIToken(m *models.APITokenSetter) {
	if !(m.ID != nil) {
		val := random_string(nil)
		m.ID = func() *string { return &val }()
	}
	if !(m.Name != nil) {
		val := random_string(nil)
		m.Name = func() *string { return &val }()
	}
	if !(m.TokenHash != nil) {
		val := random_string(nil)
		m.TokenHash = func() *string { return &val }()
	}
	if !(m.Status != nil) {
		val := random_string(nil)
		m.Status = func() *string { return &val }()
	}
	if !(m.CreatedBy != nil) {
		val := random_string(nil)
		m.CreatedBy = func() *string { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.APIToken
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *APITokenTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.APIToken) error {
	var err error

	return err
}

// Create builds a apiToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *APITokenTemplate) Create(ctx context.Context, exec bob.Executor) (*models.APIToken, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableAPIToken(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel0 *models.User

	if o.r.CreatedByUser == nil {
		if parentModel, found := mInCreation["users:api_tokens:api_tokens.api_tokens_created_by_fkey"]; found {
			if pModel, ok := parentModel.(*models.User); ok {
				rel0 = pModel
			}
		}
	}

	if rel0 == nil {
		if o.r.CreatedByUser == nil {
			APITokenMods.WithNewCreatedByUser().Apply(ctx, o)
		}

		if o.r.CreatedByUser.o.alreadyPersisted {
			rel0 = o.r.CreatedByUser.o.Build()
		} else {
			rel0, err = o.r.CreatedByUser.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.CreatedBy = func() *string { return &rel0.ID }()

	m, err := models.APITokens.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.CreatedByUser = rel0
	m.R.Loaded.CreatedByUser = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a apiToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *APITokenTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.APIToken {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a apiToken and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *APITokenTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.APIToken {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple apiTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o APITokenTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.APITokenSlice, error) {
	var err error
	m := make(models.APITokenSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple apiTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o APITokenTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.APITokenSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple apiTokens and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o APITokenTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.APITokenSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// APIToken has methods that act as mods for the APITokenTemplate
var APITokenMods apiTokenMods

type apiTokenMods struct{}

func (m apiTokenMods) RandomizeAllColumns(f *faker.Faker) APITokenMod {
	return APITokenModSlice{
		APITokenMods.RandomID(f),
		APITokenMods.RandomName(f),
		APITokenMods.RandomKind(f),
		APITokenMods.RandomTokenHash(f),
		APITokenMods.RandomRoles(f),
		APITokenMods.RandomStatus(f),
		APITokenMods.RandomCreatedBy(f),
		APITokenMods.RandomCreatedAt(f),
		APITokenMods.RandomExpiresAt(f),
		APITokenMods.RandomLastUsedAt(f),
		APITokenMods.RandomRevokedAt(f),
	}
}

// Set the model columns to this value
func (m apiTokenMods) ID(val string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) IDFunc(f func() string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetID() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiTokenMods) RandomID(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m apiTokenMods) Name(val string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) NameFunc(f func() string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetName() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiTokenMods) RandomName(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m apiTokenMods) Kind(val string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Kind = func() string { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) KindFunc(f func() string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Kind = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetKind() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Kind = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiTokenMods) RandomKind(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Kind = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m apiTokenMods) TokenHash(val string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.TokenHash = func() string { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) TokenHashFunc(f func() string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.TokenHash = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetTokenHash() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.TokenHash = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiTokenMods) RandomTokenHash(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.TokenHash = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m apiTokenMods) Roles(val pq.StringArray) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Roles = func() pq.StringArray { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) RolesFunc(f func() pq.StringArray) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Roles = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetRoles() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Roles = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiTokenMods) RandomRoles(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Roles = func() pq.StringArray {
			return random_pq_StringArray(f)
		}
	})
}

// Set the model columns to this value
func (m apiTokenMods) Status(val string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) StatusFunc(f func() string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetStatus() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiTokenMods) RandomStatus(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.Status = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m apiTokenMods) CreatedBy(val string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.CreatedBy = func() string { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) CreatedByFunc(f func() string) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.CreatedBy = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetCreatedBy() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.CreatedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiTokenMods) RandomCreatedBy(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.CreatedBy = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m apiTokenMods) CreatedAt(val time.Time) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) CreatedAtFunc(f func() time.Time) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetCreatedAt() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m apiTokenMods) RandomCreatedAt(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m apiTokenMods) ExpiresAt(val sql.Null[time.Time]) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.ExpiresAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) ExpiresAtFunc(f func() sql.Null[time.Time]) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.ExpiresAt = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetExpiresAt() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.ExpiresAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m apiTokenMods) RandomExpiresAt(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.ExpiresAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m apiTokenMods) RandomExpiresAtNotNull(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.ExpiresAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m apiTokenMods) LastUsedAt(val sql.Null[time.Time]) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.LastUsedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) LastUsedAtFunc(f func() sql.Null[time.Time]) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.LastUsedAt = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetLastUsedAt() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.LastUsedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m apiTokenMods) RandomLastUsedAt(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.LastUsedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m apiTokenMods) RandomLastUsedAtNotNull(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.LastUsedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m apiTokenMods) RevokedAt(val sql.Null[time.Time]) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.RevokedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m apiTokenMods) RevokedAtFunc(f func() sql.Null[time.Time]) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.RevokedAt = f
	})
}

// Clear any values for the column
func (m apiTokenMods) UnsetRevokedAt() APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.RevokedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m apiTokenMods) RandomRevokedAt(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.RevokedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m apiTokenMods) RandomRevokedAtNotNull(f *faker.Faker) APITokenMod {
	return APITokenModFunc(func(_ context.Context, o *APITokenTemplate) {
		o.RevokedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

func (m apiTokenMods) WithParentsCascading() APITokenMod {
	return APITokenModFunc(func(ctx context.Context, o *APITokenTemplate) {
		if isDone, _ := apiTokenWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = apiTokenWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithCreatedByUser(related).Apply(ctx, o)
		}
	})
}

func (m apiTokenMods) WithCreatedByUser(rel *UserTemplate) APITokenMod {
	return APITokenModFunc(func(ctx context.Context, o *APITokenTemplate) {
		o.r.CreatedByUser = &apiTokenRCreatedByUserR{
			o: rel,
		}
	})
}

func (m apiTokenMods) WithNewCreatedByUser(mods ...UserMod) APITokenMod {
	return APITokenModFunc(func(ctx context.Context, o *APITokenTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithCreatedByUser(related).Apply(ctx, o)
	})
}

func (m apiTokenMods) WithExistingCreatedByUser(em *models.User) APITokenMod {
	return APITokenModFunc(func(ctx context.Context, o *APITokenTemplate) {
		o.r.CreatedByUser = &apiTokenRCreatedByUserR{
			o: o.f.fromExistingUser(ctx, em),
		}
	})
}

func (m apiTokenMods) WithoutCreatedByUser() APITokenMod {
	return APITokenModFunc(func(ctx context.Context, o *APITokenTemplate) {
		o.r.CreatedByUser = nil
	})
}
