// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "nerocd/internal/store/bobgen/models"
)

type ApprovalMod interface {
	Apply(context.Context, *ApprovalTemplate)
}

type ApprovalModFunc func(context.Context, *ApprovalTemplate)

func (f ApprovalModFunc) Apply(ctx context.Context, n *ApprovalTemplate) {
	f(ctx, n)
}

type ApprovalModSlice []ApprovalMod

func (mods ApprovalModSlice) Apply(ctx context.Context, n *ApprovalTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ApprovalTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ApprovalTemplate struct {
	ID          func() string
	RunID       func() string
	Status      func() string
	RequestedBy func() string
	ApprovedBy  func() sql.Null[string]
	CreatedAt   func() time.Time
	ApprovedAt  func() sql.Null[time.Time]

	r approvalR
	f *Factory

	alreadyPersisted bool
}

type approvalR struct {
	ApprovedByUser  *approvalRApprovedByUserR
	RequestedByUser *approvalRRequestedByUserR
	RunTaskRun      *approvalRRunTaskRunR
}

type approvalRApprovedByUserR struct {
	o *UserTemplate
}
type approvalRRequestedByUserR struct {
	o *UserTemplate
}
type approvalRRunTaskRunR struct {
	o *TaskRunTemplate
}

// Apply mods to the ApprovalTemplate
func (o *ApprovalTemplate) Apply(ctx context.Context, mods ...ApprovalMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Approval
// according to the relationships in the template. Nothing is inserted into the db
func (t ApprovalTemplate) setModelRels(o *models.Approval) {
	if t.r.ApprovedByUser != nil {
		rel := t.r.ApprovedByUser.o.Build()
		o.ApprovedBy = sql.Null[string]{V: rel.ID, Valid: true} // h2
		o.R.ApprovedByUser = rel
		o.R.Loaded.ApprovedByUser = true
	}

	if t.r.RequestedByUser != nil {
		rel := t.r.RequestedByUser.o.Build()
		o.RequestedBy = rel.ID // h2
		o.R.RequestedByUser = rel
		o.R.Loaded.RequestedByUser = true
	}

	if t.r.RunTaskRun != nil {
		rel := t.r.RunTaskRun.o.Build()
		o.RunID = rel.ID // h2
		o.R.RunTaskRun = rel
		o.R.Loaded.RunTaskRun = true
	}
}

// BuildSetter returns an *models.ApprovalSetter
// this does nothing with the relationship templates
func (o ApprovalTemplate) BuildSetter() *models.ApprovalSetter {
	m := &models.ApprovalSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *string { return &val }()
	}
	if o.RunID != nil {
		val := o.RunID()
		m.RunID = func() *string { return &val }()
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = func() *string { return &val }()
	}
	if o.RequestedBy != nil {
		val := o.RequestedBy()
		m.RequestedBy = func() *string { return &val }()
	}
	if o.ApprovedBy != nil {
		val := o.ApprovedBy()
		m.ApprovedBy = func() *sql.Null[string] { v := val; return &v }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.ApprovedAt != nil {
		val := o.ApprovedAt()
		m.ApprovedAt = func() *sql.Null[time.Time] { v := val; return &v }()
	}

	return m
}

// BuildManySetter returns an []*models.ApprovalSetter
// this does nothing with the relationship templates
func (o ApprovalTemplate) BuildManySetter(number int) []*models.ApprovalSetter {
	m := make([]*models.ApprovalSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Approval
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ApprovalTemplate.Create
func (o ApprovalTemplate) Build() *models.Approval {
	m := &models.Approval{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.RunID != nil {
		m.RunID = o.RunID()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.RequestedBy != nil {
		m.RequestedBy = o.RequestedBy()
	}
	if o.ApprovedBy != nil {
		m.ApprovedBy = o.ApprovedBy()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.ApprovedAt != nil {
		m.ApprovedAt = o.ApprovedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ApprovalSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ApprovalTemplate.CreateMany
func (o ApprovalTemplate) BuildMany(number int) models.ApprovalSlice {
	m := make(models.ApprovalSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableApproval(m *models.ApprovalSetter) {
	if !(m.ID != nil) {
		val := random_string(nil)
		m.ID = func() *string { return &val }()
	}
	if !(m.RunID != nil) {
		val := random_string(nil)
		m.RunID = func() *string { return &val }()
	}
	if !(m.Status != nil) {
		val := random_string(nil)
		m.Status = func() *string { return &val }()
	}
	if !(m.RequestedBy != nil) {
		val := random_string(nil)
		m.RequestedBy = func() *string { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Approval
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ApprovalTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Approval) error {
	var err error

	isApprovedByUserDone, _ := approvalRelApprovedByUserCtx.Value(ctx)
	if !isApprovedByUserDone && o.r.ApprovedByUser != nil {
		ctx = approvalRelApprovedByUserCtx.WithValue(ctx, true)
		if o.r.ApprovedByUser.o.alreadyPersisted {
			m.R.ApprovedByUser = o.r.ApprovedByUser.o.Build()
			m.R.Loaded.ApprovedByUser = true
		} else {
			var rel0 *models.User
			rel0, err = o.r.ApprovedByUser.o.Create(ctx, exec)
			if err != nil {
				return err
			}
			err = m.AttachApprovedByUser(ctx, exec, rel0)
			if err != nil {
				return err
			}
		}

	}

	return err
}

// Create builds a approval and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ApprovalTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Approval, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableApproval(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel1 *models.User

	if o.r.RequestedByUser == nil {
		if parentModel, found := mInCreation["users:approvals:approvals.approvals_requested_by_fkey"]; found {
			if pModel, ok := parentModel.(*models.User); ok {
				rel1 = pModel
			}
		}
	}

	if rel1 == nil {
		if o.r.RequestedByUser == nil {
			ApprovalMods.WithNewRequestedByUser().Apply(ctx, o)
		}

		if o.r.RequestedByUser.o.alreadyPersisted {
			rel1 = o.r.RequestedByUser.o.Build()
		} else {
			rel1, err = o.r.RequestedByUser.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.RequestedBy = func() *string { return &rel1.ID }()

	var rel2 *models.TaskRun

	if o.r.RunTaskRun == nil {
		if parentModel, found := mInCreation["task_runs:approvals:approvals.approvals_run_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.TaskRun); ok {
				rel2 = pModel
			}
		}
	}

	if rel2 == nil {
		if o.r.RunTaskRun == nil {
			ApprovalMods.WithNewRunTaskRun().Apply(ctx, o)
		}

		if o.r.RunTaskRun.o.alreadyPersisted {
			rel2 = o.r.RunTaskRun.o.Build()
		} else {
			rel2, err = o.r.RunTaskRun.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.RunID = func() *string { return &rel2.ID }()

	m, err := models.Approvals.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["approvals:task_runs:approvals.approvals_run_id_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.RequestedByUser = rel1
	m.R.Loaded.RequestedByUser = true
	m.R.RunTaskRun = rel2
	m.R.Loaded.RunTaskRun = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a approval and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ApprovalTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Approval {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a approval and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ApprovalTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Approval {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple approvals and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ApprovalTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ApprovalSlice, error) {
	var err error
	m := make(models.ApprovalSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple approvals and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ApprovalTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ApprovalSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple approvals and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ApprovalTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ApprovalSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Approval has methods that act as mods for the ApprovalTemplate
var ApprovalMods approvalMods

type approvalMods struct{}

func (m approvalMods) RandomizeAllColumns(f *faker.Faker) ApprovalMod {
	return ApprovalModSlice{
		ApprovalMods.RandomID(f),
		ApprovalMods.RandomRunID(f),
		ApprovalMods.RandomStatus(f),
		ApprovalMods.RandomRequestedBy(f),
		ApprovalMods.RandomApprovedBy(f),
		ApprovalMods.RandomCreatedAt(f),
		ApprovalMods.RandomApprovedAt(f),
	}
}

// Set the model columns to this value
func (m approvalMods) ID(val string) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m approvalMods) IDFunc(f func() string) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m approvalMods) UnsetID() ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m approvalMods) RandomID(f *faker.Faker) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m approvalMods) RunID(val string) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.RunID = func() string { return val }
	})
}

// Set the Column from the function
func (m approvalMods) RunIDFunc(f func() string) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.RunID = f
	})
}

// Clear any values for the column
func (m approvalMods) UnsetRunID() ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.RunID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m approvalMods) RandomRunID(f *faker.Faker) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.RunID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m approvalMods) Status(val string) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m approvalMods) StatusFunc(f func() string) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m approvalMods) UnsetStatus() ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m approvalMods) RandomStatus(f *faker.Faker) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.Status = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m approvalMods) RequestedBy(val string) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.RequestedBy = func() string { return val }
	})
}

// Set the Column from the function
func (m approvalMods) RequestedByFunc(f func() string) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.RequestedBy = f
	})
}

// Clear any values for the column
func (m approvalMods) UnsetRequestedBy() ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.RequestedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m approvalMods) RandomRequestedBy(f *faker.Faker) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.RequestedBy = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m approvalMods) ApprovedBy(val sql.Null[string]) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ApprovedBy = func() sql.Null[string] { return val }
	})
}

// Set the Column from the function
func (m approvalMods) ApprovedByFunc(f func() sql.Null[string]) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ApprovedBy = f
	})
}

// Clear any values for the column
func (m approvalMods) UnsetApprovedBy() ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ApprovedBy = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m approvalMods) RandomApprovedBy(f *faker.Faker) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ApprovedBy = func() sql.Null[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return sql.Null[string]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m approvalMods) RandomApprovedByNotNull(f *faker.Faker) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ApprovedBy = func() sql.Null[string] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_string(f)
			return sql.Null[string]{V: val, Valid: true}
		}
	})
}

// Set the model columns to this value
func (m approvalMods) CreatedAt(val time.Time) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m approvalMods) CreatedAtFunc(f func() time.Time) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m approvalMods) UnsetCreatedAt() ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m approvalMods) RandomCreatedAt(f *faker.Faker) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m approvalMods) ApprovedAt(val sql.Null[time.Time]) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ApprovedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m approvalMods) ApprovedAtFunc(f func() sql.Null[time.Time]) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ApprovedAt = f
	})
}

// Clear any values for the column
func (m approvalMods) UnsetApprovedAt() ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ApprovedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m approvalMods) RandomApprovedAt(f *faker.Faker) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ApprovedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m approvalMods) RandomApprovedAtNotNull(f *faker.Faker) ApprovalMod {
	return ApprovalModFunc(func(_ context.Context, o *ApprovalTemplate) {
		o.ApprovedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

func (m approvalMods) WithParentsCascading() ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		if isDone, _ := approvalWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = approvalWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithApprovedByUser(related).Apply(ctx, o)
		}
		{

			related := o.f.NewUserWithContext(ctx, UserMods.WithParentsCascading())
			m.WithRequestedByUser(related).Apply(ctx, o)
		}
		{

			related := o.f.NewTaskRunWithContext(ctx, TaskRunMods.WithParentsCascading())
			m.WithRunTaskRun(related).Apply(ctx, o)
		}
	})
}

func (m approvalMods) WithApprovedByUser(rel *UserTemplate) ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		o.r.ApprovedByUser = &approvalRApprovedByUserR{
			o: rel,
		}
	})
}

func (m approvalMods) WithNewApprovedByUser(mods ...UserMod) ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithApprovedByUser(related).Apply(ctx, o)
	})
}

func (m approvalMods) WithExistingApprovedByUser(em *models.User) ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		o.r.ApprovedByUser = &approvalRApprovedByUserR{
			o: o.f.fromExistingUser(ctx, em),
		}
	})
}

func (m approvalMods) WithoutApprovedByUser() ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		o.r.ApprovedByUser = nil
	})
}

func (m approvalMods) WithRequestedByUser(rel *UserTemplate) ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		o.r.RequestedByUser = &approvalRRequestedByUserR{
			o: rel,
		}
	})
}

func (m approvalMods) WithNewRequestedByUser(mods ...UserMod) ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		related := o.f.NewUserWithContext(ctx, mods...)

		m.WithRequestedByUser(related).Apply(ctx, o)
	})
}

func (m approvalMods) WithExistingRequestedByUser(em *models.User) ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		o.r.RequestedByUser = &approvalRRequestedByUserR{
			o: o.f.fromExistingUser(ctx, em),
		}
	})
}

func (m approvalMods) WithoutRequestedByUser() ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		o.r.RequestedByUser = nil
	})
}

func (m approvalMods) WithRunTaskRun(rel *TaskRunTemplate) ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		o.r.RunTaskRun = &approvalRRunTaskRunR{
			o: rel,
		}
	})
}

func (m approvalMods) WithNewRunTaskRun(mods ...TaskRunMod) ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		related := o.f.NewTaskRunWithContext(ctx, mods...)

		m.WithRunTaskRun(related).Apply(ctx, o)
	})
}

func (m approvalMods) WithExistingRunTaskRun(em *models.TaskRun) ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		o.r.RunTaskRun = &approvalRRunTaskRunR{
			o: o.f.fromExistingTaskRun(ctx, em),
		}
	})
}

func (m approvalMods) WithoutRunTaskRun() ApprovalMod {
	return ApprovalModFunc(func(ctx context.Context, o *ApprovalTemplate) {
		o.r.RunTaskRun = nil
	})
}
