// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type contextKey string

var (
	factoryVisitedCtx = newContextual[map[uintptr]struct{}]("factoryVisited")

	// Relationship Contexts for access_keys
	accessKeyWithParentsCascadingCtx = newContextual[bool]("accessKeyWithParentsCascading")
	accessKeyRelProjectCtx           = newContextual[bool]("access_keys.projects.access_keys.access_keys_project_id_fkey")

	// Relationship Contexts for api_tokens
	apiTokenWithParentsCascadingCtx = newContextual[bool]("apiTokenWithParentsCascading")
	apiTokenRelCreatedByUserCtx     = newContextual[bool]("api_tokens.users.api_tokens.api_tokens_created_by_fkey")

	// Relationship Contexts for approvals
	approvalWithParentsCascadingCtx = newContextual[bool]("approvalWithParentsCascading")
	approvalRelApprovedByUserCtx    = newContextual[bool]("approvals.users.approvals.approvals_approved_by_fkey")
	approvalRelRequestedByUserCtx   = newContextual[bool]("approvals.users.approvals.approvals_requested_by_fkey")
	approvalRelRunTaskRunCtx        = newContextual[bool]("approvals.task_runs.approvals.approvals_run_id_fkey")

	// Relationship Contexts for audit_events
	auditEventWithParentsCascadingCtx = newContextual[bool]("auditEventWithParentsCascading")

	// Relationship Contexts for inventories
	inventoryWithParentsCascadingCtx = newContextual[bool]("inventoryWithParentsCascading")
	inventoryRelProjectCtx           = newContextual[bool]("inventories.projects.inventories.inventories_project_id_fkey")

	// Relationship Contexts for project_members
	projectMemberWithParentsCascadingCtx = newContextual[bool]("projectMemberWithParentsCascading")
	projectMemberRelProjectCtx           = newContextual[bool]("project_members.projects.project_members.project_members_project_id_fkey")
	projectMemberRelUserCtx              = newContextual[bool]("project_members.users.project_members.project_members_user_id_fkey")

	// Relationship Contexts for projects
	projectWithParentsCascadingCtx = newContextual[bool]("projectWithParentsCascading")
	projectRelAccessKeysCtx        = newContextual[bool]("access_keys.projects.access_keys.access_keys_project_id_fkey")
	projectRelInventoriesCtx       = newContextual[bool]("inventories.projects.inventories.inventories_project_id_fkey")
	projectRelProjectMembersCtx    = newContextual[bool]("project_members.projects.project_members.project_members_project_id_fkey")
	projectRelRepositoriesCtx      = newContextual[bool]("projects.repositories.repositories.repositories_project_id_fkey")
	projectRelTaskRunsCtx          = newContextual[bool]("projects.task_runs.task_runs.task_runs_project_id_fkey")
	projectRelTaskTemplatesCtx     = newContextual[bool]("projects.task_templates.task_templates.task_templates_project_id_fkey")

	// Relationship Contexts for repositories
	repositoryWithParentsCascadingCtx = newContextual[bool]("repositoryWithParentsCascading")
	repositoryRelProjectCtx           = newContextual[bool]("projects.repositories.repositories.repositories_project_id_fkey")

	// Relationship Contexts for run_artifacts
	runArtifactWithParentsCascadingCtx = newContextual[bool]("runArtifactWithParentsCascading")
	runArtifactRelLeaseRunLeaseCtx     = newContextual[bool]("run_artifacts.run_leases.run_artifacts.run_artifacts_lease_id_fkey")
	runArtifactRelRunTaskRunCtx        = newContextual[bool]("run_artifacts.task_runs.run_artifacts.run_artifacts_run_id_fkey")

	// Relationship Contexts for run_leases
	runLeaseWithParentsCascadingCtx = newContextual[bool]("runLeaseWithParentsCascading")
	runLeaseRelLeaseRunArtifactsCtx = newContextual[bool]("run_artifacts.run_leases.run_artifacts.run_artifacts_lease_id_fkey")
	runLeaseRelRunTaskRunCtx        = newContextual[bool]("run_leases.task_runs.run_leases.run_leases_run_id_fkey")
	runLeaseRelRunnerCtx            = newContextual[bool]("run_leases.runners.run_leases.run_leases_runner_id_fkey")

	// Relationship Contexts for run_logs
	runLogWithParentsCascadingCtx = newContextual[bool]("runLogWithParentsCascading")
	runLogRelRunTaskRunCtx        = newContextual[bool]("run_logs.task_runs.run_logs.run_logs_run_id_fkey")

	// Relationship Contexts for runners
	runnerWithParentsCascadingCtx = newContextual[bool]("runnerWithParentsCascading")
	runnerRelRunLeasesCtx         = newContextual[bool]("run_leases.runners.run_leases.run_leases_runner_id_fkey")

	// Relationship Contexts for sessions
	sessionWithParentsCascadingCtx = newContextual[bool]("sessionWithParentsCascading")
	sessionRelUserCtx              = newContextual[bool]("sessions.users.sessions.sessions_user_id_fkey")

	// Relationship Contexts for task_runs
	taskRunWithParentsCascadingCtx    = newContextual[bool]("taskRunWithParentsCascading")
	taskRunRelRunApprovalCtx          = newContextual[bool]("approvals.task_runs.approvals.approvals_run_id_fkey")
	taskRunRelRunRunArtifactsCtx      = newContextual[bool]("run_artifacts.task_runs.run_artifacts.run_artifacts_run_id_fkey")
	taskRunRelRunRunLeasesCtx         = newContextual[bool]("run_leases.task_runs.run_leases.run_leases_run_id_fkey")
	taskRunRelRunRunLogsCtx           = newContextual[bool]("run_logs.task_runs.run_logs.run_logs_run_id_fkey")
	taskRunRelProjectCtx              = newContextual[bool]("projects.task_runs.task_runs.task_runs_project_id_fkey")
	taskRunRelRequestedByUserCtx      = newContextual[bool]("task_runs.users.task_runs.task_runs_requested_by_fkey")
	taskRunRelTemplateTaskTemplateCtx = newContextual[bool]("task_runs.task_templates.task_runs.task_runs_template_id_fkey")

	// Relationship Contexts for task_templates
	taskTemplateWithParentsCascadingCtx = newContextual[bool]("taskTemplateWithParentsCascading")
	taskTemplateRelTemplateTaskRunsCtx  = newContextual[bool]("task_runs.task_templates.task_runs.task_runs_template_id_fkey")
	taskTemplateRelProjectCtx           = newContextual[bool]("projects.task_templates.task_templates.task_templates_project_id_fkey")

	// Relationship Contexts for users
	userWithParentsCascadingCtx    = newContextual[bool]("userWithParentsCascading")
	userRelCreatedByAPITokensCtx   = newContextual[bool]("api_tokens.users.api_tokens.api_tokens_created_by_fkey")
	userRelApprovedByApprovalsCtx  = newContextual[bool]("approvals.users.approvals.approvals_approved_by_fkey")
	userRelRequestedByApprovalsCtx = newContextual[bool]("approvals.users.approvals.approvals_requested_by_fkey")
	userRelProjectMembersCtx       = newContextual[bool]("project_members.users.project_members.project_members_user_id_fkey")
	userRelSessionsCtx             = newContextual[bool]("sessions.users.sessions.sessions_user_id_fkey")
	userRelRequestedByTaskRunsCtx  = newContextual[bool]("task_runs.users.task_runs.task_runs_requested_by_fkey")

	modelsInCreationCtx = newContextual[map[string]any]("modelsInCreation")
)

// Contextual is a convienience wrapper around context.WithValue and context.Value
type contextual[V any] struct {
	key contextKey
}

func newContextual[V any](key string) contextual[V] {
	return contextual[V]{key: contextKey(key)}
}

func (k contextual[V]) WithValue(ctx context.Context, val V) context.Context {
	return context.WithValue(ctx, k.key, val)
}

func (k contextual[V]) Value(ctx context.Context) (V, bool) {
	v, ok := ctx.Value(k.key).(V)
	return v, ok
}
