// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "nerocd/internal/store/bobgen/models"
)

type RunLeaseMod interface {
	Apply(context.Context, *RunLeaseTemplate)
}

type RunLeaseModFunc func(context.Context, *RunLeaseTemplate)

func (f RunLeaseModFunc) Apply(ctx context.Context, n *RunLeaseTemplate) {
	f(ctx, n)
}

type RunLeaseModSlice []RunLeaseMod

func (mods RunLeaseModSlice) Apply(ctx context.Context, n *RunLeaseTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// RunLeaseTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type RunLeaseTemplate struct {
	ID          func() string
	RunID       func() string
	RunnerID    func() string
	Status      func() string
	ExpiresAt   func() time.Time
	CreatedAt   func() time.Time
	CompletedAt func() sql.Null[time.Time]

	r runLeaseR
	f *Factory

	alreadyPersisted bool
}

type runLeaseR struct {
	LeaseRunArtifacts []*runLeaseRLeaseRunArtifactsR
	RunTaskRun        *runLeaseRRunTaskRunR
	Runner            *runLeaseRRunnerR
}

type runLeaseRLeaseRunArtifactsR struct {
	number int
	o      *RunArtifactTemplate
}
type runLeaseRRunTaskRunR struct {
	o *TaskRunTemplate
}
type runLeaseRRunnerR struct {
	o *RunnerTemplate
}

// Apply mods to the RunLeaseTemplate
func (o *RunLeaseTemplate) Apply(ctx context.Context, mods ...RunLeaseMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.RunLease
// according to the relationships in the template. Nothing is inserted into the db
func (t RunLeaseTemplate) setModelRels(o *models.RunLease) {
	if t.r.LeaseRunArtifacts != nil {
		rel := models.RunArtifactSlice{}
		for _, r := range t.r.LeaseRunArtifacts {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.LeaseID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.LeaseRunArtifacts = rel
		o.R.Loaded.LeaseRunArtifacts = true
	}

	if t.r.RunTaskRun != nil {
		rel := t.r.RunTaskRun.o.Build()
		o.RunID = rel.ID // h2
		o.R.RunTaskRun = rel
		o.R.Loaded.RunTaskRun = true
	}

	if t.r.Runner != nil {
		rel := t.r.Runner.o.Build()
		o.RunnerID = rel.ID // h2
		o.R.Runner = rel
		o.R.Loaded.Runner = true
	}
}

// BuildSetter returns an *models.RunLeaseSetter
// this does nothing with the relationship templates
func (o RunLeaseTemplate) BuildSetter() *models.RunLeaseSetter {
	m := &models.RunLeaseSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *string { return &val }()
	}
	if o.RunID != nil {
		val := o.RunID()
		m.RunID = func() *string { return &val }()
	}
	if o.RunnerID != nil {
		val := o.RunnerID()
		m.RunnerID = func() *string { return &val }()
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = func() *string { return &val }()
	}
	if o.ExpiresAt != nil {
		val := o.ExpiresAt()
		m.ExpiresAt = func() *time.Time { return &val }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.CompletedAt != nil {
		val := o.CompletedAt()
		m.CompletedAt = func() *sql.Null[time.Time] { v := val; return &v }()
	}

	return m
}

// BuildManySetter returns an []*models.RunLeaseSetter
// this does nothing with the relationship templates
func (o RunLeaseTemplate) BuildManySetter(number int) []*models.RunLeaseSetter {
	m := make([]*models.RunLeaseSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.RunLease
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RunLeaseTemplate.Create
func (o RunLeaseTemplate) Build() *models.RunLease {
	m := &models.RunLease{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.RunID != nil {
		m.RunID = o.RunID()
	}
	if o.RunnerID != nil {
		m.RunnerID = o.RunnerID()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.ExpiresAt != nil {
		m.ExpiresAt = o.ExpiresAt()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.CompletedAt != nil {
		m.CompletedAt = o.CompletedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.RunLeaseSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RunLeaseTemplate.CreateMany
func (o RunLeaseTemplate) BuildMany(number int) models.RunLeaseSlice {
	m := make(models.RunLeaseSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableRunLease(m *models.RunLeaseSetter) {
	if !(m.ID != nil) {
		val := random_string(nil)
		m.ID = func() *string { return &val }()
	}
	if !(m.RunID != nil) {
		val := random_string(nil)
		m.RunID = func() *string { return &val }()
	}
	if !(m.RunnerID != nil) {
		val := random_string(nil)
		m.RunnerID = func() *string { return &val }()
	}
	if !(m.Status != nil) {
		val := random_string(nil)
		m.Status = func() *string { return &val }()
	}
	if !(m.ExpiresAt != nil) {
		val := random_time_Time(nil)
		m.ExpiresAt = func() *time.Time { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.RunLease
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *RunLeaseTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.RunLease) error {
	var err error

	isLeaseRunArtifactsDone, _ := runLeaseRelLeaseRunArtifactsCtx.Value(ctx)
	if !isLeaseRunArtifactsDone && o.r.LeaseRunArtifacts != nil {
		ctx = runLeaseRelLeaseRunArtifactsCtx.WithValue(ctx, true)
		for _, r := range o.r.LeaseRunArtifacts {
			if r.o.alreadyPersisted {
				m.R.LeaseRunArtifacts = append(m.R.LeaseRunArtifacts, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachLeaseRunArtifacts(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a runLease and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *RunLeaseTemplate) Create(ctx context.Context, exec bob.Executor) (*models.RunLease, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableRunLease(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel1 *models.TaskRun

	if o.r.RunTaskRun == nil {
		if parentModel, found := mInCreation["task_runs:run_leases:run_leases.run_leases_run_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.TaskRun); ok {
				rel1 = pModel
			}
		}
	}

	if rel1 == nil {
		if o.r.RunTaskRun == nil {
			RunLeaseMods.WithNewRunTaskRun().Apply(ctx, o)
		}

		if o.r.RunTaskRun.o.alreadyPersisted {
			rel1 = o.r.RunTaskRun.o.Build()
		} else {
			rel1, err = o.r.RunTaskRun.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.RunID = func() *string { return &rel1.ID }()

	var rel2 *models.Runner

	if o.r.Runner == nil {
		if parentModel, found := mInCreation["runners:run_leases:run_leases.run_leases_runner_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.Runner); ok {
				rel2 = pModel
			}
		}
	}

	if rel2 == nil {
		if o.r.Runner == nil {
			RunLeaseMods.WithNewRunner().Apply(ctx, o)
		}

		if o.r.Runner.o.alreadyPersisted {
			rel2 = o.r.Runner.o.Build()
		} else {
			rel2, err = o.r.Runner.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.RunnerID = func() *string { return &rel2.ID }()

	m, err := models.RunLeases.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["run_leases:run_artifacts:run_artifacts.run_artifacts_lease_id_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.RunTaskRun = rel1
	m.R.Loaded.RunTaskRun = true
	m.R.Runner = rel2
	m.R.Loaded.Runner = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a runLease and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *RunLeaseTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.RunLease {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a runLease and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *RunLeaseTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.RunLease {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple runLeases and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o RunLeaseTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.RunLeaseSlice, error) {
	var err error
	m := make(models.RunLeaseSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple runLeases and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o RunLeaseTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.RunLeaseSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple runLeases and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o RunLeaseTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.RunLeaseSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// RunLease has methods that act as mods for the RunLeaseTemplate
var RunLeaseMods runLeaseMods

type runLeaseMods struct{}

func (m runLeaseMods) RandomizeAllColumns(f *faker.Faker) RunLeaseMod {
	return RunLeaseModSlice{
		RunLeaseMods.RandomID(f),
		RunLeaseMods.RandomRunID(f),
		RunLeaseMods.RandomRunnerID(f),
		RunLeaseMods.RandomStatus(f),
		RunLeaseMods.RandomExpiresAt(f),
		RunLeaseMods.RandomCreatedAt(f),
		RunLeaseMods.RandomCompletedAt(f),
	}
}

// Set the model columns to this value
func (m runLeaseMods) ID(val string) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m runLeaseMods) IDFunc(f func() string) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m runLeaseMods) UnsetID() RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLeaseMods) RandomID(f *faker.Faker) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m runLeaseMods) RunID(val string) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.RunID = func() string { return val }
	})
}

// Set the Column from the function
func (m runLeaseMods) RunIDFunc(f func() string) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.RunID = f
	})
}

// Clear any values for the column
func (m runLeaseMods) UnsetRunID() RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.RunID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLeaseMods) RandomRunID(f *faker.Faker) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.RunID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m runLeaseMods) RunnerID(val string) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.RunnerID = func() string { return val }
	})
}

// Set the Column from the function
func (m runLeaseMods) RunnerIDFunc(f func() string) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.RunnerID = f
	})
}

// Clear any values for the column
func (m runLeaseMods) UnsetRunnerID() RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.RunnerID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLeaseMods) RandomRunnerID(f *faker.Faker) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.RunnerID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m runLeaseMods) Status(val string) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m runLeaseMods) StatusFunc(f func() string) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m runLeaseMods) UnsetStatus() RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLeaseMods) RandomStatus(f *faker.Faker) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.Status = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m runLeaseMods) ExpiresAt(val time.Time) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.ExpiresAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m runLeaseMods) ExpiresAtFunc(f func() time.Time) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.ExpiresAt = f
	})
}

// Clear any values for the column
func (m runLeaseMods) UnsetExpiresAt() RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.ExpiresAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLeaseMods) RandomExpiresAt(f *faker.Faker) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.ExpiresAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m runLeaseMods) CreatedAt(val time.Time) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m runLeaseMods) CreatedAtFunc(f func() time.Time) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m runLeaseMods) UnsetCreatedAt() RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLeaseMods) RandomCreatedAt(f *faker.Faker) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m runLeaseMods) CompletedAt(val sql.Null[time.Time]) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.CompletedAt = func() sql.Null[time.Time] { return val }
	})
}

// Set the Column from the function
func (m runLeaseMods) CompletedAtFunc(f func() sql.Null[time.Time]) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.CompletedAt = f
	})
}

// Clear any values for the column
func (m runLeaseMods) UnsetCompletedAt() RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.CompletedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is sometimes null
func (m runLeaseMods) RandomCompletedAt(f *faker.Faker) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.CompletedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: f.Bool()}
		}
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
// The generated value is never null
func (m runLeaseMods) RandomCompletedAtNotNull(f *faker.Faker) RunLeaseMod {
	return RunLeaseModFunc(func(_ context.Context, o *RunLeaseTemplate) {
		o.CompletedAt = func() sql.Null[time.Time] {
			if f == nil {
				f = &defaultFaker
			}

			val := random_time_Time(f)
			return sql.Null[time.Time]{V: val, Valid: true}
		}
	})
}

func (m runLeaseMods) WithParentsCascading() RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		if isDone, _ := runLeaseWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = runLeaseWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewTaskRunWithContext(ctx, TaskRunMods.WithParentsCascading())
			m.WithRunTaskRun(related).Apply(ctx, o)
		}
		{

			related := o.f.NewRunnerWithContext(ctx, RunnerMods.WithParentsCascading())
			m.WithRunner(related).Apply(ctx, o)
		}
	})
}

func (m runLeaseMods) WithRunTaskRun(rel *TaskRunTemplate) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		o.r.RunTaskRun = &runLeaseRRunTaskRunR{
			o: rel,
		}
	})
}

func (m runLeaseMods) WithNewRunTaskRun(mods ...TaskRunMod) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		related := o.f.NewTaskRunWithContext(ctx, mods...)

		m.WithRunTaskRun(related).Apply(ctx, o)
	})
}

func (m runLeaseMods) WithExistingRunTaskRun(em *models.TaskRun) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		o.r.RunTaskRun = &runLeaseRRunTaskRunR{
			o: o.f.fromExistingTaskRun(ctx, em),
		}
	})
}

func (m runLeaseMods) WithoutRunTaskRun() RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		o.r.RunTaskRun = nil
	})
}

func (m runLeaseMods) WithRunner(rel *RunnerTemplate) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		o.r.Runner = &runLeaseRRunnerR{
			o: rel,
		}
	})
}

func (m runLeaseMods) WithNewRunner(mods ...RunnerMod) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		related := o.f.NewRunnerWithContext(ctx, mods...)

		m.WithRunner(related).Apply(ctx, o)
	})
}

func (m runLeaseMods) WithExistingRunner(em *models.Runner) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		o.r.Runner = &runLeaseRRunnerR{
			o: o.f.fromExistingRunner(ctx, em),
		}
	})
}

func (m runLeaseMods) WithoutRunner() RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		o.r.Runner = nil
	})
}

func (m runLeaseMods) WithLeaseRunArtifacts(number int, related *RunArtifactTemplate) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		o.r.LeaseRunArtifacts = []*runLeaseRLeaseRunArtifactsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m runLeaseMods) WithNewLeaseRunArtifacts(number int, mods ...RunArtifactMod) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		related := o.f.NewRunArtifactWithContext(ctx, mods...)
		m.WithLeaseRunArtifacts(number, related).Apply(ctx, o)
	})
}

func (m runLeaseMods) AddLeaseRunArtifacts(number int, related *RunArtifactTemplate) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		o.r.LeaseRunArtifacts = append(o.r.LeaseRunArtifacts, &runLeaseRLeaseRunArtifactsR{
			number: number,
			o:      related,
		})
	})
}

func (m runLeaseMods) AddNewLeaseRunArtifacts(number int, mods ...RunArtifactMod) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		related := o.f.NewRunArtifactWithContext(ctx, mods...)
		m.AddLeaseRunArtifacts(number, related).Apply(ctx, o)
	})
}

func (m runLeaseMods) AddExistingLeaseRunArtifacts(existingModels ...*models.RunArtifact) RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		for _, em := range existingModels {
			o.r.LeaseRunArtifacts = append(o.r.LeaseRunArtifacts, &runLeaseRLeaseRunArtifactsR{
				o: o.f.fromExistingRunArtifact(ctx, em),
			})
		}
	})
}

func (m runLeaseMods) WithoutLeaseRunArtifacts() RunLeaseMod {
	return RunLeaseModFunc(func(ctx context.Context, o *RunLeaseTemplate) {
		o.r.LeaseRunArtifacts = nil
	})
}
