// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "nerocd/internal/store/bobgen/models"
)

type RunLogMod interface {
	Apply(context.Context, *RunLogTemplate)
}

type RunLogModFunc func(context.Context, *RunLogTemplate)

func (f RunLogModFunc) Apply(ctx context.Context, n *RunLogTemplate) {
	f(ctx, n)
}

type RunLogModSlice []RunLogMod

func (mods RunLogModSlice) Apply(ctx context.Context, n *RunLogTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// RunLogTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type RunLogTemplate struct {
	ID        func() string
	RunID     func() string
	Sequence  func() int32
	Stream    func() string
	Message   func() string
	CreatedAt func() time.Time

	r runLogR
	f *Factory

	alreadyPersisted bool
}

type runLogR struct {
	RunTaskRun *runLogRRunTaskRunR
}

type runLogRRunTaskRunR struct {
	o *TaskRunTemplate
}

// Apply mods to the RunLogTemplate
func (o *RunLogTemplate) Apply(ctx context.Context, mods ...RunLogMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.RunLog
// according to the relationships in the template. Nothing is inserted into the db
func (t RunLogTemplate) setModelRels(o *models.RunLog) {
	if t.r.RunTaskRun != nil {
		rel := t.r.RunTaskRun.o.Build()
		o.RunID = rel.ID // h2
		o.R.RunTaskRun = rel
		o.R.Loaded.RunTaskRun = true
	}
}

// BuildSetter returns an *models.RunLogSetter
// this does nothing with the relationship templates
func (o RunLogTemplate) BuildSetter() *models.RunLogSetter {
	m := &models.RunLogSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *string { return &val }()
	}
	if o.RunID != nil {
		val := o.RunID()
		m.RunID = func() *string { return &val }()
	}
	if o.Sequence != nil {
		val := o.Sequence()
		m.Sequence = func() *int32 { return &val }()
	}
	if o.Stream != nil {
		val := o.Stream()
		m.Stream = func() *string { return &val }()
	}
	if o.Message != nil {
		val := o.Message()
		m.Message = func() *string { return &val }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.RunLogSetter
// this does nothing with the relationship templates
func (o RunLogTemplate) BuildManySetter(number int) []*models.RunLogSetter {
	m := make([]*models.RunLogSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.RunLog
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RunLogTemplate.Create
func (o RunLogTemplate) Build() *models.RunLog {
	m := &models.RunLog{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.RunID != nil {
		m.RunID = o.RunID()
	}
	if o.Sequence != nil {
		m.Sequence = o.Sequence()
	}
	if o.Stream != nil {
		m.Stream = o.Stream()
	}
	if o.Message != nil {
		m.Message = o.Message()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.RunLogSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use RunLogTemplate.CreateMany
func (o RunLogTemplate) BuildMany(number int) models.RunLogSlice {
	m := make(models.RunLogSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableRunLog(m *models.RunLogSetter) {
	if !(m.ID != nil) {
		val := random_string(nil)
		m.ID = func() *string { return &val }()
	}
	if !(m.RunID != nil) {
		val := random_string(nil)
		m.RunID = func() *string { return &val }()
	}
	if !(m.Sequence != nil) {
		val := random_int32(nil)
		m.Sequence = func() *int32 { return &val }()
	}
	if !(m.Stream != nil) {
		val := random_string(nil)
		m.Stream = func() *string { return &val }()
	}
	if !(m.Message != nil) {
		val := random_string(nil)
		m.Message = func() *string { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.RunLog
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *RunLogTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.RunLog) error {
	var err error

	return err
}

// Create builds a runLog and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *RunLogTemplate) Create(ctx context.Context, exec bob.Executor) (*models.RunLog, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableRunLog(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel0 *models.TaskRun

	if o.r.RunTaskRun == nil {
		if parentModel, found := mInCreation["task_runs:run_logs:run_logs.run_logs_run_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.TaskRun); ok {
				rel0 = pModel
			}
		}
	}

	if rel0 == nil {
		if o.r.RunTaskRun == nil {
			RunLogMods.WithNewRunTaskRun().Apply(ctx, o)
		}

		if o.r.RunTaskRun.o.alreadyPersisted {
			rel0 = o.r.RunTaskRun.o.Build()
		} else {
			rel0, err = o.r.RunTaskRun.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.RunID = func() *string { return &rel0.ID }()

	m, err := models.RunLogs.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.RunTaskRun = rel0
	m.R.Loaded.RunTaskRun = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a runLog and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *RunLogTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.RunLog {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a runLog and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *RunLogTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.RunLog {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple runLogs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o RunLogTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.RunLogSlice, error) {
	var err error
	m := make(models.RunLogSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple runLogs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o RunLogTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.RunLogSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple runLogs and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o RunLogTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.RunLogSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// RunLog has methods that act as mods for the RunLogTemplate
var RunLogMods runLogMods

type runLogMods struct{}

func (m runLogMods) RandomizeAllColumns(f *faker.Faker) RunLogMod {
	return RunLogModSlice{
		RunLogMods.RandomID(f),
		RunLogMods.RandomRunID(f),
		RunLogMods.RandomSequence(f),
		RunLogMods.RandomStream(f),
		RunLogMods.RandomMessage(f),
		RunLogMods.RandomCreatedAt(f),
	}
}

// Set the model columns to this value
func (m runLogMods) ID(val string) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m runLogMods) IDFunc(f func() string) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m runLogMods) UnsetID() RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLogMods) RandomID(f *faker.Faker) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m runLogMods) RunID(val string) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.RunID = func() string { return val }
	})
}

// Set the Column from the function
func (m runLogMods) RunIDFunc(f func() string) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.RunID = f
	})
}

// Clear any values for the column
func (m runLogMods) UnsetRunID() RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.RunID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLogMods) RandomRunID(f *faker.Faker) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.RunID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m runLogMods) Sequence(val int32) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Sequence = func() int32 { return val }
	})
}

// Set the Column from the function
func (m runLogMods) SequenceFunc(f func() int32) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Sequence = f
	})
}

// Clear any values for the column
func (m runLogMods) UnsetSequence() RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Sequence = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLogMods) RandomSequence(f *faker.Faker) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Sequence = func() int32 {
			return random_int32(f)
		}
	})
}

// Set the model columns to this value
func (m runLogMods) Stream(val string) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Stream = func() string { return val }
	})
}

// Set the Column from the function
func (m runLogMods) StreamFunc(f func() string) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Stream = f
	})
}

// Clear any values for the column
func (m runLogMods) UnsetStream() RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Stream = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLogMods) RandomStream(f *faker.Faker) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Stream = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m runLogMods) Message(val string) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Message = func() string { return val }
	})
}

// Set the Column from the function
func (m runLogMods) MessageFunc(f func() string) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Message = f
	})
}

// Clear any values for the column
func (m runLogMods) UnsetMessage() RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Message = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLogMods) RandomMessage(f *faker.Faker) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.Message = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m runLogMods) CreatedAt(val time.Time) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m runLogMods) CreatedAtFunc(f func() time.Time) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m runLogMods) UnsetCreatedAt() RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m runLogMods) RandomCreatedAt(f *faker.Faker) RunLogMod {
	return RunLogModFunc(func(_ context.Context, o *RunLogTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

func (m runLogMods) WithParentsCascading() RunLogMod {
	return RunLogModFunc(func(ctx context.Context, o *RunLogTemplate) {
		if isDone, _ := runLogWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = runLogWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewTaskRunWithContext(ctx, TaskRunMods.WithParentsCascading())
			m.WithRunTaskRun(related).Apply(ctx, o)
		}
	})
}

func (m runLogMods) WithRunTaskRun(rel *TaskRunTemplate) RunLogMod {
	return RunLogModFunc(func(ctx context.Context, o *RunLogTemplate) {
		o.r.RunTaskRun = &runLogRRunTaskRunR{
			o: rel,
		}
	})
}

func (m runLogMods) WithNewRunTaskRun(mods ...TaskRunMod) RunLogMod {
	return RunLogModFunc(func(ctx context.Context, o *RunLogTemplate) {
		related := o.f.NewTaskRunWithContext(ctx, mods...)

		m.WithRunTaskRun(related).Apply(ctx, o)
	})
}

func (m runLogMods) WithExistingRunTaskRun(em *models.TaskRun) RunLogMod {
	return RunLogModFunc(func(ctx context.Context, o *RunLogTemplate) {
		o.r.RunTaskRun = &runLogRRunTaskRunR{
			o: o.f.fromExistingTaskRun(ctx, em),
		}
	})
}

func (m runLogMods) WithoutRunTaskRun() RunLogMod {
	return RunLogModFunc(func(ctx context.Context, o *RunLogTemplate) {
		o.r.RunTaskRun = nil
	})
}
