// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"encoding/json"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/lib/pq"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
	models "nerocd/internal/store/bobgen/models"
)

type TaskTemplateMod interface {
	Apply(context.Context, *TaskTemplateTemplate)
}

type TaskTemplateModFunc func(context.Context, *TaskTemplateTemplate)

func (f TaskTemplateModFunc) Apply(ctx context.Context, n *TaskTemplateTemplate) {
	f(ctx, n)
}

type TaskTemplateModSlice []TaskTemplateMod

func (mods TaskTemplateModSlice) Apply(ctx context.Context, n *TaskTemplateTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// TaskTemplateTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type TaskTemplateTemplate struct {
	ID          func() string
	ProjectID   func() string
	Name        func() string
	Kind        func() string
	RunnerTags  func() pq.StringArray
	RequiresAck func() bool
	CreatedAt   func() time.Time
	UpdatedAt   func() time.Time
	RunSpec     func() types.JSON[json.RawMessage]
	Workflow    func() types.JSON[json.RawMessage]

	r taskTemplateR
	f *Factory

	alreadyPersisted bool
}

type taskTemplateR struct {
	TemplateTaskRuns []*taskTemplateRTemplateTaskRunsR
	Project          *taskTemplateRProjectR
}

type taskTemplateRTemplateTaskRunsR struct {
	number int
	o      *TaskRunTemplate
}
type taskTemplateRProjectR struct {
	o *ProjectTemplate
}

// Apply mods to the TaskTemplateTemplate
func (o *TaskTemplateTemplate) Apply(ctx context.Context, mods ...TaskTemplateMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.TaskTemplate
// according to the relationships in the template. Nothing is inserted into the db
func (t TaskTemplateTemplate) setModelRels(o *models.TaskTemplate) {
	if t.r.TemplateTaskRuns != nil {
		rel := models.TaskRunSlice{}
		for _, r := range t.r.TemplateTaskRuns {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.TemplateID = sql.Null[string]{V: o.ID, Valid: true} // h2
			}
			rel = append(rel, related...)
		}
		o.R.TemplateTaskRuns = rel
		o.R.Loaded.TemplateTaskRuns = true
	}

	if t.r.Project != nil {
		rel := t.r.Project.o.Build()
		o.ProjectID = rel.ID // h2
		o.R.Project = rel
		o.R.Loaded.Project = true
	}
}

// BuildSetter returns an *models.TaskTemplateSetter
// this does nothing with the relationship templates
func (o TaskTemplateTemplate) BuildSetter() *models.TaskTemplateSetter {
	m := &models.TaskTemplateSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *string { return &val }()
	}
	if o.ProjectID != nil {
		val := o.ProjectID()
		m.ProjectID = func() *string { return &val }()
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = func() *string { return &val }()
	}
	if o.Kind != nil {
		val := o.Kind()
		m.Kind = func() *string { return &val }()
	}
	if o.RunnerTags != nil {
		val := o.RunnerTags()
		m.RunnerTags = func() *pq.StringArray { return &val }()
	}
	if o.RequiresAck != nil {
		val := o.RequiresAck()
		m.RequiresAck = func() *bool { return &val }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = func() *time.Time { return &val }()
	}
	if o.RunSpec != nil {
		val := o.RunSpec()
		m.RunSpec = func() *types.JSON[json.RawMessage] { return &val }()
	}
	if o.Workflow != nil {
		val := o.Workflow()
		m.Workflow = func() *types.JSON[json.RawMessage] { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.TaskTemplateSetter
// this does nothing with the relationship templates
func (o TaskTemplateTemplate) BuildManySetter(number int) []*models.TaskTemplateSetter {
	m := make([]*models.TaskTemplateSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.TaskTemplate
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TaskTemplateTemplate.Create
func (o TaskTemplateTemplate) Build() *models.TaskTemplate {
	m := &models.TaskTemplate{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.ProjectID != nil {
		m.ProjectID = o.ProjectID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Kind != nil {
		m.Kind = o.Kind()
	}
	if o.RunnerTags != nil {
		m.RunnerTags = o.RunnerTags()
	}
	if o.RequiresAck != nil {
		m.RequiresAck = o.RequiresAck()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.RunSpec != nil {
		m.RunSpec = o.RunSpec()
	}
	if o.Workflow != nil {
		m.Workflow = o.Workflow()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.TaskTemplateSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use TaskTemplateTemplate.CreateMany
func (o TaskTemplateTemplate) BuildMany(number int) models.TaskTemplateSlice {
	m := make(models.TaskTemplateSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableTaskTemplate(m *models.TaskTemplateSetter) {
	if !(m.ID != nil) {
		val := random_string(nil)
		m.ID = func() *string { return &val }()
	}
	if !(m.ProjectID != nil) {
		val := random_string(nil)
		m.ProjectID = func() *string { return &val }()
	}
	if !(m.Name != nil) {
		val := random_string(nil)
		m.Name = func() *string { return &val }()
	}
	if !(m.Kind != nil) {
		val := random_string(nil)
		m.Kind = func() *string { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.TaskTemplate
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *TaskTemplateTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.TaskTemplate) error {
	var err error

	isTemplateTaskRunsDone, _ := taskTemplateRelTemplateTaskRunsCtx.Value(ctx)
	if !isTemplateTaskRunsDone && o.r.TemplateTaskRuns != nil {
		ctx = taskTemplateRelTemplateTaskRunsCtx.WithValue(ctx, true)
		for _, r := range o.r.TemplateTaskRuns {
			if r.o.alreadyPersisted {
				m.R.TemplateTaskRuns = append(m.R.TemplateTaskRuns, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachTemplateTaskRuns(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a taskTemplate and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *TaskTemplateTemplate) Create(ctx context.Context, exec bob.Executor) (*models.TaskTemplate, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableTaskTemplate(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	var rel1 *models.Project

	if o.r.Project == nil {
		if parentModel, found := mInCreation["projects:task_templates:task_templates.task_templates_project_id_fkey"]; found {
			if pModel, ok := parentModel.(*models.Project); ok {
				rel1 = pModel
			}
		}
	}

	if rel1 == nil {
		if o.r.Project == nil {
			TaskTemplateMods.WithNewProject().Apply(ctx, o)
		}

		if o.r.Project.o.alreadyPersisted {
			rel1 = o.r.Project.o.Build()
		} else {
			rel1, err = o.r.Project.o.Create(ctx, exec)
			if err != nil {
				return nil, err
			}
		}
	}

	opt.ProjectID = func() *string { return &rel1.ID }()

	m, err := models.TaskTemplates.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["task_templates:task_runs:task_runs.task_runs_template_id_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	m.R.Project = rel1
	m.R.Loaded.Project = true

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a taskTemplate and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *TaskTemplateTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.TaskTemplate {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a taskTemplate and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *TaskTemplateTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.TaskTemplate {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple taskTemplates and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o TaskTemplateTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.TaskTemplateSlice, error) {
	var err error
	m := make(models.TaskTemplateSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple taskTemplates and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o TaskTemplateTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.TaskTemplateSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple taskTemplates and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o TaskTemplateTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.TaskTemplateSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// TaskTemplate has methods that act as mods for the TaskTemplateTemplate
var TaskTemplateMods taskTemplateMods

type taskTemplateMods struct{}

func (m taskTemplateMods) RandomizeAllColumns(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModSlice{
		TaskTemplateMods.RandomID(f),
		TaskTemplateMods.RandomProjectID(f),
		TaskTemplateMods.RandomName(f),
		TaskTemplateMods.RandomKind(f),
		TaskTemplateMods.RandomRunnerTags(f),
		TaskTemplateMods.RandomRequiresAck(f),
		TaskTemplateMods.RandomCreatedAt(f),
		TaskTemplateMods.RandomUpdatedAt(f),
		TaskTemplateMods.RandomRunSpec(f),
		TaskTemplateMods.RandomWorkflow(f),
	}
}

// Set the model columns to this value
func (m taskTemplateMods) ID(val string) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m taskTemplateMods) IDFunc(f func() string) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m taskTemplateMods) UnsetID() TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskTemplateMods) RandomID(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m taskTemplateMods) ProjectID(val string) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.ProjectID = func() string { return val }
	})
}

// Set the Column from the function
func (m taskTemplateMods) ProjectIDFunc(f func() string) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.ProjectID = f
	})
}

// Clear any values for the column
func (m taskTemplateMods) UnsetProjectID() TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.ProjectID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskTemplateMods) RandomProjectID(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.ProjectID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m taskTemplateMods) Name(val string) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m taskTemplateMods) NameFunc(f func() string) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m taskTemplateMods) UnsetName() TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskTemplateMods) RandomName(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m taskTemplateMods) Kind(val string) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Kind = func() string { return val }
	})
}

// Set the Column from the function
func (m taskTemplateMods) KindFunc(f func() string) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Kind = f
	})
}

// Clear any values for the column
func (m taskTemplateMods) UnsetKind() TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Kind = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskTemplateMods) RandomKind(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Kind = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m taskTemplateMods) RunnerTags(val pq.StringArray) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RunnerTags = func() pq.StringArray { return val }
	})
}

// Set the Column from the function
func (m taskTemplateMods) RunnerTagsFunc(f func() pq.StringArray) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RunnerTags = f
	})
}

// Clear any values for the column
func (m taskTemplateMods) UnsetRunnerTags() TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RunnerTags = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskTemplateMods) RandomRunnerTags(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RunnerTags = func() pq.StringArray {
			return random_pq_StringArray(f)
		}
	})
}

// Set the model columns to this value
func (m taskTemplateMods) RequiresAck(val bool) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RequiresAck = func() bool { return val }
	})
}

// Set the Column from the function
func (m taskTemplateMods) RequiresAckFunc(f func() bool) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RequiresAck = f
	})
}

// Clear any values for the column
func (m taskTemplateMods) UnsetRequiresAck() TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RequiresAck = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskTemplateMods) RandomRequiresAck(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RequiresAck = func() bool {
			return random_bool(f)
		}
	})
}

// Set the model columns to this value
func (m taskTemplateMods) CreatedAt(val time.Time) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m taskTemplateMods) CreatedAtFunc(f func() time.Time) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m taskTemplateMods) UnsetCreatedAt() TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskTemplateMods) RandomCreatedAt(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m taskTemplateMods) UpdatedAt(val time.Time) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m taskTemplateMods) UpdatedAtFunc(f func() time.Time) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m taskTemplateMods) UnsetUpdatedAt() TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskTemplateMods) RandomUpdatedAt(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m taskTemplateMods) RunSpec(val types.JSON[json.RawMessage]) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RunSpec = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m taskTemplateMods) RunSpecFunc(f func() types.JSON[json.RawMessage]) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RunSpec = f
	})
}

// Clear any values for the column
func (m taskTemplateMods) UnsetRunSpec() TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RunSpec = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskTemplateMods) RandomRunSpec(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.RunSpec = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

// Set the model columns to this value
func (m taskTemplateMods) Workflow(val types.JSON[json.RawMessage]) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Workflow = func() types.JSON[json.RawMessage] { return val }
	})
}

// Set the Column from the function
func (m taskTemplateMods) WorkflowFunc(f func() types.JSON[json.RawMessage]) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Workflow = f
	})
}

// Clear any values for the column
func (m taskTemplateMods) UnsetWorkflow() TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Workflow = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m taskTemplateMods) RandomWorkflow(f *faker.Faker) TaskTemplateMod {
	return TaskTemplateModFunc(func(_ context.Context, o *TaskTemplateTemplate) {
		o.Workflow = func() types.JSON[json.RawMessage] {
			return random_types_JSON_json_RawMessage_(f)
		}
	})
}

func (m taskTemplateMods) WithParentsCascading() TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		if isDone, _ := taskTemplateWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = taskTemplateWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewProjectWithContext(ctx, ProjectMods.WithParentsCascading())
			m.WithProject(related).Apply(ctx, o)
		}
	})
}

func (m taskTemplateMods) WithProject(rel *ProjectTemplate) TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		o.r.Project = &taskTemplateRProjectR{
			o: rel,
		}
	})
}

func (m taskTemplateMods) WithNewProject(mods ...ProjectMod) TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		related := o.f.NewProjectWithContext(ctx, mods...)

		m.WithProject(related).Apply(ctx, o)
	})
}

func (m taskTemplateMods) WithExistingProject(em *models.Project) TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		o.r.Project = &taskTemplateRProjectR{
			o: o.f.fromExistingProject(ctx, em),
		}
	})
}

func (m taskTemplateMods) WithoutProject() TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		o.r.Project = nil
	})
}

func (m taskTemplateMods) WithTemplateTaskRuns(number int, related *TaskRunTemplate) TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		o.r.TemplateTaskRuns = []*taskTemplateRTemplateTaskRunsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m taskTemplateMods) WithNewTemplateTaskRuns(number int, mods ...TaskRunMod) TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		related := o.f.NewTaskRunWithContext(ctx, mods...)
		m.WithTemplateTaskRuns(number, related).Apply(ctx, o)
	})
}

func (m taskTemplateMods) AddTemplateTaskRuns(number int, related *TaskRunTemplate) TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		o.r.TemplateTaskRuns = append(o.r.TemplateTaskRuns, &taskTemplateRTemplateTaskRunsR{
			number: number,
			o:      related,
		})
	})
}

func (m taskTemplateMods) AddNewTemplateTaskRuns(number int, mods ...TaskRunMod) TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		related := o.f.NewTaskRunWithContext(ctx, mods...)
		m.AddTemplateTaskRuns(number, related).Apply(ctx, o)
	})
}

func (m taskTemplateMods) AddExistingTemplateTaskRuns(existingModels ...*models.TaskRun) TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		for _, em := range existingModels {
			o.r.TemplateTaskRuns = append(o.r.TemplateTaskRuns, &taskTemplateRTemplateTaskRunsR{
				o: o.f.fromExistingTaskRun(ctx, em),
			})
		}
	})
}

func (m taskTemplateMods) WithoutTemplateTaskRuns() TaskTemplateMod {
	return TaskTemplateModFunc(func(ctx context.Context, o *TaskTemplateTemplate) {
		o.r.TemplateTaskRuns = nil
	})
}
