// Code generated by NeroCD BobGen. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"database/sql"
	"testing"
	"time"

	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "nerocd/internal/store/bobgen/models"
)

type UserMod interface {
	Apply(context.Context, *UserTemplate)
}

type UserModFunc func(context.Context, *UserTemplate)

func (f UserModFunc) Apply(ctx context.Context, n *UserTemplate) {
	f(ctx, n)
}

type UserModSlice []UserMod

func (mods UserModSlice) Apply(ctx context.Context, n *UserTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// UserTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type UserTemplate struct {
	ID           func() string
	Email        func() string
	Name         func() string
	Status       func() string
	CreatedAt    func() time.Time
	UpdatedAt    func() time.Time
	PasswordHash func() string
	GlobalRole   func() string

	r userR
	f *Factory

	alreadyPersisted bool
}

type userR struct {
	CreatedByAPITokens   []*userRCreatedByAPITokensR
	ApprovedByApprovals  []*userRApprovedByApprovalsR
	RequestedByApprovals []*userRRequestedByApprovalsR
	ProjectMembers       []*userRProjectMembersR
	Sessions             []*userRSessionsR
	RequestedByTaskRuns  []*userRRequestedByTaskRunsR
}

type userRCreatedByAPITokensR struct {
	number int
	o      *APITokenTemplate
}
type userRApprovedByApprovalsR struct {
	number int
	o      *ApprovalTemplate
}
type userRRequestedByApprovalsR struct {
	number int
	o      *ApprovalTemplate
}
type userRProjectMembersR struct {
	number int
	o      *ProjectMemberTemplate
}
type userRSessionsR struct {
	number int
	o      *SessionTemplate
}
type userRRequestedByTaskRunsR struct {
	number int
	o      *TaskRunTemplate
}

// Apply mods to the UserTemplate
func (o *UserTemplate) Apply(ctx context.Context, mods ...UserMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.User
// according to the relationships in the template. Nothing is inserted into the db
func (t UserTemplate) setModelRels(o *models.User) {
	if t.r.CreatedByAPITokens != nil {
		rel := models.APITokenSlice{}
		for _, r := range t.r.CreatedByAPITokens {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.CreatedBy = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.CreatedByAPITokens = rel
		o.R.Loaded.CreatedByAPITokens = true
	}

	if t.r.ApprovedByApprovals != nil {
		rel := models.ApprovalSlice{}
		for _, r := range t.r.ApprovedByApprovals {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.ApprovedBy = sql.Null[string]{V: o.ID, Valid: true} // h2
			}
			rel = append(rel, related...)
		}
		o.R.ApprovedByApprovals = rel
		o.R.Loaded.ApprovedByApprovals = true
	}

	if t.r.RequestedByApprovals != nil {
		rel := models.ApprovalSlice{}
		for _, r := range t.r.RequestedByApprovals {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.RequestedBy = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.RequestedByApprovals = rel
		o.R.Loaded.RequestedByApprovals = true
	}

	if t.r.ProjectMembers != nil {
		rel := models.ProjectMemberSlice{}
		for _, r := range t.r.ProjectMembers {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.ProjectMembers = rel
		o.R.Loaded.ProjectMembers = true
	}

	if t.r.Sessions != nil {
		rel := models.SessionSlice{}
		for _, r := range t.r.Sessions {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.UserID = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.Sessions = rel
		o.R.Loaded.Sessions = true
	}

	if t.r.RequestedByTaskRuns != nil {
		rel := models.TaskRunSlice{}
		for _, r := range t.r.RequestedByTaskRuns {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.RequestedBy = o.ID // h2
			}
			rel = append(rel, related...)
		}
		o.R.RequestedByTaskRuns = rel
		o.R.Loaded.RequestedByTaskRuns = true
	}
}

// BuildSetter returns an *models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildSetter() *models.UserSetter {
	m := &models.UserSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = func() *string { return &val }()
	}
	if o.Email != nil {
		val := o.Email()
		m.Email = func() *string { return &val }()
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = func() *string { return &val }()
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = func() *string { return &val }()
	}
	if o.CreatedAt != nil {
		val := o.CreatedAt()
		m.CreatedAt = func() *time.Time { return &val }()
	}
	if o.UpdatedAt != nil {
		val := o.UpdatedAt()
		m.UpdatedAt = func() *time.Time { return &val }()
	}
	if o.PasswordHash != nil {
		val := o.PasswordHash()
		m.PasswordHash = func() *string { return &val }()
	}
	if o.GlobalRole != nil {
		val := o.GlobalRole()
		m.GlobalRole = func() *string { return &val }()
	}

	return m
}

// BuildManySetter returns an []*models.UserSetter
// this does nothing with the relationship templates
func (o UserTemplate) BuildManySetter(number int) []*models.UserSetter {
	m := make([]*models.UserSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.User
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.Create
func (o UserTemplate) Build() *models.User {
	m := &models.User{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.Email != nil {
		m.Email = o.Email()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}
	if o.CreatedAt != nil {
		m.CreatedAt = o.CreatedAt()
	}
	if o.UpdatedAt != nil {
		m.UpdatedAt = o.UpdatedAt()
	}
	if o.PasswordHash != nil {
		m.PasswordHash = o.PasswordHash()
	}
	if o.GlobalRole != nil {
		m.GlobalRole = o.GlobalRole()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.UserSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use UserTemplate.CreateMany
func (o UserTemplate) BuildMany(number int) models.UserSlice {
	m := make(models.UserSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableUser(m *models.UserSetter) {
	if !(m.ID != nil) {
		val := random_string(nil)
		m.ID = func() *string { return &val }()
	}
	if !(m.Email != nil) {
		val := random_string(nil)
		m.Email = func() *string { return &val }()
	}
	if !(m.Name != nil) {
		val := random_string(nil)
		m.Name = func() *string { return &val }()
	}
	if !(m.Status != nil) {
		val := random_string(nil)
		m.Status = func() *string { return &val }()
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.User
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *UserTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.User) error {
	var err error

	isCreatedByAPITokensDone, _ := userRelCreatedByAPITokensCtx.Value(ctx)
	if !isCreatedByAPITokensDone && o.r.CreatedByAPITokens != nil {
		ctx = userRelCreatedByAPITokensCtx.WithValue(ctx, true)
		for _, r := range o.r.CreatedByAPITokens {
			if r.o.alreadyPersisted {
				m.R.CreatedByAPITokens = append(m.R.CreatedByAPITokens, r.o.Build())
			} else {
				rel0, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachCreatedByAPITokens(ctx, exec, rel0...)
				if err != nil {
					return err
				}
			}
		}
	}

	isApprovedByApprovalsDone, _ := userRelApprovedByApprovalsCtx.Value(ctx)
	if !isApprovedByApprovalsDone && o.r.ApprovedByApprovals != nil {
		ctx = userRelApprovedByApprovalsCtx.WithValue(ctx, true)
		for _, r := range o.r.ApprovedByApprovals {
			if r.o.alreadyPersisted {
				m.R.ApprovedByApprovals = append(m.R.ApprovedByApprovals, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachApprovedByApprovals(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	isRequestedByApprovalsDone, _ := userRelRequestedByApprovalsCtx.Value(ctx)
	if !isRequestedByApprovalsDone && o.r.RequestedByApprovals != nil {
		ctx = userRelRequestedByApprovalsCtx.WithValue(ctx, true)
		for _, r := range o.r.RequestedByApprovals {
			if r.o.alreadyPersisted {
				m.R.RequestedByApprovals = append(m.R.RequestedByApprovals, r.o.Build())
			} else {
				rel2, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachRequestedByApprovals(ctx, exec, rel2...)
				if err != nil {
					return err
				}
			}
		}
	}

	isProjectMembersDone, _ := userRelProjectMembersCtx.Value(ctx)
	if !isProjectMembersDone && o.r.ProjectMembers != nil {
		ctx = userRelProjectMembersCtx.WithValue(ctx, true)
		for _, r := range o.r.ProjectMembers {
			if r.o.alreadyPersisted {
				m.R.ProjectMembers = append(m.R.ProjectMembers, r.o.Build())
			} else {
				rel3, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachProjectMembers(ctx, exec, rel3...)
				if err != nil {
					return err
				}
			}
		}
	}

	isSessionsDone, _ := userRelSessionsCtx.Value(ctx)
	if !isSessionsDone && o.r.Sessions != nil {
		ctx = userRelSessionsCtx.WithValue(ctx, true)
		for _, r := range o.r.Sessions {
			if r.o.alreadyPersisted {
				m.R.Sessions = append(m.R.Sessions, r.o.Build())
			} else {
				rel4, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachSessions(ctx, exec, rel4...)
				if err != nil {
					return err
				}
			}
		}
	}

	isRequestedByTaskRunsDone, _ := userRelRequestedByTaskRunsCtx.Value(ctx)
	if !isRequestedByTaskRunsDone && o.r.RequestedByTaskRuns != nil {
		ctx = userRelRequestedByTaskRunsCtx.WithValue(ctx, true)
		for _, r := range o.r.RequestedByTaskRuns {
			if r.o.alreadyPersisted {
				m.R.RequestedByTaskRuns = append(m.R.RequestedByTaskRuns, r.o.Build())
			} else {
				rel5, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachRequestedByTaskRuns(ctx, exec, rel5...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *UserTemplate) Create(ctx context.Context, exec bob.Executor) (*models.User, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableUser(opt)

	// Retrieve ancestor models from context to avoid duplicate parent creation.
	// Parents are keyed by "parent_table:child_table:child_rel_name".
	// This works regardless of NoBackReferencing since it only uses child-side metadata.
	mInCreation, _ := modelsInCreationCtx.Value(ctx)

	m, err := models.Users.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	// Store this model in context for child creates.
	// Key format: "parent_table:child_table:child_rel_name" where child_rel_name is the FK name.
	// We store an entry for every relationship pointing TO this table (where this table is the parent).
	// This works regardless of NoBackReferencing since keys use child-side metadata.
	newMInCreation := make(map[string]any, len(mInCreation)+1)
	for k, v := range mInCreation {
		newMInCreation[k] = v
	}
	newMInCreation["users:api_tokens:api_tokens.api_tokens_created_by_fkey"] = m
	newMInCreation["users:approvals:approvals.approvals_approved_by_fkey"] = m
	newMInCreation["users:approvals:approvals.approvals_requested_by_fkey"] = m
	newMInCreation["users:project_members:project_members.project_members_user_id_fkey"] = m
	newMInCreation["users:sessions:sessions.sessions_user_id_fkey"] = m
	newMInCreation["users:task_runs:task_runs.task_runs_requested_by_fkey"] = m

	ctx = modelsInCreationCtx.WithValue(ctx, newMInCreation)

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *UserTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.User {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a user and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *UserTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.User {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o UserTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.UserSlice, error) {
	var err error
	m := make(models.UserSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o UserTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.UserSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple users and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o UserTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.UserSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// User has methods that act as mods for the UserTemplate
var UserMods userMods

type userMods struct{}

func (m userMods) RandomizeAllColumns(f *faker.Faker) UserMod {
	return UserModSlice{
		UserMods.RandomID(f),
		UserMods.RandomEmail(f),
		UserMods.RandomName(f),
		UserMods.RandomStatus(f),
		UserMods.RandomCreatedAt(f),
		UserMods.RandomUpdatedAt(f),
		UserMods.RandomPasswordHash(f),
		UserMods.RandomGlobalRole(f),
	}
}

// Set the model columns to this value
func (m userMods) ID(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) IDFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m userMods) UnsetID() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomID(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.ID = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Email(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) EmailFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = f
	})
}

// Clear any values for the column
func (m userMods) UnsetEmail() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomEmail(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Email = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Name(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) NameFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m userMods) UnsetName() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomName(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) Status(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Status = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) StatusFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m userMods) UnsetStatus() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomStatus(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.Status = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) CreatedAt(val time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userMods) CreatedAtFunc(f func() time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetCreatedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomCreatedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.CreatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) UpdatedAt(val time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = func() time.Time { return val }
	})
}

// Set the Column from the function
func (m userMods) UpdatedAtFunc(f func() time.Time) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = f
	})
}

// Clear any values for the column
func (m userMods) UnsetUpdatedAt() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomUpdatedAt(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.UpdatedAt = func() time.Time {
			return random_time_Time(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) PasswordHash(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.PasswordHash = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) PasswordHashFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.PasswordHash = f
	})
}

// Clear any values for the column
func (m userMods) UnsetPasswordHash() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.PasswordHash = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomPasswordHash(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.PasswordHash = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m userMods) GlobalRole(val string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GlobalRole = func() string { return val }
	})
}

// Set the Column from the function
func (m userMods) GlobalRoleFunc(f func() string) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GlobalRole = f
	})
}

// Clear any values for the column
func (m userMods) UnsetGlobalRole() UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GlobalRole = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m userMods) RandomGlobalRole(f *faker.Faker) UserMod {
	return UserModFunc(func(_ context.Context, o *UserTemplate) {
		o.GlobalRole = func() string {
			return random_string(f)
		}
	})
}

func (m userMods) WithParentsCascading() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		if isDone, _ := userWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = userWithParentsCascadingCtx.WithValue(ctx, true)
	})
}

func (m userMods) WithCreatedByAPITokens(number int, related *APITokenTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.CreatedByAPITokens = []*userRCreatedByAPITokensR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewCreatedByAPITokens(number int, mods ...APITokenMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewAPITokenWithContext(ctx, mods...)
		m.WithCreatedByAPITokens(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddCreatedByAPITokens(number int, related *APITokenTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.CreatedByAPITokens = append(o.r.CreatedByAPITokens, &userRCreatedByAPITokensR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewCreatedByAPITokens(number int, mods ...APITokenMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewAPITokenWithContext(ctx, mods...)
		m.AddCreatedByAPITokens(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingCreatedByAPITokens(existingModels ...*models.APIToken) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.CreatedByAPITokens = append(o.r.CreatedByAPITokens, &userRCreatedByAPITokensR{
				o: o.f.fromExistingAPIToken(ctx, em),
			})
		}
	})
}

func (m userMods) WithoutCreatedByAPITokens() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.CreatedByAPITokens = nil
	})
}

func (m userMods) WithApprovedByApprovals(number int, related *ApprovalTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ApprovedByApprovals = []*userRApprovedByApprovalsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewApprovedByApprovals(number int, mods ...ApprovalMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewApprovalWithContext(ctx, mods...)
		m.WithApprovedByApprovals(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddApprovedByApprovals(number int, related *ApprovalTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ApprovedByApprovals = append(o.r.ApprovedByApprovals, &userRApprovedByApprovalsR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewApprovedByApprovals(number int, mods ...ApprovalMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewApprovalWithContext(ctx, mods...)
		m.AddApprovedByApprovals(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingApprovedByApprovals(existingModels ...*models.Approval) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.ApprovedByApprovals = append(o.r.ApprovedByApprovals, &userRApprovedByApprovalsR{
				o: o.f.fromExistingApproval(ctx, em),
			})
		}
	})
}

func (m userMods) WithoutApprovedByApprovals() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ApprovedByApprovals = nil
	})
}

func (m userMods) WithRequestedByApprovals(number int, related *ApprovalTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RequestedByApprovals = []*userRRequestedByApprovalsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewRequestedByApprovals(number int, mods ...ApprovalMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewApprovalWithContext(ctx, mods...)
		m.WithRequestedByApprovals(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddRequestedByApprovals(number int, related *ApprovalTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RequestedByApprovals = append(o.r.RequestedByApprovals, &userRRequestedByApprovalsR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewRequestedByApprovals(number int, mods ...ApprovalMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewApprovalWithContext(ctx, mods...)
		m.AddRequestedByApprovals(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingRequestedByApprovals(existingModels ...*models.Approval) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.RequestedByApprovals = append(o.r.RequestedByApprovals, &userRRequestedByApprovalsR{
				o: o.f.fromExistingApproval(ctx, em),
			})
		}
	})
}

func (m userMods) WithoutRequestedByApprovals() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RequestedByApprovals = nil
	})
}

func (m userMods) WithProjectMembers(number int, related *ProjectMemberTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ProjectMembers = []*userRProjectMembersR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewProjectMembers(number int, mods ...ProjectMemberMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewProjectMemberWithContext(ctx, mods...)
		m.WithProjectMembers(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddProjectMembers(number int, related *ProjectMemberTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ProjectMembers = append(o.r.ProjectMembers, &userRProjectMembersR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewProjectMembers(number int, mods ...ProjectMemberMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewProjectMemberWithContext(ctx, mods...)
		m.AddProjectMembers(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingProjectMembers(existingModels ...*models.ProjectMember) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.ProjectMembers = append(o.r.ProjectMembers, &userRProjectMembersR{
				o: o.f.fromExistingProjectMember(ctx, em),
			})
		}
	})
}

func (m userMods) WithoutProjectMembers() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.ProjectMembers = nil
	})
}

func (m userMods) WithSessions(number int, related *SessionTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Sessions = []*userRSessionsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewSessions(number int, mods ...SessionMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewSessionWithContext(ctx, mods...)
		m.WithSessions(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddSessions(number int, related *SessionTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Sessions = append(o.r.Sessions, &userRSessionsR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewSessions(number int, mods ...SessionMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewSessionWithContext(ctx, mods...)
		m.AddSessions(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingSessions(existingModels ...*models.Session) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.Sessions = append(o.r.Sessions, &userRSessionsR{
				o: o.f.fromExistingSession(ctx, em),
			})
		}
	})
}

func (m userMods) WithoutSessions() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.Sessions = nil
	})
}

func (m userMods) WithRequestedByTaskRuns(number int, related *TaskRunTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RequestedByTaskRuns = []*userRRequestedByTaskRunsR{{
			number: number,
			o:      related,
		}}
	})
}

func (m userMods) WithNewRequestedByTaskRuns(number int, mods ...TaskRunMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewTaskRunWithContext(ctx, mods...)
		m.WithRequestedByTaskRuns(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddRequestedByTaskRuns(number int, related *TaskRunTemplate) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RequestedByTaskRuns = append(o.r.RequestedByTaskRuns, &userRRequestedByTaskRunsR{
			number: number,
			o:      related,
		})
	})
}

func (m userMods) AddNewRequestedByTaskRuns(number int, mods ...TaskRunMod) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		related := o.f.NewTaskRunWithContext(ctx, mods...)
		m.AddRequestedByTaskRuns(number, related).Apply(ctx, o)
	})
}

func (m userMods) AddExistingRequestedByTaskRuns(existingModels ...*models.TaskRun) UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		for _, em := range existingModels {
			o.r.RequestedByTaskRuns = append(o.r.RequestedByTaskRuns, &userRRequestedByTaskRunsR{
				o: o.f.fromExistingTaskRun(ctx, em),
			})
		}
	})
}

func (m userMods) WithoutRequestedByTaskRuns() UserMod {
	return UserModFunc(func(ctx context.Context, o *UserTemplate) {
		o.r.RequestedByTaskRuns = nil
	})
}
